#!/bin/bash
# Hook: blockiert AI-Attribution in Commit-Messages.
# Laeuft als PreToolUse auf dem Bash-Tool, wenn `git commit` erkannt wird.
# Exit 2 = blockieren, Exit 0 = erlauben.
#
# WARUM DAS EIN HOOK IST UND KEINE BITTE:
# Die Regel "keine AI-Attribution" stand bis 2026-08-24 dreimal als Prosa in CLAUDE.md und
# MEMORY.md. Gleichzeitig weist der Harness-Systemprompt Claude aktiv an, Commit-Messages mit
# `Co-Authored-By: Claude ...` und einer `Claude-Session:`-Zeile zu beenden. Eine advisory Regel
# stand damit gegen eine Systemprompt-Anweisung — dass es gutging, war Disziplin, keine
# Absicherung. Als Hook gewinnt die Regel deterministisch.
#
# ANGELEGT von der Setup-Kur 2026-08-24. Diese Datei gehoert ins claude-command-center
# zurueckgespielt (dieselbe Source-of-Truth wie check-commit-message.sh), sonst ueberschreibt
# der naechste sync.ps1-Lauf sie oder laesst sie in anderen Projekten fehlen.

INPUT=$(cat)

# Nur bei echten Commits pruefen. `git commit` deckt auch `--amend` ab.
echo "$INPUT" | grep -q 'git commit' || exit 0

# Bewusst das GESAMTE Kommando pruefen, nicht nur den -m-Teil: Attribution kommt genauso ueber
# Heredocs (`git commit -F -`, `-m @'...'@`) herein, die eine -m-Extraktion nicht sieht. Genau
# an dieser Luecke scheitert check-commit-message.sh, und die soll sich hier nicht wiederholen.
HIT=""

# Menschliche Co-Autoren (Luke, Nico, ...) bleiben ausdruecklich erlaubt — geblockt wird nur,
# wenn in derselben Zeile ein KI-Name steht.
if echo "$INPUT" | grep -qiE 'co-authored-by:[^"\\]*(claude|anthropic|copilot|cursor|gpt)'; then
  HIT="Co-Authored-By mit KI-Name"
fi

if echo "$INPUT" | grep -qiE 'generated with|generated by (claude|anthropic|ai)|written by claude'; then
  HIT="${HIT:+$HIT, }Generated-with-Hinweis"
fi

if echo "$INPUT" | grep -qE 'Claude-Session:|claude\.ai/code/session'; then
  HIT="${HIT:+$HIT, }Claude-Session-Link"
fi

# Robot-Emoji (U+1F916) — taucht in den Standard-Vorlagen der Harness auf.
# Zwei Formen noetig: als rohe UTF-8-Bytes, und als JSON-escaptes Surrogatpaar (🤖),
# denn je nach Serialisierung kommt das Zeichen so oder so im Hook-stdin an. Nur die PCRE-Form
# \x{1F916} zu pruefen reichte nicht — der Fall ging im Test still durch.
if printf '%s' "$INPUT" | LC_ALL=C grep -qF "$(printf '\xf0\x9f\xa4\x96')" \
   || printf '%s' "$INPUT" | grep -qiF '🤖' \
   || printf '%s' "$INPUT" | grep -qi 'ud83e.udd16'; then
  HIT="${HIT:+$HIT, }Robot-Emoji"
fi

if [ -n "$HIT" ]; then
  echo "BLOCKED: AI-Attribution in der Commit-Message ($HIT)." >&2
  echo "In diesem Repo gilt: keine Co-Authored-By-Zeile mit KI-Namen, kein 'Generated with'," >&2
  echo "kein Session-Link, kein Robot-Emoji. Menschliche Co-Autoren sind erlaubt." >&2
  echo "Commit-Message ohne diese Zeilen neu absetzen." >&2
  exit 2
fi

exit 0
