// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/document/v1/document.proto

package documentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentService_CreateFolder_FullMethodName            = "/document.v1.DocumentService/CreateFolder"
	DocumentService_GetFolder_FullMethodName               = "/document.v1.DocumentService/GetFolder"
	DocumentService_ListFolders_FullMethodName             = "/document.v1.DocumentService/ListFolders"
	DocumentService_UpdateFolder_FullMethodName            = "/document.v1.DocumentService/UpdateFolder"
	DocumentService_DeleteFolder_FullMethodName            = "/document.v1.DocumentService/DeleteFolder"
	DocumentService_GetFolderPath_FullMethodName           = "/document.v1.DocumentService/GetFolderPath"
	DocumentService_InitializeUserSpace_FullMethodName     = "/document.v1.DocumentService/InitializeUserSpace"
	DocumentService_InitializeTeamSpace_FullMethodName     = "/document.v1.DocumentService/InitializeTeamSpace"
	DocumentService_GetFile_FullMethodName                 = "/document.v1.DocumentService/GetFile"
	DocumentService_ListFiles_FullMethodName               = "/document.v1.DocumentService/ListFiles"
	DocumentService_UpdateFile_FullMethodName              = "/document.v1.DocumentService/UpdateFile"
	DocumentService_DeleteFile_FullMethodName              = "/document.v1.DocumentService/DeleteFile"
	DocumentService_CopyFile_FullMethodName                = "/document.v1.DocumentService/CopyFile"
	DocumentService_MoveFile_FullMethodName                = "/document.v1.DocumentService/MoveFile"
	DocumentService_GetFileDownloadURL_FullMethodName      = "/document.v1.DocumentService/GetFileDownloadURL"
	DocumentService_CreateFileVersion_FullMethodName       = "/document.v1.DocumentService/CreateFileVersion"
	DocumentService_ListFileVersions_FullMethodName        = "/document.v1.DocumentService/ListFileVersions"
	DocumentService_RevertFileVersion_FullMethodName       = "/document.v1.DocumentService/RevertFileVersion"
	DocumentService_ListFileActivity_FullMethodName        = "/document.v1.DocumentService/ListFileActivity"
	DocumentService_RegisterUploadedFile_FullMethodName    = "/document.v1.DocumentService/RegisterUploadedFile"
	DocumentService_ShareEntity_FullMethodName             = "/document.v1.DocumentService/ShareEntity"
	DocumentService_UnshareEntity_FullMethodName           = "/document.v1.DocumentService/UnshareEntity"
	DocumentService_ListShares_FullMethodName              = "/document.v1.DocumentService/ListShares"
	DocumentService_ListSharedWithMe_FullMethodName        = "/document.v1.DocumentService/ListSharedWithMe"
	DocumentService_CreateTag_FullMethodName               = "/document.v1.DocumentService/CreateTag"
	DocumentService_ListTags_FullMethodName                = "/document.v1.DocumentService/ListTags"
	DocumentService_DeleteTag_FullMethodName               = "/document.v1.DocumentService/DeleteTag"
	DocumentService_TagFile_FullMethodName                 = "/document.v1.DocumentService/TagFile"
	DocumentService_UntagFile_FullMethodName               = "/document.v1.DocumentService/UntagFile"
	DocumentService_LinkFileToEntity_FullMethodName        = "/document.v1.DocumentService/LinkFileToEntity"
	DocumentService_UnlinkFileFromEntity_FullMethodName    = "/document.v1.DocumentService/UnlinkFileFromEntity"
	DocumentService_ListFileEntityLinks_FullMethodName     = "/document.v1.DocumentService/ListFileEntityLinks"
	DocumentService_SearchFiles_FullMethodName             = "/document.v1.DocumentService/SearchFiles"
	DocumentService_ListVirtualFiles_FullMethodName        = "/document.v1.DocumentService/ListVirtualFiles"
	DocumentService_GenerateWOPIToken_FullMethodName       = "/document.v1.DocumentService/GenerateWOPIToken"
	DocumentService_GetWOPIDiscovery_FullMethodName        = "/document.v1.DocumentService/GetWOPIDiscovery"
	DocumentService_GetPresignedUploadURL_FullMethodName   = "/document.v1.DocumentService/GetPresignedUploadURL"
	DocumentService_GetPresignedDownloadURL_FullMethodName = "/document.v1.DocumentService/GetPresignedDownloadURL"
)

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentServiceClient interface {
	// ==================== Folder operations ====================
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error)
	GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*GetFolderResponse, error)
	ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*ListFoldersResponse, error)
	UpdateFolder(ctx context.Context, in *UpdateFolderRequest, opts ...grpc.CallOption) (*UpdateFolderResponse, error)
	DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error)
	GetFolderPath(ctx context.Context, in *GetFolderPathRequest, opts ...grpc.CallOption) (*GetFolderPathResponse, error)
	InitializeUserSpace(ctx context.Context, in *InitializeUserSpaceRequest, opts ...grpc.CallOption) (*InitializeUserSpaceResponse, error)
	InitializeTeamSpace(ctx context.Context, in *InitializeTeamSpaceRequest, opts ...grpc.CallOption) (*InitializeTeamSpaceResponse, error)
	// ==================== File operations ====================
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	UpdateFile(ctx context.Context, in *UpdateFileRequest, opts ...grpc.CallOption) (*UpdateFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*CopyFileResponse, error)
	MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*MoveFileResponse, error)
	GetFileDownloadURL(ctx context.Context, in *GetFileDownloadURLRequest, opts ...grpc.CallOption) (*GetFileDownloadURLResponse, error)
	CreateFileVersion(ctx context.Context, in *CreateFileVersionRequest, opts ...grpc.CallOption) (*CreateFileVersionResponse, error)
	ListFileVersions(ctx context.Context, in *ListFileVersionsRequest, opts ...grpc.CallOption) (*ListFileVersionsResponse, error)
	RevertFileVersion(ctx context.Context, in *RevertFileVersionRequest, opts ...grpc.CallOption) (*RevertFileVersionResponse, error)
	ListFileActivity(ctx context.Context, in *ListFileActivityRequest, opts ...grpc.CallOption) (*ListFileActivityResponse, error)
	// Registers metadata for a file already uploaded to object storage via a
	// presigned PUT URL (browser-direct upload). Does not touch object storage.
	RegisterUploadedFile(ctx context.Context, in *RegisterUploadedFileRequest, opts ...grpc.CallOption) (*RegisterUploadedFileResponse, error)
	// ==================== Share operations ====================
	ShareEntity(ctx context.Context, in *ShareEntityRequest, opts ...grpc.CallOption) (*ShareEntityResponse, error)
	UnshareEntity(ctx context.Context, in *UnshareEntityRequest, opts ...grpc.CallOption) (*UnshareEntityResponse, error)
	ListShares(ctx context.Context, in *ListSharesRequest, opts ...grpc.CallOption) (*ListSharesResponse, error)
	ListSharedWithMe(ctx context.Context, in *ListSharedWithMeRequest, opts ...grpc.CallOption) (*ListSharedWithMeResponse, error)
	// ==================== Tag operations ====================
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	TagFile(ctx context.Context, in *TagFileRequest, opts ...grpc.CallOption) (*TagFileResponse, error)
	UntagFile(ctx context.Context, in *UntagFileRequest, opts ...grpc.CallOption) (*UntagFileResponse, error)
	// ==================== Entity link operations ====================
	LinkFileToEntity(ctx context.Context, in *LinkFileToEntityRequest, opts ...grpc.CallOption) (*LinkFileToEntityResponse, error)
	UnlinkFileFromEntity(ctx context.Context, in *UnlinkFileFromEntityRequest, opts ...grpc.CallOption) (*UnlinkFileFromEntityResponse, error)
	ListFileEntityLinks(ctx context.Context, in *ListFileEntityLinksRequest, opts ...grpc.CallOption) (*ListFileEntityLinksResponse, error)
	// ==================== Search operations ====================
	SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*SearchFilesResponse, error)
	ListVirtualFiles(ctx context.Context, in *ListVirtualFilesRequest, opts ...grpc.CallOption) (*ListVirtualFilesResponse, error)
	// ==================== WOPI operations ====================
	GenerateWOPIToken(ctx context.Context, in *GenerateWOPITokenRequest, opts ...grpc.CallOption) (*GenerateWOPITokenResponse, error)
	GetWOPIDiscovery(ctx context.Context, in *GetWOPIDiscoveryRequest, opts ...grpc.CallOption) (*GetWOPIDiscoveryResponse, error)
	// ==================== Presigned URL operations ====================
	GetPresignedUploadURL(ctx context.Context, in *GetPresignedUploadURLRequest, opts ...grpc.CallOption) (*GetPresignedUploadURLResponse, error)
	GetPresignedDownloadURL(ctx context.Context, in *GetPresignedDownloadURLRequest, opts ...grpc.CallOption) (*GetPresignedDownloadURLResponse, error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFolderResponse)
	err := c.cc.Invoke(ctx, DocumentService_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetFolder(ctx context.Context, in *GetFolderRequest, opts ...grpc.CallOption) (*GetFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFolderResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*ListFoldersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFoldersResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UpdateFolder(ctx context.Context, in *UpdateFolderRequest, opts ...grpc.CallOption) (*UpdateFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFolderResponse)
	err := c.cc.Invoke(ctx, DocumentService_UpdateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFolderResponse)
	err := c.cc.Invoke(ctx, DocumentService_DeleteFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetFolderPath(ctx context.Context, in *GetFolderPathRequest, opts ...grpc.CallOption) (*GetFolderPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFolderPathResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetFolderPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) InitializeUserSpace(ctx context.Context, in *InitializeUserSpaceRequest, opts ...grpc.CallOption) (*InitializeUserSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeUserSpaceResponse)
	err := c.cc.Invoke(ctx, DocumentService_InitializeUserSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) InitializeTeamSpace(ctx context.Context, in *InitializeTeamSpaceRequest, opts ...grpc.CallOption) (*InitializeTeamSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeTeamSpaceResponse)
	err := c.cc.Invoke(ctx, DocumentService_InitializeTeamSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UpdateFile(ctx context.Context, in *UpdateFileRequest, opts ...grpc.CallOption) (*UpdateFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFileResponse)
	err := c.cc.Invoke(ctx, DocumentService_UpdateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, DocumentService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*CopyFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyFileResponse)
	err := c.cc.Invoke(ctx, DocumentService_CopyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*MoveFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveFileResponse)
	err := c.cc.Invoke(ctx, DocumentService_MoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetFileDownloadURL(ctx context.Context, in *GetFileDownloadURLRequest, opts ...grpc.CallOption) (*GetFileDownloadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileDownloadURLResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetFileDownloadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) CreateFileVersion(ctx context.Context, in *CreateFileVersionRequest, opts ...grpc.CallOption) (*CreateFileVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileVersionResponse)
	err := c.cc.Invoke(ctx, DocumentService_CreateFileVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListFileVersions(ctx context.Context, in *ListFileVersionsRequest, opts ...grpc.CallOption) (*ListFileVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileVersionsResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListFileVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) RevertFileVersion(ctx context.Context, in *RevertFileVersionRequest, opts ...grpc.CallOption) (*RevertFileVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertFileVersionResponse)
	err := c.cc.Invoke(ctx, DocumentService_RevertFileVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListFileActivity(ctx context.Context, in *ListFileActivityRequest, opts ...grpc.CallOption) (*ListFileActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileActivityResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListFileActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) RegisterUploadedFile(ctx context.Context, in *RegisterUploadedFileRequest, opts ...grpc.CallOption) (*RegisterUploadedFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUploadedFileResponse)
	err := c.cc.Invoke(ctx, DocumentService_RegisterUploadedFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ShareEntity(ctx context.Context, in *ShareEntityRequest, opts ...grpc.CallOption) (*ShareEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareEntityResponse)
	err := c.cc.Invoke(ctx, DocumentService_ShareEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UnshareEntity(ctx context.Context, in *UnshareEntityRequest, opts ...grpc.CallOption) (*UnshareEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnshareEntityResponse)
	err := c.cc.Invoke(ctx, DocumentService_UnshareEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListShares(ctx context.Context, in *ListSharesRequest, opts ...grpc.CallOption) (*ListSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharesResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListSharedWithMe(ctx context.Context, in *ListSharedWithMeRequest, opts ...grpc.CallOption) (*ListSharedWithMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharedWithMeResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListSharedWithMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, DocumentService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, DocumentService_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) TagFile(ctx context.Context, in *TagFileRequest, opts ...grpc.CallOption) (*TagFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagFileResponse)
	err := c.cc.Invoke(ctx, DocumentService_TagFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UntagFile(ctx context.Context, in *UntagFileRequest, opts ...grpc.CallOption) (*UntagFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UntagFileResponse)
	err := c.cc.Invoke(ctx, DocumentService_UntagFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) LinkFileToEntity(ctx context.Context, in *LinkFileToEntityRequest, opts ...grpc.CallOption) (*LinkFileToEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkFileToEntityResponse)
	err := c.cc.Invoke(ctx, DocumentService_LinkFileToEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UnlinkFileFromEntity(ctx context.Context, in *UnlinkFileFromEntityRequest, opts ...grpc.CallOption) (*UnlinkFileFromEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkFileFromEntityResponse)
	err := c.cc.Invoke(ctx, DocumentService_UnlinkFileFromEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListFileEntityLinks(ctx context.Context, in *ListFileEntityLinksRequest, opts ...grpc.CallOption) (*ListFileEntityLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileEntityLinksResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListFileEntityLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*SearchFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFilesResponse)
	err := c.cc.Invoke(ctx, DocumentService_SearchFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ListVirtualFiles(ctx context.Context, in *ListVirtualFilesRequest, opts ...grpc.CallOption) (*ListVirtualFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVirtualFilesResponse)
	err := c.cc.Invoke(ctx, DocumentService_ListVirtualFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GenerateWOPIToken(ctx context.Context, in *GenerateWOPITokenRequest, opts ...grpc.CallOption) (*GenerateWOPITokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateWOPITokenResponse)
	err := c.cc.Invoke(ctx, DocumentService_GenerateWOPIToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetWOPIDiscovery(ctx context.Context, in *GetWOPIDiscoveryRequest, opts ...grpc.CallOption) (*GetWOPIDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWOPIDiscoveryResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetWOPIDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetPresignedUploadURL(ctx context.Context, in *GetPresignedUploadURLRequest, opts ...grpc.CallOption) (*GetPresignedUploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedUploadURLResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetPresignedUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetPresignedDownloadURL(ctx context.Context, in *GetPresignedDownloadURLRequest, opts ...grpc.CallOption) (*GetPresignedDownloadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedDownloadURLResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetPresignedDownloadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
// All implementations must embed UnimplementedDocumentServiceServer
// for forward compatibility.
type DocumentServiceServer interface {
	// ==================== Folder operations ====================
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error)
	GetFolder(context.Context, *GetFolderRequest) (*GetFolderResponse, error)
	ListFolders(context.Context, *ListFoldersRequest) (*ListFoldersResponse, error)
	UpdateFolder(context.Context, *UpdateFolderRequest) (*UpdateFolderResponse, error)
	DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error)
	GetFolderPath(context.Context, *GetFolderPathRequest) (*GetFolderPathResponse, error)
	InitializeUserSpace(context.Context, *InitializeUserSpaceRequest) (*InitializeUserSpaceResponse, error)
	InitializeTeamSpace(context.Context, *InitializeTeamSpaceRequest) (*InitializeTeamSpaceResponse, error)
	// ==================== File operations ====================
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	UpdateFile(context.Context, *UpdateFileRequest) (*UpdateFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	CopyFile(context.Context, *CopyFileRequest) (*CopyFileResponse, error)
	MoveFile(context.Context, *MoveFileRequest) (*MoveFileResponse, error)
	GetFileDownloadURL(context.Context, *GetFileDownloadURLRequest) (*GetFileDownloadURLResponse, error)
	CreateFileVersion(context.Context, *CreateFileVersionRequest) (*CreateFileVersionResponse, error)
	ListFileVersions(context.Context, *ListFileVersionsRequest) (*ListFileVersionsResponse, error)
	RevertFileVersion(context.Context, *RevertFileVersionRequest) (*RevertFileVersionResponse, error)
	ListFileActivity(context.Context, *ListFileActivityRequest) (*ListFileActivityResponse, error)
	// Registers metadata for a file already uploaded to object storage via a
	// presigned PUT URL (browser-direct upload). Does not touch object storage.
	RegisterUploadedFile(context.Context, *RegisterUploadedFileRequest) (*RegisterUploadedFileResponse, error)
	// ==================== Share operations ====================
	ShareEntity(context.Context, *ShareEntityRequest) (*ShareEntityResponse, error)
	UnshareEntity(context.Context, *UnshareEntityRequest) (*UnshareEntityResponse, error)
	ListShares(context.Context, *ListSharesRequest) (*ListSharesResponse, error)
	ListSharedWithMe(context.Context, *ListSharedWithMeRequest) (*ListSharedWithMeResponse, error)
	// ==================== Tag operations ====================
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	TagFile(context.Context, *TagFileRequest) (*TagFileResponse, error)
	UntagFile(context.Context, *UntagFileRequest) (*UntagFileResponse, error)
	// ==================== Entity link operations ====================
	LinkFileToEntity(context.Context, *LinkFileToEntityRequest) (*LinkFileToEntityResponse, error)
	UnlinkFileFromEntity(context.Context, *UnlinkFileFromEntityRequest) (*UnlinkFileFromEntityResponse, error)
	ListFileEntityLinks(context.Context, *ListFileEntityLinksRequest) (*ListFileEntityLinksResponse, error)
	// ==================== Search operations ====================
	SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesResponse, error)
	ListVirtualFiles(context.Context, *ListVirtualFilesRequest) (*ListVirtualFilesResponse, error)
	// ==================== WOPI operations ====================
	GenerateWOPIToken(context.Context, *GenerateWOPITokenRequest) (*GenerateWOPITokenResponse, error)
	GetWOPIDiscovery(context.Context, *GetWOPIDiscoveryRequest) (*GetWOPIDiscoveryResponse, error)
	// ==================== Presigned URL operations ====================
	GetPresignedUploadURL(context.Context, *GetPresignedUploadURLRequest) (*GetPresignedUploadURLResponse, error)
	GetPresignedDownloadURL(context.Context, *GetPresignedDownloadURLRequest) (*GetPresignedDownloadURLResponse, error)
	mustEmbedUnimplementedDocumentServiceServer()
}

// UnimplementedDocumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentServiceServer struct{}

func (UnimplementedDocumentServiceServer) CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedDocumentServiceServer) GetFolder(context.Context, *GetFolderRequest) (*GetFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFolder not implemented")
}
func (UnimplementedDocumentServiceServer) ListFolders(context.Context, *ListFoldersRequest) (*ListFoldersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFolders not implemented")
}
func (UnimplementedDocumentServiceServer) UpdateFolder(context.Context, *UpdateFolderRequest) (*UpdateFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFolder not implemented")
}
func (UnimplementedDocumentServiceServer) DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFolder not implemented")
}
func (UnimplementedDocumentServiceServer) GetFolderPath(context.Context, *GetFolderPathRequest) (*GetFolderPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFolderPath not implemented")
}
func (UnimplementedDocumentServiceServer) InitializeUserSpace(context.Context, *InitializeUserSpaceRequest) (*InitializeUserSpaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeUserSpace not implemented")
}
func (UnimplementedDocumentServiceServer) InitializeTeamSpace(context.Context, *InitializeTeamSpaceRequest) (*InitializeTeamSpaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeTeamSpace not implemented")
}
func (UnimplementedDocumentServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedDocumentServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedDocumentServiceServer) UpdateFile(context.Context, *UpdateFileRequest) (*UpdateFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFile not implemented")
}
func (UnimplementedDocumentServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedDocumentServiceServer) CopyFile(context.Context, *CopyFileRequest) (*CopyFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedDocumentServiceServer) MoveFile(context.Context, *MoveFileRequest) (*MoveFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveFile not implemented")
}
func (UnimplementedDocumentServiceServer) GetFileDownloadURL(context.Context, *GetFileDownloadURLRequest) (*GetFileDownloadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileDownloadURL not implemented")
}
func (UnimplementedDocumentServiceServer) CreateFileVersion(context.Context, *CreateFileVersionRequest) (*CreateFileVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFileVersion not implemented")
}
func (UnimplementedDocumentServiceServer) ListFileVersions(context.Context, *ListFileVersionsRequest) (*ListFileVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFileVersions not implemented")
}
func (UnimplementedDocumentServiceServer) RevertFileVersion(context.Context, *RevertFileVersionRequest) (*RevertFileVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevertFileVersion not implemented")
}
func (UnimplementedDocumentServiceServer) ListFileActivity(context.Context, *ListFileActivityRequest) (*ListFileActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFileActivity not implemented")
}
func (UnimplementedDocumentServiceServer) RegisterUploadedFile(context.Context, *RegisterUploadedFileRequest) (*RegisterUploadedFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUploadedFile not implemented")
}
func (UnimplementedDocumentServiceServer) ShareEntity(context.Context, *ShareEntityRequest) (*ShareEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareEntity not implemented")
}
func (UnimplementedDocumentServiceServer) UnshareEntity(context.Context, *UnshareEntityRequest) (*UnshareEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnshareEntity not implemented")
}
func (UnimplementedDocumentServiceServer) ListShares(context.Context, *ListSharesRequest) (*ListSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShares not implemented")
}
func (UnimplementedDocumentServiceServer) ListSharedWithMe(context.Context, *ListSharedWithMeRequest) (*ListSharedWithMeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSharedWithMe not implemented")
}
func (UnimplementedDocumentServiceServer) CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedDocumentServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedDocumentServiceServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedDocumentServiceServer) TagFile(context.Context, *TagFileRequest) (*TagFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagFile not implemented")
}
func (UnimplementedDocumentServiceServer) UntagFile(context.Context, *UntagFileRequest) (*UntagFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UntagFile not implemented")
}
func (UnimplementedDocumentServiceServer) LinkFileToEntity(context.Context, *LinkFileToEntityRequest) (*LinkFileToEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkFileToEntity not implemented")
}
func (UnimplementedDocumentServiceServer) UnlinkFileFromEntity(context.Context, *UnlinkFileFromEntityRequest) (*UnlinkFileFromEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkFileFromEntity not implemented")
}
func (UnimplementedDocumentServiceServer) ListFileEntityLinks(context.Context, *ListFileEntityLinksRequest) (*ListFileEntityLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFileEntityLinks not implemented")
}
func (UnimplementedDocumentServiceServer) SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFiles not implemented")
}
func (UnimplementedDocumentServiceServer) ListVirtualFiles(context.Context, *ListVirtualFilesRequest) (*ListVirtualFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVirtualFiles not implemented")
}
func (UnimplementedDocumentServiceServer) GenerateWOPIToken(context.Context, *GenerateWOPITokenRequest) (*GenerateWOPITokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateWOPIToken not implemented")
}
func (UnimplementedDocumentServiceServer) GetWOPIDiscovery(context.Context, *GetWOPIDiscoveryRequest) (*GetWOPIDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWOPIDiscovery not implemented")
}
func (UnimplementedDocumentServiceServer) GetPresignedUploadURL(context.Context, *GetPresignedUploadURLRequest) (*GetPresignedUploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresignedUploadURL not implemented")
}
func (UnimplementedDocumentServiceServer) GetPresignedDownloadURL(context.Context, *GetPresignedDownloadURLRequest) (*GetPresignedDownloadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresignedDownloadURL not implemented")
}
func (UnimplementedDocumentServiceServer) mustEmbedUnimplementedDocumentServiceServer() {}
func (UnimplementedDocumentServiceServer) testEmbeddedByValue()                         {}

// UnsafeDocumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServiceServer will
// result in compilation errors.
type UnsafeDocumentServiceServer interface {
	mustEmbedUnimplementedDocumentServiceServer()
}

func RegisterDocumentServiceServer(s grpc.ServiceRegistrar, srv DocumentServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentService_ServiceDesc, srv)
}

func _DocumentService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetFolder(ctx, req.(*GetFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListFolders(ctx, req.(*ListFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UpdateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UpdateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UpdateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UpdateFolder(ctx, req.(*UpdateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_DeleteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).DeleteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_DeleteFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).DeleteFolder(ctx, req.(*DeleteFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetFolderPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFolderPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetFolderPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetFolderPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetFolderPath(ctx, req.(*GetFolderPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_InitializeUserSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeUserSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).InitializeUserSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_InitializeUserSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).InitializeUserSpace(ctx, req.(*InitializeUserSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_InitializeTeamSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeTeamSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).InitializeTeamSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_InitializeTeamSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).InitializeTeamSpace(ctx, req.(*InitializeTeamSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UpdateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UpdateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UpdateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UpdateFile(ctx, req.(*UpdateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_CopyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CopyFile(ctx, req.(*CopyFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_MoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).MoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_MoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).MoveFile(ctx, req.(*MoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetFileDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileDownloadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetFileDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetFileDownloadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetFileDownloadURL(ctx, req.(*GetFileDownloadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_CreateFileVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CreateFileVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_CreateFileVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CreateFileVersion(ctx, req.(*CreateFileVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListFileVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListFileVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListFileVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListFileVersions(ctx, req.(*ListFileVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_RevertFileVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertFileVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).RevertFileVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_RevertFileVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).RevertFileVersion(ctx, req.(*RevertFileVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListFileActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListFileActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListFileActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListFileActivity(ctx, req.(*ListFileActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_RegisterUploadedFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUploadedFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).RegisterUploadedFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_RegisterUploadedFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).RegisterUploadedFile(ctx, req.(*RegisterUploadedFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ShareEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ShareEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ShareEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ShareEntity(ctx, req.(*ShareEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UnshareEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnshareEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UnshareEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UnshareEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UnshareEntity(ctx, req.(*UnshareEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListShares(ctx, req.(*ListSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListSharedWithMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharedWithMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListSharedWithMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListSharedWithMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListSharedWithMe(ctx, req.(*ListSharedWithMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_TagFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).TagFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_TagFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).TagFile(ctx, req.(*TagFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UntagFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntagFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UntagFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UntagFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UntagFile(ctx, req.(*UntagFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_LinkFileToEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkFileToEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).LinkFileToEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_LinkFileToEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).LinkFileToEntity(ctx, req.(*LinkFileToEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UnlinkFileFromEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkFileFromEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UnlinkFileFromEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UnlinkFileFromEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UnlinkFileFromEntity(ctx, req.(*UnlinkFileFromEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListFileEntityLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileEntityLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListFileEntityLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListFileEntityLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListFileEntityLinks(ctx, req.(*ListFileEntityLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_SearchFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).SearchFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_SearchFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).SearchFiles(ctx, req.(*SearchFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ListVirtualFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVirtualFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ListVirtualFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ListVirtualFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ListVirtualFiles(ctx, req.(*ListVirtualFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GenerateWOPIToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateWOPITokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GenerateWOPIToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GenerateWOPIToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GenerateWOPIToken(ctx, req.(*GenerateWOPITokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetWOPIDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWOPIDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetWOPIDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetWOPIDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetWOPIDiscovery(ctx, req.(*GetWOPIDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetPresignedUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetPresignedUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetPresignedUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetPresignedUploadURL(ctx, req.(*GetPresignedUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetPresignedDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedDownloadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetPresignedDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetPresignedDownloadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetPresignedDownloadURL(ctx, req.(*GetPresignedDownloadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentService_ServiceDesc is the grpc.ServiceDesc for DocumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "document.v1.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFolder",
			Handler:    _DocumentService_CreateFolder_Handler,
		},
		{
			MethodName: "GetFolder",
			Handler:    _DocumentService_GetFolder_Handler,
		},
		{
			MethodName: "ListFolders",
			Handler:    _DocumentService_ListFolders_Handler,
		},
		{
			MethodName: "UpdateFolder",
			Handler:    _DocumentService_UpdateFolder_Handler,
		},
		{
			MethodName: "DeleteFolder",
			Handler:    _DocumentService_DeleteFolder_Handler,
		},
		{
			MethodName: "GetFolderPath",
			Handler:    _DocumentService_GetFolderPath_Handler,
		},
		{
			MethodName: "InitializeUserSpace",
			Handler:    _DocumentService_InitializeUserSpace_Handler,
		},
		{
			MethodName: "InitializeTeamSpace",
			Handler:    _DocumentService_InitializeTeamSpace_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _DocumentService_GetFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _DocumentService_ListFiles_Handler,
		},
		{
			MethodName: "UpdateFile",
			Handler:    _DocumentService_UpdateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _DocumentService_DeleteFile_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _DocumentService_CopyFile_Handler,
		},
		{
			MethodName: "MoveFile",
			Handler:    _DocumentService_MoveFile_Handler,
		},
		{
			MethodName: "GetFileDownloadURL",
			Handler:    _DocumentService_GetFileDownloadURL_Handler,
		},
		{
			MethodName: "CreateFileVersion",
			Handler:    _DocumentService_CreateFileVersion_Handler,
		},
		{
			MethodName: "ListFileVersions",
			Handler:    _DocumentService_ListFileVersions_Handler,
		},
		{
			MethodName: "RevertFileVersion",
			Handler:    _DocumentService_RevertFileVersion_Handler,
		},
		{
			MethodName: "ListFileActivity",
			Handler:    _DocumentService_ListFileActivity_Handler,
		},
		{
			MethodName: "RegisterUploadedFile",
			Handler:    _DocumentService_RegisterUploadedFile_Handler,
		},
		{
			MethodName: "ShareEntity",
			Handler:    _DocumentService_ShareEntity_Handler,
		},
		{
			MethodName: "UnshareEntity",
			Handler:    _DocumentService_UnshareEntity_Handler,
		},
		{
			MethodName: "ListShares",
			Handler:    _DocumentService_ListShares_Handler,
		},
		{
			MethodName: "ListSharedWithMe",
			Handler:    _DocumentService_ListSharedWithMe_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _DocumentService_CreateTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _DocumentService_ListTags_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _DocumentService_DeleteTag_Handler,
		},
		{
			MethodName: "TagFile",
			Handler:    _DocumentService_TagFile_Handler,
		},
		{
			MethodName: "UntagFile",
			Handler:    _DocumentService_UntagFile_Handler,
		},
		{
			MethodName: "LinkFileToEntity",
			Handler:    _DocumentService_LinkFileToEntity_Handler,
		},
		{
			MethodName: "UnlinkFileFromEntity",
			Handler:    _DocumentService_UnlinkFileFromEntity_Handler,
		},
		{
			MethodName: "ListFileEntityLinks",
			Handler:    _DocumentService_ListFileEntityLinks_Handler,
		},
		{
			MethodName: "SearchFiles",
			Handler:    _DocumentService_SearchFiles_Handler,
		},
		{
			MethodName: "ListVirtualFiles",
			Handler:    _DocumentService_ListVirtualFiles_Handler,
		},
		{
			MethodName: "GenerateWOPIToken",
			Handler:    _DocumentService_GenerateWOPIToken_Handler,
		},
		{
			MethodName: "GetWOPIDiscovery",
			Handler:    _DocumentService_GetWOPIDiscovery_Handler,
		},
		{
			MethodName: "GetPresignedUploadURL",
			Handler:    _DocumentService_GetPresignedUploadURL_Handler,
		},
		{
			MethodName: "GetPresignedDownloadURL",
			Handler:    _DocumentService_GetPresignedDownloadURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/document/v1/document.proto",
}
