version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - gosec
    - bodyclose
    - misspell
    - unconvert
  settings:
    govet:
      enable:
        - shadow
    goimports:
      local-prefixes:
        - github.com/kmuhub/kmuhub
    gosec:
      excludes:
        - G404

issues:
  exclude-dirs:
    - proto
    - bin
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
