FROM golang:1.25-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o document ./cmd/document

FROM alpine:3.20

RUN apk --no-cache add ca-certificates wget \
    poppler-utils wv antiword unrtf

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app
COPY --from=builder /build/document .

USER appuser

EXPOSE 50057 9097

CMD ["./document"]
