// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/rapporte/v1/rapporte.proto

package rapportev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RapporteService_CreateReport_FullMethodName         = "/rapporte.v1.RapporteService/CreateReport"
	RapporteService_GetReport_FullMethodName            = "/rapporte.v1.RapporteService/GetReport"
	RapporteService_UpdateReport_FullMethodName         = "/rapporte.v1.RapporteService/UpdateReport"
	RapporteService_DeleteReport_FullMethodName         = "/rapporte.v1.RapporteService/DeleteReport"
	RapporteService_ListReports_FullMethodName          = "/rapporte.v1.RapporteService/ListReports"
	RapporteService_SubmitReport_FullMethodName         = "/rapporte.v1.RapporteService/SubmitReport"
	RapporteService_ApproveReport_FullMethodName        = "/rapporte.v1.RapporteService/ApproveReport"
	RapporteService_RejectReport_FullMethodName         = "/rapporte.v1.RapporteService/RejectReport"
	RapporteService_AddLine_FullMethodName              = "/rapporte.v1.RapporteService/AddLine"
	RapporteService_UpdateLine_FullMethodName           = "/rapporte.v1.RapporteService/UpdateLine"
	RapporteService_DeleteLine_FullMethodName           = "/rapporte.v1.RapporteService/DeleteLine"
	RapporteService_ListLines_FullMethodName            = "/rapporte.v1.RapporteService/ListLines"
	RapporteService_UploadAttachment_FullMethodName     = "/rapporte.v1.RapporteService/UploadAttachment"
	RapporteService_ListAttachments_FullMethodName      = "/rapporte.v1.RapporteService/ListAttachments"
	RapporteService_DeleteAttachment_FullMethodName     = "/rapporte.v1.RapporteService/DeleteAttachment"
	RapporteService_GetReportStats_FullMethodName       = "/rapporte.v1.RapporteService/GetReportStats"
	RapporteService_ListPendingApprovals_FullMethodName = "/rapporte.v1.RapporteService/ListPendingApprovals"
	RapporteService_ExportPDF_FullMethodName            = "/rapporte.v1.RapporteService/ExportPDF"
	RapporteService_SaveSignature_FullMethodName        = "/rapporte.v1.RapporteService/SaveSignature"
)

// RapporteServiceClient is the client API for RapporteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RapporteServiceClient interface {
	// Reports
	CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	UpdateReport(ctx context.Context, in *UpdateReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	DeleteReport(ctx context.Context, in *DeleteReportRequest, opts ...grpc.CallOption) (*DeleteReportResponse, error)
	ListReports(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsResponse, error)
	// State machine
	SubmitReport(ctx context.Context, in *SubmitReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	ApproveReport(ctx context.Context, in *ApproveReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	RejectReport(ctx context.Context, in *RejectReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	// Lines
	AddLine(ctx context.Context, in *AddLineRequest, opts ...grpc.CallOption) (*LineResponse, error)
	UpdateLine(ctx context.Context, in *UpdateLineRequest, opts ...grpc.CallOption) (*LineResponse, error)
	DeleteLine(ctx context.Context, in *DeleteLineRequest, opts ...grpc.CallOption) (*DeleteLineResponse, error)
	ListLines(ctx context.Context, in *ListLinesRequest, opts ...grpc.CallOption) (*ListLinesResponse, error)
	// Attachments
	UploadAttachment(ctx context.Context, in *UploadAttachmentRequest, opts ...grpc.CallOption) (*AttachmentResponse, error)
	ListAttachments(ctx context.Context, in *ListAttachmentsRequest, opts ...grpc.CallOption) (*ListAttachmentsResponse, error)
	DeleteAttachment(ctx context.Context, in *DeleteAttachmentRequest, opts ...grpc.CallOption) (*DeleteAttachmentResponse, error)
	// Reports & export
	GetReportStats(ctx context.Context, in *GetReportStatsRequest, opts ...grpc.CallOption) (*ReportStatsResponse, error)
	ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...grpc.CallOption) (*ListReportsResponse, error)
	ExportPDF(ctx context.Context, in *ExportPDFRequest, opts ...grpc.CallOption) (*ExportPDFResponse, error)
	// Signature
	SaveSignature(ctx context.Context, in *SaveReportSignatureRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type rapporteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRapporteServiceClient(cc grpc.ClientConnInterface) RapporteServiceClient {
	return &rapporteServiceClient{cc}
}

func (c *rapporteServiceClient) CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, RapporteService_CreateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, RapporteService_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) UpdateReport(ctx context.Context, in *UpdateReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, RapporteService_UpdateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) DeleteReport(ctx context.Context, in *DeleteReportRequest, opts ...grpc.CallOption) (*DeleteReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReportResponse)
	err := c.cc.Invoke(ctx, RapporteService_DeleteReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) ListReports(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReportsResponse)
	err := c.cc.Invoke(ctx, RapporteService_ListReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) SubmitReport(ctx context.Context, in *SubmitReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, RapporteService_SubmitReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) ApproveReport(ctx context.Context, in *ApproveReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, RapporteService_ApproveReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) RejectReport(ctx context.Context, in *RejectReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, RapporteService_RejectReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) AddLine(ctx context.Context, in *AddLineRequest, opts ...grpc.CallOption) (*LineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LineResponse)
	err := c.cc.Invoke(ctx, RapporteService_AddLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) UpdateLine(ctx context.Context, in *UpdateLineRequest, opts ...grpc.CallOption) (*LineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LineResponse)
	err := c.cc.Invoke(ctx, RapporteService_UpdateLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) DeleteLine(ctx context.Context, in *DeleteLineRequest, opts ...grpc.CallOption) (*DeleteLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLineResponse)
	err := c.cc.Invoke(ctx, RapporteService_DeleteLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) ListLines(ctx context.Context, in *ListLinesRequest, opts ...grpc.CallOption) (*ListLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinesResponse)
	err := c.cc.Invoke(ctx, RapporteService_ListLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) UploadAttachment(ctx context.Context, in *UploadAttachmentRequest, opts ...grpc.CallOption) (*AttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentResponse)
	err := c.cc.Invoke(ctx, RapporteService_UploadAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) ListAttachments(ctx context.Context, in *ListAttachmentsRequest, opts ...grpc.CallOption) (*ListAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttachmentsResponse)
	err := c.cc.Invoke(ctx, RapporteService_ListAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) DeleteAttachment(ctx context.Context, in *DeleteAttachmentRequest, opts ...grpc.CallOption) (*DeleteAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAttachmentResponse)
	err := c.cc.Invoke(ctx, RapporteService_DeleteAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) GetReportStats(ctx context.Context, in *GetReportStatsRequest, opts ...grpc.CallOption) (*ReportStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatsResponse)
	err := c.cc.Invoke(ctx, RapporteService_GetReportStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...grpc.CallOption) (*ListReportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReportsResponse)
	err := c.cc.Invoke(ctx, RapporteService_ListPendingApprovals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) ExportPDF(ctx context.Context, in *ExportPDFRequest, opts ...grpc.CallOption) (*ExportPDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportPDFResponse)
	err := c.cc.Invoke(ctx, RapporteService_ExportPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rapporteServiceClient) SaveSignature(ctx context.Context, in *SaveReportSignatureRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, RapporteService_SaveSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RapporteServiceServer is the server API for RapporteService service.
// All implementations must embed UnimplementedRapporteServiceServer
// for forward compatibility.
type RapporteServiceServer interface {
	// Reports
	CreateReport(context.Context, *CreateReportRequest) (*ReportResponse, error)
	GetReport(context.Context, *GetReportRequest) (*ReportResponse, error)
	UpdateReport(context.Context, *UpdateReportRequest) (*ReportResponse, error)
	DeleteReport(context.Context, *DeleteReportRequest) (*DeleteReportResponse, error)
	ListReports(context.Context, *ListReportsRequest) (*ListReportsResponse, error)
	// State machine
	SubmitReport(context.Context, *SubmitReportRequest) (*ReportResponse, error)
	ApproveReport(context.Context, *ApproveReportRequest) (*ReportResponse, error)
	RejectReport(context.Context, *RejectReportRequest) (*ReportResponse, error)
	// Lines
	AddLine(context.Context, *AddLineRequest) (*LineResponse, error)
	UpdateLine(context.Context, *UpdateLineRequest) (*LineResponse, error)
	DeleteLine(context.Context, *DeleteLineRequest) (*DeleteLineResponse, error)
	ListLines(context.Context, *ListLinesRequest) (*ListLinesResponse, error)
	// Attachments
	UploadAttachment(context.Context, *UploadAttachmentRequest) (*AttachmentResponse, error)
	ListAttachments(context.Context, *ListAttachmentsRequest) (*ListAttachmentsResponse, error)
	DeleteAttachment(context.Context, *DeleteAttachmentRequest) (*DeleteAttachmentResponse, error)
	// Reports & export
	GetReportStats(context.Context, *GetReportStatsRequest) (*ReportStatsResponse, error)
	ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListReportsResponse, error)
	ExportPDF(context.Context, *ExportPDFRequest) (*ExportPDFResponse, error)
	// Signature
	SaveSignature(context.Context, *SaveReportSignatureRequest) (*ReportResponse, error)
	mustEmbedUnimplementedRapporteServiceServer()
}

// UnimplementedRapporteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRapporteServiceServer struct{}

func (UnimplementedRapporteServiceServer) CreateReport(context.Context, *CreateReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReport not implemented")
}
func (UnimplementedRapporteServiceServer) GetReport(context.Context, *GetReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedRapporteServiceServer) UpdateReport(context.Context, *UpdateReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReport not implemented")
}
func (UnimplementedRapporteServiceServer) DeleteReport(context.Context, *DeleteReportRequest) (*DeleteReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReport not implemented")
}
func (UnimplementedRapporteServiceServer) ListReports(context.Context, *ListReportsRequest) (*ListReportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReports not implemented")
}
func (UnimplementedRapporteServiceServer) SubmitReport(context.Context, *SubmitReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitReport not implemented")
}
func (UnimplementedRapporteServiceServer) ApproveReport(context.Context, *ApproveReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveReport not implemented")
}
func (UnimplementedRapporteServiceServer) RejectReport(context.Context, *RejectReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectReport not implemented")
}
func (UnimplementedRapporteServiceServer) AddLine(context.Context, *AddLineRequest) (*LineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddLine not implemented")
}
func (UnimplementedRapporteServiceServer) UpdateLine(context.Context, *UpdateLineRequest) (*LineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLine not implemented")
}
func (UnimplementedRapporteServiceServer) DeleteLine(context.Context, *DeleteLineRequest) (*DeleteLineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLine not implemented")
}
func (UnimplementedRapporteServiceServer) ListLines(context.Context, *ListLinesRequest) (*ListLinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLines not implemented")
}
func (UnimplementedRapporteServiceServer) UploadAttachment(context.Context, *UploadAttachmentRequest) (*AttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAttachment not implemented")
}
func (UnimplementedRapporteServiceServer) ListAttachments(context.Context, *ListAttachmentsRequest) (*ListAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAttachments not implemented")
}
func (UnimplementedRapporteServiceServer) DeleteAttachment(context.Context, *DeleteAttachmentRequest) (*DeleteAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAttachment not implemented")
}
func (UnimplementedRapporteServiceServer) GetReportStats(context.Context, *GetReportStatsRequest) (*ReportStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReportStats not implemented")
}
func (UnimplementedRapporteServiceServer) ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListReportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingApprovals not implemented")
}
func (UnimplementedRapporteServiceServer) ExportPDF(context.Context, *ExportPDFRequest) (*ExportPDFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportPDF not implemented")
}
func (UnimplementedRapporteServiceServer) SaveSignature(context.Context, *SaveReportSignatureRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSignature not implemented")
}
func (UnimplementedRapporteServiceServer) mustEmbedUnimplementedRapporteServiceServer() {}
func (UnimplementedRapporteServiceServer) testEmbeddedByValue()                         {}

// UnsafeRapporteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RapporteServiceServer will
// result in compilation errors.
type UnsafeRapporteServiceServer interface {
	mustEmbedUnimplementedRapporteServiceServer()
}

func RegisterRapporteServiceServer(s grpc.ServiceRegistrar, srv RapporteServiceServer) {
	// If the following call panics, it indicates UnimplementedRapporteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RapporteService_ServiceDesc, srv)
}

func _RapporteService_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_CreateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).CreateReport(ctx, req.(*CreateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).GetReport(ctx, req.(*GetReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_UpdateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).UpdateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_UpdateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).UpdateReport(ctx, req.(*UpdateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_DeleteReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).DeleteReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_DeleteReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).DeleteReport(ctx, req.(*DeleteReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_ListReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).ListReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_ListReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).ListReports(ctx, req.(*ListReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_SubmitReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).SubmitReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_SubmitReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).SubmitReport(ctx, req.(*SubmitReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_ApproveReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).ApproveReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_ApproveReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).ApproveReport(ctx, req.(*ApproveReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_RejectReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).RejectReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_RejectReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).RejectReport(ctx, req.(*RejectReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_AddLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).AddLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_AddLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).AddLine(ctx, req.(*AddLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_UpdateLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).UpdateLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_UpdateLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).UpdateLine(ctx, req.(*UpdateLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_DeleteLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).DeleteLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_DeleteLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).DeleteLine(ctx, req.(*DeleteLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_ListLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).ListLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_ListLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).ListLines(ctx, req.(*ListLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_UploadAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).UploadAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_UploadAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).UploadAttachment(ctx, req.(*UploadAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_ListAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).ListAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_ListAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).ListAttachments(ctx, req.(*ListAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_DeleteAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).DeleteAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_DeleteAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).DeleteAttachment(ctx, req.(*DeleteAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_GetReportStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).GetReportStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_GetReportStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).GetReportStats(ctx, req.(*GetReportStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_ListPendingApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).ListPendingApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_ListPendingApprovals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).ListPendingApprovals(ctx, req.(*ListPendingApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_ExportPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportPDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).ExportPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_ExportPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).ExportPDF(ctx, req.(*ExportPDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RapporteService_SaveSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveReportSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RapporteServiceServer).SaveSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RapporteService_SaveSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RapporteServiceServer).SaveSignature(ctx, req.(*SaveReportSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RapporteService_ServiceDesc is the grpc.ServiceDesc for RapporteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RapporteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rapporte.v1.RapporteService",
	HandlerType: (*RapporteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReport",
			Handler:    _RapporteService_CreateReport_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _RapporteService_GetReport_Handler,
		},
		{
			MethodName: "UpdateReport",
			Handler:    _RapporteService_UpdateReport_Handler,
		},
		{
			MethodName: "DeleteReport",
			Handler:    _RapporteService_DeleteReport_Handler,
		},
		{
			MethodName: "ListReports",
			Handler:    _RapporteService_ListReports_Handler,
		},
		{
			MethodName: "SubmitReport",
			Handler:    _RapporteService_SubmitReport_Handler,
		},
		{
			MethodName: "ApproveReport",
			Handler:    _RapporteService_ApproveReport_Handler,
		},
		{
			MethodName: "RejectReport",
			Handler:    _RapporteService_RejectReport_Handler,
		},
		{
			MethodName: "AddLine",
			Handler:    _RapporteService_AddLine_Handler,
		},
		{
			MethodName: "UpdateLine",
			Handler:    _RapporteService_UpdateLine_Handler,
		},
		{
			MethodName: "DeleteLine",
			Handler:    _RapporteService_DeleteLine_Handler,
		},
		{
			MethodName: "ListLines",
			Handler:    _RapporteService_ListLines_Handler,
		},
		{
			MethodName: "UploadAttachment",
			Handler:    _RapporteService_UploadAttachment_Handler,
		},
		{
			MethodName: "ListAttachments",
			Handler:    _RapporteService_ListAttachments_Handler,
		},
		{
			MethodName: "DeleteAttachment",
			Handler:    _RapporteService_DeleteAttachment_Handler,
		},
		{
			MethodName: "GetReportStats",
			Handler:    _RapporteService_GetReportStats_Handler,
		},
		{
			MethodName: "ListPendingApprovals",
			Handler:    _RapporteService_ListPendingApprovals_Handler,
		},
		{
			MethodName: "ExportPDF",
			Handler:    _RapporteService_ExportPDF_Handler,
		},
		{
			MethodName: "SaveSignature",
			Handler:    _RapporteService_SaveSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rapporte/v1/rapporte.proto",
}
