// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/rapporte/v1/rapporte.proto

package rapportev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // draft|submitted|approved|rejected
	AuthorId      string                 `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ReviewerId    *string                `protobuf:"bytes,7,opt,name=reviewer_id,json=reviewerId,proto3,oneof" json:"reviewer_id,omitempty"`
	ReviewedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=reviewed_at,json=reviewedAt,proto3,oneof" json:"reviewed_at,omitempty"`
	ReviewNote    string                 `protobuf:"bytes,9,opt,name=review_note,json=reviewNote,proto3" json:"review_note,omitempty"`
	Lat           *float64               `protobuf:"fixed64,10,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,11,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	ReportDate    string                 `protobuf:"bytes,12,opt,name=report_date,json=reportDate,proto3" json:"report_date,omitempty"` // YYYY-MM-DD
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkReport) Reset() {
	*x = WorkReport{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkReport) ProtoMessage() {}

func (x *WorkReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkReport.ProtoReflect.Descriptor instead.
func (*WorkReport) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{0}
}

func (x *WorkReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkReport) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WorkReport) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WorkReport) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkReport) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *WorkReport) GetReviewerId() string {
	if x != nil && x.ReviewerId != nil {
		return *x.ReviewerId
	}
	return ""
}

func (x *WorkReport) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

func (x *WorkReport) GetReviewNote() string {
	if x != nil {
		return x.ReviewNote
	}
	return ""
}

func (x *WorkReport) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *WorkReport) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *WorkReport) GetReportDate() string {
	if x != nil {
		return x.ReportDate
	}
	return ""
}

func (x *WorkReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkReport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ReportLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,3,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	Notes         string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportLine) Reset() {
	*x = ReportLine{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportLine) ProtoMessage() {}

func (x *ReportLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportLine.ProtoReflect.Descriptor instead.
func (*ReportLine) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{1}
}

func (x *ReportLine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportLine) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReportLine) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportLine) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ReportLine) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReportLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReportLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ReportLine) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ReportLine) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReportLine) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ReportAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,3,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	LineId        *string                `protobuf:"bytes,4,opt,name=line_id,json=lineId,proto3,oneof" json:"line_id,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,8,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,9,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	UploadedBy    string                 `protobuf:"bytes,10,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAttachment) Reset() {
	*x = ReportAttachment{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAttachment) ProtoMessage() {}

func (x *ReportAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAttachment.ProtoReflect.Descriptor instead.
func (*ReportAttachment) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{2}
}

func (x *ReportAttachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportAttachment) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReportAttachment) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportAttachment) GetLineId() string {
	if x != nil && x.LineId != nil {
		return *x.LineId
	}
	return ""
}

func (x *ReportAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReportAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ReportAttachment) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ReportAttachment) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ReportAttachment) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *ReportAttachment) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *ReportAttachment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Lat           *float64               `protobuf:"fixed64,5,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,6,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	ReportDate    string                 `protobuf:"bytes,7,opt,name=report_date,json=reportDate,proto3" json:"report_date,omitempty"` // YYYY-MM-DD, empty = today
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateReportRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateReportRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateReportRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateReportRequest) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *CreateReportRequest) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *CreateReportRequest) GetReportDate() string {
	if x != nil {
		return x.ReportDate
	}
	return ""
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{4}
}

func (x *GetReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type UpdateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Lat           *float64               `protobuf:"fixed64,5,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,6,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	ReportDate    *string                `protobuf:"bytes,7,opt,name=report_date,json=reportDate,proto3,oneof" json:"report_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReportRequest) Reset() {
	*x = UpdateReportRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReportRequest) ProtoMessage() {}

func (x *UpdateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *UpdateReportRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateReportRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateReportRequest) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *UpdateReportRequest) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *UpdateReportRequest) GetReportDate() string {
	if x != nil && x.ReportDate != nil {
		return *x.ReportDate
	}
	return ""
}

type DeleteReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReportRequest) Reset() {
	*x = DeleteReportRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReportRequest) ProtoMessage() {}

func (x *DeleteReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type DeleteReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReportResponse) Reset() {
	*x = DeleteReportResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReportResponse) ProtoMessage() {}

func (x *DeleteReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReportResponse.ProtoReflect.Descriptor instead.
func (*DeleteReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{7}
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *WorkReport            `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResponse) GetReport() *WorkReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type ListReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	AuthorId      *string                `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3,oneof" json:"author_id,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{9}
}

func (x *ListReportsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListReportsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListReportsRequest) GetAuthorId() string {
	if x != nil && x.AuthorId != nil {
		return *x.AuthorId
	}
	return ""
}

func (x *ListReportsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListReportsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReportsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*WorkReport          `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{10}
}

func (x *ListReportsResponse) GetReports() []*WorkReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ListReportsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SubmitReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReportRequest) Reset() {
	*x = SubmitReportRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReportRequest) ProtoMessage() {}

func (x *SubmitReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReportRequest.ProtoReflect.Descriptor instead.
func (*SubmitReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ApproveReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ReviewerId    string                 `protobuf:"bytes,3,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	ReviewNote    string                 `protobuf:"bytes,4,opt,name=review_note,json=reviewNote,proto3" json:"review_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveReportRequest) Reset() {
	*x = ApproveReportRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveReportRequest) ProtoMessage() {}

func (x *ApproveReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveReportRequest.ProtoReflect.Descriptor instead.
func (*ApproveReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ApproveReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ApproveReportRequest) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *ApproveReportRequest) GetReviewNote() string {
	if x != nil {
		return x.ReviewNote
	}
	return ""
}

type RejectReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ReviewerId    string                 `protobuf:"bytes,3,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	ReviewNote    string                 `protobuf:"bytes,4,opt,name=review_note,json=reviewNote,proto3" json:"review_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectReportRequest) Reset() {
	*x = RejectReportRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectReportRequest) ProtoMessage() {}

func (x *RejectReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectReportRequest.ProtoReflect.Descriptor instead.
func (*RejectReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{13}
}

func (x *RejectReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RejectReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *RejectReportRequest) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *RejectReportRequest) GetReviewNote() string {
	if x != nil {
		return x.ReviewNote
	}
	return ""
}

type AddLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	Position      int32                  `protobuf:"varint,7,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLineRequest) Reset() {
	*x = AddLineRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLineRequest) ProtoMessage() {}

func (x *AddLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLineRequest.ProtoReflect.Descriptor instead.
func (*AddLineRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{14}
}

func (x *AddLineRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AddLineRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *AddLineRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddLineRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddLineRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *AddLineRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *AddLineRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type UpdateLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LineId        string                 `protobuf:"bytes,2,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Quantity      *float64               `protobuf:"fixed64,4,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Unit          *string                `protobuf:"bytes,5,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	Notes         *string                `protobuf:"bytes,6,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	Position      *int32                 `protobuf:"varint,7,opt,name=position,proto3,oneof" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLineRequest) Reset() {
	*x = UpdateLineRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLineRequest) ProtoMessage() {}

func (x *UpdateLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLineRequest.ProtoReflect.Descriptor instead.
func (*UpdateLineRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateLineRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateLineRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *UpdateLineRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateLineRequest) GetQuantity() float64 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *UpdateLineRequest) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *UpdateLineRequest) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *UpdateLineRequest) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

type DeleteLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LineId        string                 `protobuf:"bytes,2,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLineRequest) Reset() {
	*x = DeleteLineRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLineRequest) ProtoMessage() {}

func (x *DeleteLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLineRequest.ProtoReflect.Descriptor instead.
func (*DeleteLineRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteLineRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteLineRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

type DeleteLineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLineResponse) Reset() {
	*x = DeleteLineResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLineResponse) ProtoMessage() {}

func (x *DeleteLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLineResponse.ProtoReflect.Descriptor instead.
func (*DeleteLineResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{17}
}

type LineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          *ReportLine            `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineResponse) Reset() {
	*x = LineResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineResponse) ProtoMessage() {}

func (x *LineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineResponse.ProtoReflect.Descriptor instead.
func (*LineResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{18}
}

func (x *LineResponse) GetLine() *ReportLine {
	if x != nil {
		return x.Line
	}
	return nil
}

type ListLinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinesRequest) Reset() {
	*x = ListLinesRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinesRequest) ProtoMessage() {}

func (x *ListLinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinesRequest.ProtoReflect.Descriptor instead.
func (*ListLinesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{19}
}

func (x *ListLinesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListLinesRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ListLinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*ReportLine          `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinesResponse) Reset() {
	*x = ListLinesResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinesResponse) ProtoMessage() {}

func (x *ListLinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinesResponse.ProtoReflect.Descriptor instead.
func (*ListLinesResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{20}
}

func (x *ListLinesResponse) GetLines() []*ReportLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type UploadAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	LineId        *string                `protobuf:"bytes,3,opt,name=line_id,json=lineId,proto3,oneof" json:"line_id,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,7,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // pre-computed by caller, stored as-is
	UploadedBy    string                 `protobuf:"bytes,8,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentRequest) Reset() {
	*x = UploadAttachmentRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentRequest) ProtoMessage() {}

func (x *UploadAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentRequest.ProtoReflect.Descriptor instead.
func (*UploadAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{21}
}

func (x *UploadAttachmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UploadAttachmentRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *UploadAttachmentRequest) GetLineId() string {
	if x != nil && x.LineId != nil {
		return *x.LineId
	}
	return ""
}

func (x *UploadAttachmentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadAttachmentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadAttachmentRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UploadAttachmentRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *UploadAttachmentRequest) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

type ListAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	LineId        *string                `protobuf:"bytes,3,opt,name=line_id,json=lineId,proto3,oneof" json:"line_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsRequest) Reset() {
	*x = ListAttachmentsRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsRequest) ProtoMessage() {}

func (x *ListAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{22}
}

func (x *ListAttachmentsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAttachmentsRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ListAttachmentsRequest) GetLineId() string {
	if x != nil && x.LineId != nil {
		return *x.LineId
	}
	return ""
}

type ListAttachmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachments   []*ReportAttachment    `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsResponse) Reset() {
	*x = ListAttachmentsResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsResponse) ProtoMessage() {}

func (x *ListAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{23}
}

func (x *ListAttachmentsResponse) GetAttachments() []*ReportAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type AttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachment    *ReportAttachment      `protobuf:"bytes,1,opt,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentResponse) Reset() {
	*x = AttachmentResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentResponse) ProtoMessage() {}

func (x *AttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentResponse.ProtoReflect.Descriptor instead.
func (*AttachmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{24}
}

func (x *AttachmentResponse) GetAttachment() *ReportAttachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type DeleteAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AttachmentId  string                 `protobuf:"bytes,2,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentRequest) Reset() {
	*x = DeleteAttachmentRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentRequest) ProtoMessage() {}

func (x *DeleteAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteAttachmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteAttachmentRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

type DeleteAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentResponse) Reset() {
	*x = DeleteAttachmentResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentResponse) ProtoMessage() {}

func (x *DeleteAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{26}
}

type GetReportStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportStatsRequest) Reset() {
	*x = GetReportStatsRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportStatsRequest) ProtoMessage() {}

func (x *GetReportStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportStatsRequest.ProtoReflect.Descriptor instead.
func (*GetReportStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{27}
}

func (x *GetReportStatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ReportStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalReports   int32                  `protobuf:"varint,1,opt,name=total_reports,json=totalReports,proto3" json:"total_reports,omitempty"`
	DraftCount     int32                  `protobuf:"varint,2,opt,name=draft_count,json=draftCount,proto3" json:"draft_count,omitempty"`
	SubmittedCount int32                  `protobuf:"varint,3,opt,name=submitted_count,json=submittedCount,proto3" json:"submitted_count,omitempty"`
	ApprovedCount  int32                  `protobuf:"varint,4,opt,name=approved_count,json=approvedCount,proto3" json:"approved_count,omitempty"`
	RejectedCount  int32                  `protobuf:"varint,5,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportStatsResponse) Reset() {
	*x = ReportStatsResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatsResponse) ProtoMessage() {}

func (x *ReportStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatsResponse.ProtoReflect.Descriptor instead.
func (*ReportStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{28}
}

func (x *ReportStatsResponse) GetTotalReports() int32 {
	if x != nil {
		return x.TotalReports
	}
	return 0
}

func (x *ReportStatsResponse) GetDraftCount() int32 {
	if x != nil {
		return x.DraftCount
	}
	return 0
}

func (x *ReportStatsResponse) GetSubmittedCount() int32 {
	if x != nil {
		return x.SubmittedCount
	}
	return 0
}

func (x *ReportStatsResponse) GetApprovedCount() int32 {
	if x != nil {
		return x.ApprovedCount
	}
	return 0
}

func (x *ReportStatsResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

type ListPendingApprovalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingApprovalsRequest) Reset() {
	*x = ListPendingApprovalsRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsRequest) ProtoMessage() {}

func (x *ListPendingApprovalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{29}
}

func (x *ListPendingApprovalsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListPendingApprovalsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPendingApprovalsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ExportPDFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPDFRequest) Reset() {
	*x = ExportPDFRequest{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPDFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPDFRequest) ProtoMessage() {}

func (x *ExportPDFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPDFRequest.ProtoReflect.Descriptor instead.
func (*ExportPDFRequest) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{30}
}

func (x *ExportPDFRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExportPDFRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ExportPDFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPDFResponse) Reset() {
	*x = ExportPDFResponse{}
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPDFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPDFResponse) ProtoMessage() {}

func (x *ExportPDFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rapporte_v1_rapporte_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPDFResponse.ProtoReflect.Descriptor instead.
func (*ExportPDFResponse) Descriptor() ([]byte, []int) {
	return file_proto_rapporte_v1_rapporte_proto_rawDescGZIP(), []int{31}
}

func (x *ExportPDFResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExportPDFResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExportPDFResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_proto_rapporte_v1_rapporte_proto protoreflect.FileDescriptor

const file_proto_rapporte_v1_rapporte_proto_rawDesc = "" +
	"\n" +
	" proto/rapporte/v1/rapporte.proto\x12\vrapporte.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x04\n" +
	"\n" +
	"WorkReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\tR\bauthorId\x12$\n" +
	"\vreviewer_id\x18\a \x01(\tH\x00R\n" +
	"reviewerId\x88\x01\x01\x12@\n" +
	"\vreviewed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"reviewedAt\x88\x01\x01\x12\x1f\n" +
	"\vreview_note\x18\t \x01(\tR\n" +
	"reviewNote\x12\x15\n" +
	"\x03lat\x18\n" +
	" \x01(\x01H\x02R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\v \x01(\x01H\x03R\x03lon\x88\x01\x01\x12\x1f\n" +
	"\vreport_date\x18\f \x01(\tR\n" +
	"reportDate\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_reviewer_idB\x0e\n" +
	"\f_reviewed_atB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lon\"\xd0\x02\n" +
	"\n" +
	"ReportLine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x03 \x01(\tR\breportId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x84\x03\n" +
	"\x10ReportAttachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x03 \x01(\tR\breportId\x12\x1c\n" +
	"\aline_id\x18\x04 \x01(\tH\x00R\x06lineId\x88\x01\x01\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"object_key\x18\b \x01(\tR\tobjectKey\x12#\n" +
	"\rpresigned_url\x18\t \x01(\tR\fpresignedUrl\x12\x1f\n" +
	"\vuploaded_by\x18\n" +
	" \x01(\tR\n" +
	"uploadedBy\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\n" +
	"\n" +
	"\b_line_id\"\xe6\x01\n" +
	"\x13CreateReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x15\n" +
	"\x03lat\x18\x05 \x01(\x01H\x00R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\x06 \x01(\x01H\x01R\x03lon\x88\x01\x01\x12\x1f\n" +
	"\vreport_date\x18\a \x01(\tR\n" +
	"reportDateB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lon\"L\n" +
	"\x10GetReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"\x9f\x02\n" +
	"\x13UpdateReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03lat\x18\x05 \x01(\x01H\x02R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\x06 \x01(\x01H\x03R\x03lon\x88\x01\x01\x12$\n" +
	"\vreport_date\x18\a \x01(\tH\x04R\n" +
	"reportDate\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lonB\x0e\n" +
	"\f_report_date\"O\n" +
	"\x13DeleteReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"\x16\n" +
	"\x14DeleteReportResponse\"A\n" +
	"\x0eReportResponse\x12/\n" +
	"\x06report\x18\x01 \x01(\v2\x17.rapporte.v1.WorkReportR\x06report\"\xd2\x01\n" +
	"\x12ListReportsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x00R\x06status\x88\x01\x01\x12 \n" +
	"\tauthor_id\x18\x03 \x01(\tH\x01R\bauthorId\x88\x01\x01\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSizeB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_author_id\"^\n" +
	"\x13ListReportsResponse\x121\n" +
	"\areports\x18\x01 \x03(\v2\x17.rapporte.v1.WorkReportR\areports\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"O\n" +
	"\x13SubmitReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"\x92\x01\n" +
	"\x14ApproveReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12\x1f\n" +
	"\vreviewer_id\x18\x03 \x01(\tR\n" +
	"reviewerId\x12\x1f\n" +
	"\vreview_note\x18\x04 \x01(\tR\n" +
	"reviewNote\"\x91\x01\n" +
	"\x13RejectReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12\x1f\n" +
	"\vreviewer_id\x18\x03 \x01(\tR\n" +
	"reviewerId\x12\x1f\n" +
	"\vreview_note\x18\x04 \x01(\tR\n" +
	"reviewNote\"\xce\x01\n" +
	"\x0eAddLineRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12\x1a\n" +
	"\bposition\x18\a \x01(\x05R\bposition\"\xa3\x02\n" +
	"\x11UpdateLineRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\aline_id\x18\x02 \x01(\tR\x06lineId\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bquantity\x18\x04 \x01(\x01H\x01R\bquantity\x88\x01\x01\x12\x17\n" +
	"\x04unit\x18\x05 \x01(\tH\x02R\x04unit\x88\x01\x01\x12\x19\n" +
	"\x05notes\x18\x06 \x01(\tH\x03R\x05notes\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\a \x01(\x05H\x04R\bposition\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_quantityB\a\n" +
	"\x05_unitB\b\n" +
	"\x06_notesB\v\n" +
	"\t_position\"I\n" +
	"\x11DeleteLineRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\aline_id\x18\x02 \x01(\tR\x06lineId\"\x14\n" +
	"\x12DeleteLineResponse\";\n" +
	"\fLineResponse\x12+\n" +
	"\x04line\x18\x01 \x01(\v2\x17.rapporte.v1.ReportLineR\x04line\"L\n" +
	"\x10ListLinesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"B\n" +
	"\x11ListLinesResponse\x12-\n" +
	"\x05lines\x18\x01 \x03(\v2\x17.rapporte.v1.ReportLineR\x05lines\"\x9b\x02\n" +
	"\x17UploadAttachmentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12\x1c\n" +
	"\aline_id\x18\x03 \x01(\tH\x00R\x06lineId\x88\x01\x01\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"object_key\x18\a \x01(\tR\tobjectKey\x12\x1f\n" +
	"\vuploaded_by\x18\b \x01(\tR\n" +
	"uploadedByB\n" +
	"\n" +
	"\b_line_id\"|\n" +
	"\x16ListAttachmentsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\x12\x1c\n" +
	"\aline_id\x18\x03 \x01(\tH\x00R\x06lineId\x88\x01\x01B\n" +
	"\n" +
	"\b_line_id\"Z\n" +
	"\x17ListAttachmentsResponse\x12?\n" +
	"\vattachments\x18\x01 \x03(\v2\x1d.rapporte.v1.ReportAttachmentR\vattachments\"S\n" +
	"\x12AttachmentResponse\x12=\n" +
	"\n" +
	"attachment\x18\x01 \x01(\v2\x1d.rapporte.v1.ReportAttachmentR\n" +
	"attachment\"[\n" +
	"\x17DeleteAttachmentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rattachment_id\x18\x02 \x01(\tR\fattachmentId\"\x1a\n" +
	"\x18DeleteAttachmentResponse\"4\n" +
	"\x15GetReportStatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xd2\x01\n" +
	"\x13ReportStatsResponse\x12#\n" +
	"\rtotal_reports\x18\x01 \x01(\x05R\ftotalReports\x12\x1f\n" +
	"\vdraft_count\x18\x02 \x01(\x05R\n" +
	"draftCount\x12'\n" +
	"\x0fsubmitted_count\x18\x03 \x01(\x05R\x0esubmittedCount\x12%\n" +
	"\x0eapproved_count\x18\x04 \x01(\x05R\rapprovedCount\x12%\n" +
	"\x0erejected_count\x18\x05 \x01(\x05R\rrejectedCount\"k\n" +
	"\x1bListPendingApprovalsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"L\n" +
	"\x10ExportPDFRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"l\n" +
	"\x11ExportPDFResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename2\xd7\v\n" +
	"\x0fRapporteService\x12M\n" +
	"\fCreateReport\x12 .rapporte.v1.CreateReportRequest\x1a\x1b.rapporte.v1.ReportResponse\x12G\n" +
	"\tGetReport\x12\x1d.rapporte.v1.GetReportRequest\x1a\x1b.rapporte.v1.ReportResponse\x12M\n" +
	"\fUpdateReport\x12 .rapporte.v1.UpdateReportRequest\x1a\x1b.rapporte.v1.ReportResponse\x12S\n" +
	"\fDeleteReport\x12 .rapporte.v1.DeleteReportRequest\x1a!.rapporte.v1.DeleteReportResponse\x12P\n" +
	"\vListReports\x12\x1f.rapporte.v1.ListReportsRequest\x1a .rapporte.v1.ListReportsResponse\x12M\n" +
	"\fSubmitReport\x12 .rapporte.v1.SubmitReportRequest\x1a\x1b.rapporte.v1.ReportResponse\x12O\n" +
	"\rApproveReport\x12!.rapporte.v1.ApproveReportRequest\x1a\x1b.rapporte.v1.ReportResponse\x12M\n" +
	"\fRejectReport\x12 .rapporte.v1.RejectReportRequest\x1a\x1b.rapporte.v1.ReportResponse\x12A\n" +
	"\aAddLine\x12\x1b.rapporte.v1.AddLineRequest\x1a\x19.rapporte.v1.LineResponse\x12G\n" +
	"\n" +
	"UpdateLine\x12\x1e.rapporte.v1.UpdateLineRequest\x1a\x19.rapporte.v1.LineResponse\x12M\n" +
	"\n" +
	"DeleteLine\x12\x1e.rapporte.v1.DeleteLineRequest\x1a\x1f.rapporte.v1.DeleteLineResponse\x12J\n" +
	"\tListLines\x12\x1d.rapporte.v1.ListLinesRequest\x1a\x1e.rapporte.v1.ListLinesResponse\x12Y\n" +
	"\x10UploadAttachment\x12$.rapporte.v1.UploadAttachmentRequest\x1a\x1f.rapporte.v1.AttachmentResponse\x12\\\n" +
	"\x0fListAttachments\x12#.rapporte.v1.ListAttachmentsRequest\x1a$.rapporte.v1.ListAttachmentsResponse\x12_\n" +
	"\x10DeleteAttachment\x12$.rapporte.v1.DeleteAttachmentRequest\x1a%.rapporte.v1.DeleteAttachmentResponse\x12V\n" +
	"\x0eGetReportStats\x12\".rapporte.v1.GetReportStatsRequest\x1a .rapporte.v1.ReportStatsResponse\x12b\n" +
	"\x14ListPendingApprovals\x12(.rapporte.v1.ListPendingApprovalsRequest\x1a .rapporte.v1.ListReportsResponse\x12J\n" +
	"\tExportPDF\x12\x1d.rapporte.v1.ExportPDFRequest\x1a\x1e.rapporte.v1.ExportPDFResponseB7Z5github.com/kmuhub/kmuhub/proto/rapporte/v1;rapportev1b\x06proto3"

var (
	file_proto_rapporte_v1_rapporte_proto_rawDescOnce sync.Once
	file_proto_rapporte_v1_rapporte_proto_rawDescData []byte
)

func file_proto_rapporte_v1_rapporte_proto_rawDescGZIP() []byte {
	file_proto_rapporte_v1_rapporte_proto_rawDescOnce.Do(func() {
		file_proto_rapporte_v1_rapporte_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rapporte_v1_rapporte_proto_rawDesc), len(file_proto_rapporte_v1_rapporte_proto_rawDesc)))
	})
	return file_proto_rapporte_v1_rapporte_proto_rawDescData
}

var file_proto_rapporte_v1_rapporte_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_rapporte_v1_rapporte_proto_goTypes = []any{
	(*WorkReport)(nil),                  // 0: rapporte.v1.WorkReport
	(*ReportLine)(nil),                  // 1: rapporte.v1.ReportLine
	(*ReportAttachment)(nil),            // 2: rapporte.v1.ReportAttachment
	(*CreateReportRequest)(nil),         // 3: rapporte.v1.CreateReportRequest
	(*GetReportRequest)(nil),            // 4: rapporte.v1.GetReportRequest
	(*UpdateReportRequest)(nil),         // 5: rapporte.v1.UpdateReportRequest
	(*DeleteReportRequest)(nil),         // 6: rapporte.v1.DeleteReportRequest
	(*DeleteReportResponse)(nil),        // 7: rapporte.v1.DeleteReportResponse
	(*ReportResponse)(nil),              // 8: rapporte.v1.ReportResponse
	(*ListReportsRequest)(nil),          // 9: rapporte.v1.ListReportsRequest
	(*ListReportsResponse)(nil),         // 10: rapporte.v1.ListReportsResponse
	(*SubmitReportRequest)(nil),         // 11: rapporte.v1.SubmitReportRequest
	(*ApproveReportRequest)(nil),        // 12: rapporte.v1.ApproveReportRequest
	(*RejectReportRequest)(nil),         // 13: rapporte.v1.RejectReportRequest
	(*AddLineRequest)(nil),              // 14: rapporte.v1.AddLineRequest
	(*UpdateLineRequest)(nil),           // 15: rapporte.v1.UpdateLineRequest
	(*DeleteLineRequest)(nil),           // 16: rapporte.v1.DeleteLineRequest
	(*DeleteLineResponse)(nil),          // 17: rapporte.v1.DeleteLineResponse
	(*LineResponse)(nil),                // 18: rapporte.v1.LineResponse
	(*ListLinesRequest)(nil),            // 19: rapporte.v1.ListLinesRequest
	(*ListLinesResponse)(nil),           // 20: rapporte.v1.ListLinesResponse
	(*UploadAttachmentRequest)(nil),     // 21: rapporte.v1.UploadAttachmentRequest
	(*ListAttachmentsRequest)(nil),      // 22: rapporte.v1.ListAttachmentsRequest
	(*ListAttachmentsResponse)(nil),     // 23: rapporte.v1.ListAttachmentsResponse
	(*AttachmentResponse)(nil),          // 24: rapporte.v1.AttachmentResponse
	(*DeleteAttachmentRequest)(nil),     // 25: rapporte.v1.DeleteAttachmentRequest
	(*DeleteAttachmentResponse)(nil),    // 26: rapporte.v1.DeleteAttachmentResponse
	(*GetReportStatsRequest)(nil),       // 27: rapporte.v1.GetReportStatsRequest
	(*ReportStatsResponse)(nil),         // 28: rapporte.v1.ReportStatsResponse
	(*ListPendingApprovalsRequest)(nil), // 29: rapporte.v1.ListPendingApprovalsRequest
	(*ExportPDFRequest)(nil),            // 30: rapporte.v1.ExportPDFRequest
	(*ExportPDFResponse)(nil),           // 31: rapporte.v1.ExportPDFResponse
	(*timestamppb.Timestamp)(nil),       // 32: google.protobuf.Timestamp
}
var file_proto_rapporte_v1_rapporte_proto_depIdxs = []int32{
	32, // 0: rapporte.v1.WorkReport.reviewed_at:type_name -> google.protobuf.Timestamp
	32, // 1: rapporte.v1.WorkReport.created_at:type_name -> google.protobuf.Timestamp
	32, // 2: rapporte.v1.WorkReport.updated_at:type_name -> google.protobuf.Timestamp
	32, // 3: rapporte.v1.ReportLine.created_at:type_name -> google.protobuf.Timestamp
	32, // 4: rapporte.v1.ReportLine.updated_at:type_name -> google.protobuf.Timestamp
	32, // 5: rapporte.v1.ReportAttachment.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: rapporte.v1.ReportResponse.report:type_name -> rapporte.v1.WorkReport
	0,  // 7: rapporte.v1.ListReportsResponse.reports:type_name -> rapporte.v1.WorkReport
	1,  // 8: rapporte.v1.LineResponse.line:type_name -> rapporte.v1.ReportLine
	1,  // 9: rapporte.v1.ListLinesResponse.lines:type_name -> rapporte.v1.ReportLine
	2,  // 10: rapporte.v1.ListAttachmentsResponse.attachments:type_name -> rapporte.v1.ReportAttachment
	2,  // 11: rapporte.v1.AttachmentResponse.attachment:type_name -> rapporte.v1.ReportAttachment
	3,  // 12: rapporte.v1.RapporteService.CreateReport:input_type -> rapporte.v1.CreateReportRequest
	4,  // 13: rapporte.v1.RapporteService.GetReport:input_type -> rapporte.v1.GetReportRequest
	5,  // 14: rapporte.v1.RapporteService.UpdateReport:input_type -> rapporte.v1.UpdateReportRequest
	6,  // 15: rapporte.v1.RapporteService.DeleteReport:input_type -> rapporte.v1.DeleteReportRequest
	9,  // 16: rapporte.v1.RapporteService.ListReports:input_type -> rapporte.v1.ListReportsRequest
	11, // 17: rapporte.v1.RapporteService.SubmitReport:input_type -> rapporte.v1.SubmitReportRequest
	12, // 18: rapporte.v1.RapporteService.ApproveReport:input_type -> rapporte.v1.ApproveReportRequest
	13, // 19: rapporte.v1.RapporteService.RejectReport:input_type -> rapporte.v1.RejectReportRequest
	14, // 20: rapporte.v1.RapporteService.AddLine:input_type -> rapporte.v1.AddLineRequest
	15, // 21: rapporte.v1.RapporteService.UpdateLine:input_type -> rapporte.v1.UpdateLineRequest
	16, // 22: rapporte.v1.RapporteService.DeleteLine:input_type -> rapporte.v1.DeleteLineRequest
	19, // 23: rapporte.v1.RapporteService.ListLines:input_type -> rapporte.v1.ListLinesRequest
	21, // 24: rapporte.v1.RapporteService.UploadAttachment:input_type -> rapporte.v1.UploadAttachmentRequest
	22, // 25: rapporte.v1.RapporteService.ListAttachments:input_type -> rapporte.v1.ListAttachmentsRequest
	25, // 26: rapporte.v1.RapporteService.DeleteAttachment:input_type -> rapporte.v1.DeleteAttachmentRequest
	27, // 27: rapporte.v1.RapporteService.GetReportStats:input_type -> rapporte.v1.GetReportStatsRequest
	29, // 28: rapporte.v1.RapporteService.ListPendingApprovals:input_type -> rapporte.v1.ListPendingApprovalsRequest
	30, // 29: rapporte.v1.RapporteService.ExportPDF:input_type -> rapporte.v1.ExportPDFRequest
	8,  // 30: rapporte.v1.RapporteService.CreateReport:output_type -> rapporte.v1.ReportResponse
	8,  // 31: rapporte.v1.RapporteService.GetReport:output_type -> rapporte.v1.ReportResponse
	8,  // 32: rapporte.v1.RapporteService.UpdateReport:output_type -> rapporte.v1.ReportResponse
	7,  // 33: rapporte.v1.RapporteService.DeleteReport:output_type -> rapporte.v1.DeleteReportResponse
	10, // 34: rapporte.v1.RapporteService.ListReports:output_type -> rapporte.v1.ListReportsResponse
	8,  // 35: rapporte.v1.RapporteService.SubmitReport:output_type -> rapporte.v1.ReportResponse
	8,  // 36: rapporte.v1.RapporteService.ApproveReport:output_type -> rapporte.v1.ReportResponse
	8,  // 37: rapporte.v1.RapporteService.RejectReport:output_type -> rapporte.v1.ReportResponse
	18, // 38: rapporte.v1.RapporteService.AddLine:output_type -> rapporte.v1.LineResponse
	18, // 39: rapporte.v1.RapporteService.UpdateLine:output_type -> rapporte.v1.LineResponse
	17, // 40: rapporte.v1.RapporteService.DeleteLine:output_type -> rapporte.v1.DeleteLineResponse
	20, // 41: rapporte.v1.RapporteService.ListLines:output_type -> rapporte.v1.ListLinesResponse
	24, // 42: rapporte.v1.RapporteService.UploadAttachment:output_type -> rapporte.v1.AttachmentResponse
	23, // 43: rapporte.v1.RapporteService.ListAttachments:output_type -> rapporte.v1.ListAttachmentsResponse
	26, // 44: rapporte.v1.RapporteService.DeleteAttachment:output_type -> rapporte.v1.DeleteAttachmentResponse
	28, // 45: rapporte.v1.RapporteService.GetReportStats:output_type -> rapporte.v1.ReportStatsResponse
	10, // 46: rapporte.v1.RapporteService.ListPendingApprovals:output_type -> rapporte.v1.ListReportsResponse
	31, // 47: rapporte.v1.RapporteService.ExportPDF:output_type -> rapporte.v1.ExportPDFResponse
	30, // [30:48] is the sub-list for method output_type
	12, // [12:30] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_rapporte_v1_rapporte_proto_init() }
func file_proto_rapporte_v1_rapporte_proto_init() {
	if File_proto_rapporte_v1_rapporte_proto != nil {
		return
	}
	file_proto_rapporte_v1_rapporte_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_rapporte_v1_rapporte_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_rapporte_v1_rapporte_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_rapporte_v1_rapporte_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_rapporte_v1_rapporte_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_rapporte_v1_rapporte_proto_msgTypes[15].OneofWrappers = []any{}
	file_proto_rapporte_v1_rapporte_proto_msgTypes[21].OneofWrappers = []any{}
	file_proto_rapporte_v1_rapporte_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rapporte_v1_rapporte_proto_rawDesc), len(file_proto_rapporte_v1_rapporte_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rapporte_v1_rapporte_proto_goTypes,
		DependencyIndexes: file_proto_rapporte_v1_rapporte_proto_depIdxs,
		MessageInfos:      file_proto_rapporte_v1_rapporte_proto_msgTypes,
	}.Build()
	File_proto_rapporte_v1_rapporte_proto = out.File
	file_proto_rapporte_v1_rapporte_proto_goTypes = nil
	file_proto_rapporte_v1_rapporte_proto_depIdxs = nil
}
