// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/biz/v1/datev_upload.proto

package bizv1

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// ============================================================================
// OAuth Messages
// ============================================================================

type GetDatevAuthURLRequest struct {
	TenantId    string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RedirectUrl string `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
}

func (x *GetDatevAuthURLRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDatevAuthURLRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type GetDatevAuthURLResponse struct {
	AuthorizationUrl string `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
}

func (x *GetDatevAuthURLResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

type HandleDatevOAuthCallbackRequest struct {
	TenantId    string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUrl string `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
}

func (x *HandleDatevOAuthCallbackRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HandleDatevOAuthCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *HandleDatevOAuthCallbackRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type HandleDatevOAuthCallbackResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *HandleDatevOAuthCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleDatevOAuthCallbackResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DisconnectDatevRequest struct {
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *DisconnectDatevRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DisconnectDatevResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DisconnectDatevResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetDatevConnectionStatusRequest struct {
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *GetDatevConnectionStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetDatevConnectionStatusResponse struct {
	Connected bool `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
}

func (x *GetDatevConnectionStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

// ============================================================================
// Upload Messages
// ============================================================================

type UploadDatevBuchungsstapelRequest struct {
	TenantId        string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	StartDate       string `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate         string `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	FiscalYearStart string `protobuf:"bytes,4,opt,name=fiscal_year_start,json=fiscalYearStart,proto3" json:"fiscal_year_start,omitempty"`
}

func (x *UploadDatevBuchungsstapelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UploadDatevBuchungsstapelRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UploadDatevBuchungsstapelRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *UploadDatevBuchungsstapelRequest) GetFiscalYearStart() string {
	if x != nil {
		return x.FiscalYearStart
	}
	return ""
}

type UploadDatevBuchungsstapelResponse struct {
	Success       bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DocumentCount int32  `protobuf:"varint,2,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	FileSize      int32  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *UploadDatevBuchungsstapelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadDatevBuchungsstapelResponse) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *UploadDatevBuchungsstapelResponse) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadDatevBuchungsstapelResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UploadDatevBelegRequest struct {
	TenantId  string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	InvoiceId string `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
}

func (x *UploadDatevBelegRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UploadDatevBelegRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type UploadDatevBelegResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *UploadDatevBelegResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadDatevBelegResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ============================================================================
// Config Messages
// ============================================================================

type GetDatevUploadConfigRequest struct {
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *GetDatevUploadConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetDatevUploadConfigResponse struct {
	ClientNumber      string `protobuf:"bytes,1,opt,name=client_number,json=clientNumber,proto3" json:"client_number,omitempty"`
	AutoUploadEnabled bool   `protobuf:"varint,2,opt,name=auto_upload_enabled,json=autoUploadEnabled,proto3" json:"auto_upload_enabled,omitempty"`
	UploadAfterExport bool   `protobuf:"varint,3,opt,name=upload_after_export,json=uploadAfterExport,proto3" json:"upload_after_export,omitempty"`
}

func (x *GetDatevUploadConfigResponse) GetClientNumber() string {
	if x != nil {
		return x.ClientNumber
	}
	return ""
}

func (x *GetDatevUploadConfigResponse) GetAutoUploadEnabled() bool {
	if x != nil {
		return x.AutoUploadEnabled
	}
	return false
}

func (x *GetDatevUploadConfigResponse) GetUploadAfterExport() bool {
	if x != nil {
		return x.UploadAfterExport
	}
	return false
}

type UpdateDatevUploadConfigRequest struct {
	TenantId          string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientNumber      string `protobuf:"bytes,2,opt,name=client_number,json=clientNumber,proto3" json:"client_number,omitempty"`
	AutoUploadEnabled bool   `protobuf:"varint,3,opt,name=auto_upload_enabled,json=autoUploadEnabled,proto3" json:"auto_upload_enabled,omitempty"`
	UploadAfterExport bool   `protobuf:"varint,4,opt,name=upload_after_export,json=uploadAfterExport,proto3" json:"upload_after_export,omitempty"`
}

func (x *UpdateDatevUploadConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateDatevUploadConfigRequest) GetClientNumber() string {
	if x != nil {
		return x.ClientNumber
	}
	return ""
}

func (x *UpdateDatevUploadConfigRequest) GetAutoUploadEnabled() bool {
	if x != nil {
		return x.AutoUploadEnabled
	}
	return false
}

func (x *UpdateDatevUploadConfigRequest) GetUploadAfterExport() bool {
	if x != nil {
		return x.UploadAfterExport
	}
	return false
}

type UpdateDatevUploadConfigResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateDatevUploadConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ============================================================================
// Log Messages
// ============================================================================

type ListDatevUploadLogsRequest struct {
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Limit    int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListDatevUploadLogsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDatevUploadLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDatevUploadLogsResponse struct {
	Entries []*DatevUploadLogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *ListDatevUploadLogsResponse) GetEntries() []*DatevUploadLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DatevUploadLogEntry struct {
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UploadType    string                 `protobuf:"bytes,2,opt,name=upload_type,json=uploadType,proto3" json:"upload_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	FileSize      int32                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	DocumentCount int32                  `protobuf:"varint,5,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
}

func (x *DatevUploadLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatevUploadLogEntry) GetUploadType() string {
	if x != nil {
		return x.UploadType
	}
	return ""
}

func (x *DatevUploadLogEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DatevUploadLogEntry) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *DatevUploadLogEntry) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *DatevUploadLogEntry) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DatevUploadLogEntry) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *DatevUploadLogEntry) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}
