// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/biz/v1/datev_upload.proto

package bizv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion9

const (
	DatevUploadService_GetDatevAuthURL_FullMethodName            = "/biz.v1.DatevUploadService/GetDatevAuthURL"
	DatevUploadService_HandleDatevOAuthCallback_FullMethodName   = "/biz.v1.DatevUploadService/HandleDatevOAuthCallback"
	DatevUploadService_DisconnectDatev_FullMethodName            = "/biz.v1.DatevUploadService/DisconnectDatev"
	DatevUploadService_GetDatevConnectionStatus_FullMethodName   = "/biz.v1.DatevUploadService/GetDatevConnectionStatus"
	DatevUploadService_UploadDatevBuchungsstapel_FullMethodName  = "/biz.v1.DatevUploadService/UploadDatevBuchungsstapel"
	DatevUploadService_UploadDatevBeleg_FullMethodName           = "/biz.v1.DatevUploadService/UploadDatevBeleg"
	DatevUploadService_GetDatevUploadConfig_FullMethodName       = "/biz.v1.DatevUploadService/GetDatevUploadConfig"
	DatevUploadService_UpdateDatevUploadConfig_FullMethodName    = "/biz.v1.DatevUploadService/UpdateDatevUploadConfig"
	DatevUploadService_ListDatevUploadLogs_FullMethodName        = "/biz.v1.DatevUploadService/ListDatevUploadLogs"
)

// DatevUploadServiceClient is the client API for DatevUploadService.
type DatevUploadServiceClient interface {
	// OAuth
	GetDatevAuthURL(ctx context.Context, in *GetDatevAuthURLRequest, opts ...grpc.CallOption) (*GetDatevAuthURLResponse, error)
	HandleDatevOAuthCallback(ctx context.Context, in *HandleDatevOAuthCallbackRequest, opts ...grpc.CallOption) (*HandleDatevOAuthCallbackResponse, error)
	DisconnectDatev(ctx context.Context, in *DisconnectDatevRequest, opts ...grpc.CallOption) (*DisconnectDatevResponse, error)
	GetDatevConnectionStatus(ctx context.Context, in *GetDatevConnectionStatusRequest, opts ...grpc.CallOption) (*GetDatevConnectionStatusResponse, error)
	// Upload Operations
	UploadDatevBuchungsstapel(ctx context.Context, in *UploadDatevBuchungsstapelRequest, opts ...grpc.CallOption) (*UploadDatevBuchungsstapelResponse, error)
	UploadDatevBeleg(ctx context.Context, in *UploadDatevBelegRequest, opts ...grpc.CallOption) (*UploadDatevBelegResponse, error)
	// Config
	GetDatevUploadConfig(ctx context.Context, in *GetDatevUploadConfigRequest, opts ...grpc.CallOption) (*GetDatevUploadConfigResponse, error)
	UpdateDatevUploadConfig(ctx context.Context, in *UpdateDatevUploadConfigRequest, opts ...grpc.CallOption) (*UpdateDatevUploadConfigResponse, error)
	// Logs
	ListDatevUploadLogs(ctx context.Context, in *ListDatevUploadLogsRequest, opts ...grpc.CallOption) (*ListDatevUploadLogsResponse, error)
}

type datevUploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatevUploadServiceClient(cc grpc.ClientConnInterface) DatevUploadServiceClient {
	return &datevUploadServiceClient{cc}
}

func (c *datevUploadServiceClient) GetDatevAuthURL(ctx context.Context, in *GetDatevAuthURLRequest, opts ...grpc.CallOption) (*GetDatevAuthURLResponse, error) {
	out := new(GetDatevAuthURLResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_GetDatevAuthURL_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datevUploadServiceClient) HandleDatevOAuthCallback(ctx context.Context, in *HandleDatevOAuthCallbackRequest, opts ...grpc.CallOption) (*HandleDatevOAuthCallbackResponse, error) {
	out := new(HandleDatevOAuthCallbackResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_HandleDatevOAuthCallback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datevUploadServiceClient) DisconnectDatev(ctx context.Context, in *DisconnectDatevRequest, opts ...grpc.CallOption) (*DisconnectDatevResponse, error) {
	out := new(DisconnectDatevResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_DisconnectDatev_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datevUploadServiceClient) GetDatevConnectionStatus(ctx context.Context, in *GetDatevConnectionStatusRequest, opts ...grpc.CallOption) (*GetDatevConnectionStatusResponse, error) {
	out := new(GetDatevConnectionStatusResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_GetDatevConnectionStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datevUploadServiceClient) UploadDatevBuchungsstapel(ctx context.Context, in *UploadDatevBuchungsstapelRequest, opts ...grpc.CallOption) (*UploadDatevBuchungsstapelResponse, error) {
	out := new(UploadDatevBuchungsstapelResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_UploadDatevBuchungsstapel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datevUploadServiceClient) UploadDatevBeleg(ctx context.Context, in *UploadDatevBelegRequest, opts ...grpc.CallOption) (*UploadDatevBelegResponse, error) {
	out := new(UploadDatevBelegResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_UploadDatevBeleg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datevUploadServiceClient) GetDatevUploadConfig(ctx context.Context, in *GetDatevUploadConfigRequest, opts ...grpc.CallOption) (*GetDatevUploadConfigResponse, error) {
	out := new(GetDatevUploadConfigResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_GetDatevUploadConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datevUploadServiceClient) UpdateDatevUploadConfig(ctx context.Context, in *UpdateDatevUploadConfigRequest, opts ...grpc.CallOption) (*UpdateDatevUploadConfigResponse, error) {
	out := new(UpdateDatevUploadConfigResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_UpdateDatevUploadConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datevUploadServiceClient) ListDatevUploadLogs(ctx context.Context, in *ListDatevUploadLogsRequest, opts ...grpc.CallOption) (*ListDatevUploadLogsResponse, error) {
	out := new(ListDatevUploadLogsResponse)
	err := c.cc.Invoke(ctx, DatevUploadService_ListDatevUploadLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatevUploadServiceServer is the server API for DatevUploadService.
type DatevUploadServiceServer interface {
	GetDatevAuthURL(context.Context, *GetDatevAuthURLRequest) (*GetDatevAuthURLResponse, error)
	HandleDatevOAuthCallback(context.Context, *HandleDatevOAuthCallbackRequest) (*HandleDatevOAuthCallbackResponse, error)
	DisconnectDatev(context.Context, *DisconnectDatevRequest) (*DisconnectDatevResponse, error)
	GetDatevConnectionStatus(context.Context, *GetDatevConnectionStatusRequest) (*GetDatevConnectionStatusResponse, error)
	UploadDatevBuchungsstapel(context.Context, *UploadDatevBuchungsstapelRequest) (*UploadDatevBuchungsstapelResponse, error)
	UploadDatevBeleg(context.Context, *UploadDatevBelegRequest) (*UploadDatevBelegResponse, error)
	GetDatevUploadConfig(context.Context, *GetDatevUploadConfigRequest) (*GetDatevUploadConfigResponse, error)
	UpdateDatevUploadConfig(context.Context, *UpdateDatevUploadConfigRequest) (*UpdateDatevUploadConfigResponse, error)
	ListDatevUploadLogs(context.Context, *ListDatevUploadLogsRequest) (*ListDatevUploadLogsResponse, error)
	mustEmbedUnimplementedDatevUploadServiceServer()
}

// UnimplementedDatevUploadServiceServer should be embedded to have
// forward compatible implementations.
type UnimplementedDatevUploadServiceServer struct{}

func (UnimplementedDatevUploadServiceServer) GetDatevAuthURL(context.Context, *GetDatevAuthURLRequest) (*GetDatevAuthURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatevAuthURL not implemented")
}
func (UnimplementedDatevUploadServiceServer) HandleDatevOAuthCallback(context.Context, *HandleDatevOAuthCallbackRequest) (*HandleDatevOAuthCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleDatevOAuthCallback not implemented")
}
func (UnimplementedDatevUploadServiceServer) DisconnectDatev(context.Context, *DisconnectDatevRequest) (*DisconnectDatevResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectDatev not implemented")
}
func (UnimplementedDatevUploadServiceServer) GetDatevConnectionStatus(context.Context, *GetDatevConnectionStatusRequest) (*GetDatevConnectionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatevConnectionStatus not implemented")
}
func (UnimplementedDatevUploadServiceServer) UploadDatevBuchungsstapel(context.Context, *UploadDatevBuchungsstapelRequest) (*UploadDatevBuchungsstapelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDatevBuchungsstapel not implemented")
}
func (UnimplementedDatevUploadServiceServer) UploadDatevBeleg(context.Context, *UploadDatevBelegRequest) (*UploadDatevBelegResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDatevBeleg not implemented")
}
func (UnimplementedDatevUploadServiceServer) GetDatevUploadConfig(context.Context, *GetDatevUploadConfigRequest) (*GetDatevUploadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatevUploadConfig not implemented")
}
func (UnimplementedDatevUploadServiceServer) UpdateDatevUploadConfig(context.Context, *UpdateDatevUploadConfigRequest) (*UpdateDatevUploadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDatevUploadConfig not implemented")
}
func (UnimplementedDatevUploadServiceServer) ListDatevUploadLogs(context.Context, *ListDatevUploadLogsRequest) (*ListDatevUploadLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDatevUploadLogs not implemented")
}
func (UnimplementedDatevUploadServiceServer) mustEmbedUnimplementedDatevUploadServiceServer() {
}

// UnsafeDatevUploadServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeDatevUploadServiceServer interface {
	mustEmbedUnimplementedDatevUploadServiceServer()
}

func RegisterDatevUploadServiceServer(s grpc.ServiceRegistrar, srv DatevUploadServiceServer) {
	s.RegisterService(&DatevUploadService_ServiceDesc, srv)
}

func _DatevUploadService_GetDatevAuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatevAuthURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).GetDatevAuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_GetDatevAuthURL_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).GetDatevAuthURL(ctx, req.(*GetDatevAuthURLRequest))
	})
}

func _DatevUploadService_HandleDatevOAuthCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleDatevOAuthCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).HandleDatevOAuthCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_HandleDatevOAuthCallback_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).HandleDatevOAuthCallback(ctx, req.(*HandleDatevOAuthCallbackRequest))
	})
}

func _DatevUploadService_DisconnectDatev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectDatevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).DisconnectDatev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_DisconnectDatev_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).DisconnectDatev(ctx, req.(*DisconnectDatevRequest))
	})
}

func _DatevUploadService_GetDatevConnectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatevConnectionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).GetDatevConnectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_GetDatevConnectionStatus_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).GetDatevConnectionStatus(ctx, req.(*GetDatevConnectionStatusRequest))
	})
}

func _DatevUploadService_UploadDatevBuchungsstapel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDatevBuchungsstapelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).UploadDatevBuchungsstapel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_UploadDatevBuchungsstapel_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).UploadDatevBuchungsstapel(ctx, req.(*UploadDatevBuchungsstapelRequest))
	})
}

func _DatevUploadService_UploadDatevBeleg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDatevBelegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).UploadDatevBeleg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_UploadDatevBeleg_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).UploadDatevBeleg(ctx, req.(*UploadDatevBelegRequest))
	})
}

func _DatevUploadService_GetDatevUploadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatevUploadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).GetDatevUploadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_GetDatevUploadConfig_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).GetDatevUploadConfig(ctx, req.(*GetDatevUploadConfigRequest))
	})
}

func _DatevUploadService_UpdateDatevUploadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatevUploadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).UpdateDatevUploadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_UpdateDatevUploadConfig_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).UpdateDatevUploadConfig(ctx, req.(*UpdateDatevUploadConfigRequest))
	})
}

func _DatevUploadService_ListDatevUploadLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatevUploadLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatevUploadServiceServer).ListDatevUploadLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DatevUploadService_ListDatevUploadLogs_FullMethodName}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatevUploadServiceServer).ListDatevUploadLogs(ctx, req.(*ListDatevUploadLogsRequest))
	})
}

// DatevUploadService_ServiceDesc is the grpc.ServiceDesc for DatevUploadService service.
var DatevUploadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "biz.v1.DatevUploadService",
	HandlerType: (*DatevUploadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetDatevAuthURL", Handler: _DatevUploadService_GetDatevAuthURL_Handler},
		{MethodName: "HandleDatevOAuthCallback", Handler: _DatevUploadService_HandleDatevOAuthCallback_Handler},
		{MethodName: "DisconnectDatev", Handler: _DatevUploadService_DisconnectDatev_Handler},
		{MethodName: "GetDatevConnectionStatus", Handler: _DatevUploadService_GetDatevConnectionStatus_Handler},
		{MethodName: "UploadDatevBuchungsstapel", Handler: _DatevUploadService_UploadDatevBuchungsstapel_Handler},
		{MethodName: "UploadDatevBeleg", Handler: _DatevUploadService_UploadDatevBeleg_Handler},
		{MethodName: "GetDatevUploadConfig", Handler: _DatevUploadService_GetDatevUploadConfig_Handler},
		{MethodName: "UpdateDatevUploadConfig", Handler: _DatevUploadService_UpdateDatevUploadConfig_Handler},
		{MethodName: "ListDatevUploadLogs", Handler: _DatevUploadService_ListDatevUploadLogs_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/biz/v1/datev_upload.proto",
}
