-- RBAC Phase 1a (loop unit p1a-migration): give roles a tenant owner, a preset
-- lineage and a colour, give every grant a scope, and seed the seven preset
-- roles with the full fine-grained capability catalogue from the frontend SSOT.
--
-- The coarse legacy permissions (contacts:read etc.) and the existing
-- RequirePermission gates are untouched — the fine keys coexist beside them,
-- so no running deployment loses access through this migration.
--
-- RLS design, the part that is easy to get wrong:
-- `roles` must NOT go through enable_tenant_rls(). That procedure writes
-- `tenant_id = current_tenant_id() OR is_system_context()`, which hides every
-- row with tenant_id IS NULL — and all seven presets are exactly those rows.
-- The result would be an empty capability set for everyone including admin,
-- indistinguishable from "no permissions granted".
-- Read and write policy are split instead of using one USING clause: DELETE
-- only ever consults USING, so a single permissive policy that lets a tenant
-- read the presets would also let it delete them.
--   read  : own tenant + system presets
--   write : own tenant only (presets are seed data, immutable for the app role)

SET LOCAL row_security = off;

BEGIN;

-- 1) roles: tenant ownership (NULL = system preset), preset lineage, UI colour.
ALTER TABLE roles
    ADD COLUMN tenant_id UUID NULL REFERENCES tenants(id) ON DELETE CASCADE,
    ADD COLUMN based_on  UUID NULL REFERENCES roles(id)   ON DELETE SET NULL,
    ADD COLUMN color     VARCHAR(40) NOT NULL DEFAULT '';

-- 2) Role names are unique per tenant, not globally: two tenants may both name
--    a custom role "Buchhaltung". COALESCE maps the presets onto a fixed
--    sentinel so they keep colliding with each other.
--    This expression must stay byte-identical to the ON CONFLICT clause of the
--    generated seed below, otherwise Postgres finds no arbiter index.
DROP INDEX idx_roles_name;
CREATE UNIQUE INDEX idx_roles_tenant_name
    ON roles (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), name);

-- 3) role_permissions: the data scope a grant is valid for. Default 'all' so
--    every pre-existing grant keeps exactly today's behaviour.
ALTER TABLE role_permissions
    ADD COLUMN scope VARCHAR(8) NOT NULL DEFAULT 'all'
        CONSTRAINT role_permissions_scope_check CHECK (scope IN ('own', 'team', 'all'));

-- 4) RLS on roles.
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_read ON roles
    FOR SELECT
    USING (tenant_id IS NULL OR tenant_id = current_tenant_id() OR is_system_context());

CREATE POLICY tenant_isolation_write ON roles
    FOR ALL
    USING (tenant_id = current_tenant_id() OR is_system_context())
    WITH CHECK (tenant_id = current_tenant_id() OR is_system_context());

-- 5) RLS on role_permissions, derived through the owning role. Same asymmetry:
--    the presets' grants are readable by every tenant, writable by none.
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_read ON role_permissions
    FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM roles r
        WHERE r.id = role_permissions.role_id
          AND (r.tenant_id IS NULL OR r.tenant_id = current_tenant_id() OR is_system_context())
    ));

CREATE POLICY tenant_isolation_write ON role_permissions
    FOR ALL
    USING (EXISTS (
        SELECT 1 FROM roles r
        WHERE r.id = role_permissions.role_id
          AND (r.tenant_id = current_tenant_id() OR is_system_context())
    ))
    WITH CHECK (EXISTS (
        SELECT 1 FROM roles r
        WHERE r.id = role_permissions.role_id
          AND (r.tenant_id = current_tenant_id() OR is_system_context())
    ));

-- 6) Seed. Everything below this line is the verbatim output of
--    `cd desktop && npx tsx --tsconfig tsconfig.web.json scripts/gen-rbac-seed.mjs`
--    — regenerate it there, do not hand-edit it here.

-- ============================================================
-- Generated by desktop/scripts/gen-rbac-seed.mjs — do not hand-edit.
-- Source of truth: mocks/data/rbac.ts (ROLE_DEFS) + config/capability-catalog.ts.
-- ============================================================

-- (a) permissions
-- 282 keys: level-1 module:view visibility for every module +
-- every fine capability key from capability-catalog.ts.
INSERT INTO permissions (name, resource, action) VALUES
    ('admin:ai:manage', 'admin:ai', 'manage'),
    ('admin:branding:manage', 'admin:branding', 'manage'),
    ('admin:company:manage', 'admin:company', 'manage'),
    ('admin:customization:manage', 'admin:customization', 'manage'),
    ('admin:impersonate:run', 'admin:impersonate', 'run'),
    ('admin:integrations:manage', 'admin:integrations', 'manage'),
    ('admin:it:manage', 'admin:it', 'manage'),
    ('admin:license:manage', 'admin:license', 'manage'),
    ('admin:module:view', 'admin:module', 'view'),
    ('admin:modules:manage', 'admin:modules', 'manage'),
    ('admin:role:assign', 'admin:role', 'assign'),
    ('admin:role:create', 'admin:role', 'create'),
    ('admin:role:delete', 'admin:role', 'delete'),
    ('admin:role:edit', 'admin:role', 'edit'),
    ('admin:role:read', 'admin:role', 'read'),
    ('admin:user:deactivate', 'admin:user', 'deactivate'),
    ('admin:user:invite', 'admin:user', 'invite'),
    ('admin:user:read', 'admin:user', 'read'),
    ('admin:user_override:manage', 'admin:user_override', 'manage'),
    ('automatisierung:automations:create', 'automatisierung:automations', 'create'),
    ('automatisierung:automations:delete', 'automatisierung:automations', 'delete'),
    ('automatisierung:automations:edit', 'automatisierung:automations', 'edit'),
    ('automatisierung:automations:read', 'automatisierung:automations', 'read'),
    ('automatisierung:automations:toggle', 'automatisierung:automations', 'toggle'),
    ('automatisierung:executions:read', 'automatisierung:executions', 'read'),
    ('automatisierung:module:view', 'automatisierung:module', 'view'),
    ('berichte:datev:read', 'berichte:datev', 'read'),
    ('berichte:export:run', 'berichte:export', 'run'),
    ('berichte:module:view', 'berichte:module', 'view'),
    ('berichte:reports:create', 'berichte:reports', 'create'),
    ('berichte:reports:delete', 'berichte:reports', 'delete'),
    ('berichte:reports:edit', 'berichte:reports', 'edit'),
    ('berichte:reports:publish', 'berichte:reports', 'publish'),
    ('berichte:reports:read', 'berichte:reports', 'read'),
    ('berichte:schedule:manage', 'berichte:schedule', 'manage'),
    ('berichte:share:manage', 'berichte:share', 'manage'),
    ('crm:advisory:read', 'crm:advisory', 'read'),
    ('crm:advisory:write', 'crm:advisory', 'write'),
    ('crm:contact:create', 'crm:contact', 'create'),
    ('crm:contact:delete', 'crm:contact', 'delete'),
    ('crm:contact:edit', 'crm:contact', 'edit'),
    ('crm:contact:export', 'crm:contact', 'export'),
    ('crm:contact:read', 'crm:contact', 'read'),
    ('crm:deal:create', 'crm:deal', 'create'),
    ('crm:deal:delete', 'crm:deal', 'delete'),
    ('crm:deal:edit', 'crm:deal', 'edit'),
    ('crm:deal:read', 'crm:deal', 'read'),
    ('crm:import:run', 'crm:import', 'run'),
    ('crm:module:view', 'crm:module', 'view'),
    ('crm:pipeline:manage', 'crm:pipeline', 'manage'),
    ('crm:segment:override', 'crm:segment', 'override'),
    ('dashboard:module:view', 'dashboard:module', 'view'),
    ('dialer:agent:manage', 'dialer:agent', 'manage'),
    ('dialer:calls:read', 'dialer:calls', 'read'),
    ('dialer:calls:write', 'dialer:calls', 'write'),
    ('dialer:campaigns:manage', 'dialer:campaigns', 'manage'),
    ('dialer:campaigns:read', 'dialer:campaigns', 'read'),
    ('dialer:module:view', 'dialer:module', 'view'),
    ('dialer:outcomes:manage', 'dialer:outcomes', 'manage'),
    ('documents:file:delete', 'documents:file', 'delete'),
    ('documents:file:download', 'documents:file', 'download'),
    ('documents:file:edit', 'documents:file', 'edit'),
    ('documents:file:read', 'documents:file', 'read'),
    ('documents:file:upload', 'documents:file', 'upload'),
    ('documents:module:view', 'documents:module', 'view'),
    ('documents:share:manage', 'documents:share', 'manage'),
    ('documents:share_link:create', 'documents:share_link', 'create'),
    ('documents:template:manage', 'documents:template', 'manage'),
    ('documents:version:restore', 'documents:version', 'restore'),
    ('einkauf:catalog:read', 'einkauf:catalog', 'read'),
    ('einkauf:contract:call', 'einkauf:contract', 'call'),
    ('einkauf:contract:read', 'einkauf:contract', 'read'),
    ('einkauf:export:run', 'einkauf:export', 'run'),
    ('einkauf:module:view', 'einkauf:module', 'view'),
    ('einkauf:po:approve', 'einkauf:po', 'approve'),
    ('einkauf:po:cancel', 'einkauf:po', 'cancel'),
    ('einkauf:po:create', 'einkauf:po', 'create'),
    ('einkauf:po:delete', 'einkauf:po', 'delete'),
    ('einkauf:po:edit', 'einkauf:po', 'edit'),
    ('einkauf:po:read', 'einkauf:po', 'read'),
    ('einkauf:po:receive', 'einkauf:po', 'receive'),
    ('einkauf:po:send', 'einkauf:po', 'send'),
    ('einkauf:rating:create', 'einkauf:rating', 'create'),
    ('einkauf:supplier:create', 'einkauf:supplier', 'create'),
    ('einkauf:supplier:deactivate', 'einkauf:supplier', 'deactivate'),
    ('einkauf:supplier:edit', 'einkauf:supplier', 'edit'),
    ('einkauf:supplier:read', 'einkauf:supplier', 'read'),
    ('finance:amounts:view', 'finance:amounts', 'view'),
    ('finance:dunning:run', 'finance:dunning', 'run'),
    ('finance:export:run', 'finance:export', 'run'),
    ('finance:incoming:book', 'finance:incoming', 'book'),
    ('finance:incoming:review', 'finance:incoming', 'review'),
    ('finance:invoice:create', 'finance:invoice', 'create'),
    ('finance:invoice:delete', 'finance:invoice', 'delete'),
    ('finance:invoice:edit', 'finance:invoice', 'edit'),
    ('finance:invoice:read', 'finance:invoice', 'read'),
    ('finance:invoice:send', 'finance:invoice', 'send'),
    ('finance:module:view', 'finance:module', 'view'),
    ('finance:quote:create', 'finance:quote', 'create'),
    ('finance:quote:read', 'finance:quote', 'read'),
    ('finance:quote:send', 'finance:quote', 'send'),
    ('finance:settings:manage', 'finance:settings', 'manage'),
    ('formulare:export:run', 'formulare:export', 'run'),
    ('formulare:module:view', 'formulare:module', 'view'),
    ('formulare:schemas:create', 'formulare:schemas', 'create'),
    ('formulare:schemas:delete', 'formulare:schemas', 'delete'),
    ('formulare:schemas:edit', 'formulare:schemas', 'edit'),
    ('formulare:schemas:publish', 'formulare:schemas', 'publish'),
    ('formulare:schemas:read', 'formulare:schemas', 'read'),
    ('formulare:share:manage', 'formulare:share', 'manage'),
    ('formulare:submissions:read', 'formulare:submissions', 'read'),
    ('formulare:submissions:write', 'formulare:submissions', 'write'),
    ('fuhrpark:damage:create', 'fuhrpark:damage', 'create'),
    ('fuhrpark:export:run', 'fuhrpark:export', 'run'),
    ('fuhrpark:fuel:create', 'fuhrpark:fuel', 'create'),
    ('fuhrpark:fuel:read', 'fuhrpark:fuel', 'read'),
    ('fuhrpark:gps:read', 'fuhrpark:gps', 'read'),
    ('fuhrpark:module:view', 'fuhrpark:module', 'view'),
    ('fuhrpark:service:create', 'fuhrpark:service', 'create'),
    ('fuhrpark:service:read', 'fuhrpark:service', 'read'),
    ('fuhrpark:trip:create', 'fuhrpark:trip', 'create'),
    ('fuhrpark:trip:read', 'fuhrpark:trip', 'read'),
    ('fuhrpark:vehicle:manage', 'fuhrpark:vehicle', 'manage'),
    ('fuhrpark:vehicle:read', 'fuhrpark:vehicle', 'read'),
    ('helpdesk:canned:manage', 'helpdesk:canned', 'manage'),
    ('helpdesk:kb:manage', 'helpdesk:kb', 'manage'),
    ('helpdesk:module:view', 'helpdesk:module', 'view'),
    ('helpdesk:stats:view', 'helpdesk:stats', 'view'),
    ('helpdesk:ticket:create', 'helpdesk:ticket', 'create'),
    ('helpdesk:ticket:edit', 'helpdesk:ticket', 'edit'),
    ('helpdesk:ticket:read', 'helpdesk:ticket', 'read'),
    ('helpdesk:ticket:reply', 'helpdesk:ticket', 'reply'),
    ('infrastructure:backup:manage', 'infrastructure:backup', 'manage'),
    ('infrastructure:logs:export', 'infrastructure:logs', 'export'),
    ('infrastructure:module:view', 'infrastructure:module', 'view'),
    ('infrastructure:security:manage', 'infrastructure:security', 'manage'),
    ('infrastructure:service:manage', 'infrastructure:service', 'manage'),
    ('infrastructure:updates:manage', 'infrastructure:updates', 'manage'),
    ('inventar:attachment:manage', 'inventar:attachment', 'manage'),
    ('inventar:export:run', 'inventar:export', 'run'),
    ('inventar:inventur:book', 'inventar:inventur', 'book'),
    ('inventar:inventur:count', 'inventar:inventur', 'count'),
    ('inventar:inventur:create', 'inventar:inventur', 'create'),
    ('inventar:inventur:read', 'inventar:inventur', 'read'),
    ('inventar:item:create', 'inventar:item', 'create'),
    ('inventar:item:delete', 'inventar:item', 'delete'),
    ('inventar:item:edit', 'inventar:item', 'edit'),
    ('inventar:item:read', 'inventar:item', 'read'),
    ('inventar:location:read', 'inventar:location', 'read'),
    ('inventar:module:view', 'inventar:module', 'view'),
    ('inventar:movement:adjust', 'inventar:movement', 'adjust'),
    ('inventar:movement:create', 'inventar:movement', 'create'),
    ('inventar:movement:read', 'inventar:movement', 'read'),
    ('kalender:booking_page:manage', 'kalender:booking_page', 'manage'),
    ('kalender:category:manage', 'kalender:category', 'manage'),
    ('kalender:module:view', 'kalender:module', 'view'),
    ('kommunikation:canned:manage', 'kommunikation:canned', 'manage'),
    ('kommunikation:channel:manage', 'kommunikation:channel', 'manage'),
    ('kommunikation:module:view', 'kommunikation:module', 'view'),
    ('kommunikation:routing:manage', 'kommunikation:routing', 'manage'),
    ('kommunikation:team_inbox:manage', 'kommunikation:team_inbox', 'manage'),
    ('kommunikation:webhook:manage', 'kommunikation:webhook', 'manage'),
    ('mail:module:view', 'mail:module', 'view'),
    ('mail:settings:manage', 'mail:settings', 'manage'),
    ('notifications:module:view', 'notifications:module', 'view'),
    ('produktion:bom:create', 'produktion:bom', 'create'),
    ('produktion:bom:edit', 'produktion:bom', 'edit'),
    ('produktion:bom:read', 'produktion:bom', 'read'),
    ('produktion:export:run', 'produktion:export', 'run'),
    ('produktion:machine:manage', 'produktion:machine', 'manage'),
    ('produktion:machine:read', 'produktion:machine', 'read'),
    ('produktion:module:view', 'produktion:module', 'view'),
    ('produktion:order:cancel', 'produktion:order', 'cancel'),
    ('produktion:order:complete', 'produktion:order', 'complete'),
    ('produktion:order:create', 'produktion:order', 'create'),
    ('produktion:order:delete', 'produktion:order', 'delete'),
    ('produktion:order:edit', 'produktion:order', 'edit'),
    ('produktion:order:read', 'produktion:order', 'read'),
    ('produktion:order:start', 'produktion:order', 'start'),
    ('produktion:quality:create', 'produktion:quality', 'create'),
    ('produktion:quality:read', 'produktion:quality', 'read'),
    ('produktion:workstep:edit', 'produktion:workstep', 'edit'),
    ('rapporte:export:run', 'rapporte:export', 'run'),
    ('rapporte:measurement:manage', 'rapporte:measurement', 'manage'),
    ('rapporte:measurement:read', 'rapporte:measurement', 'read'),
    ('rapporte:module:view', 'rapporte:module', 'view'),
    ('rapporte:report:approve', 'rapporte:report', 'approve'),
    ('rapporte:report:create', 'rapporte:report', 'create'),
    ('rapporte:report:delete', 'rapporte:report', 'delete'),
    ('rapporte:report:edit', 'rapporte:report', 'edit'),
    ('rapporte:report:read', 'rapporte:report', 'read'),
    ('rapporte:template:read', 'rapporte:template', 'read'),
    ('schichten:assignment:manage', 'schichten:assignment', 'manage'),
    ('schichten:export:run', 'schichten:export', 'run'),
    ('schichten:module:view', 'schichten:module', 'view'),
    ('schichten:shift:publish', 'schichten:shift', 'publish'),
    ('schichten:shift:read', 'schichten:shift', 'read'),
    ('schichten:swap:approve', 'schichten:swap', 'approve'),
    ('schichten:swap:create', 'schichten:swap', 'create'),
    ('schichten:swap:read', 'schichten:swap', 'read'),
    ('schichten:template:manage', 'schichten:template', 'manage'),
    ('schichten:template:read', 'schichten:template', 'read'),
    ('security:audit:read', 'security:audit', 'read'),
    ('security:gdpr:execute', 'security:gdpr', 'execute'),
    ('security:module:view', 'security:module', 'view'),
    ('security:policy:manage', 'security:policy', 'manage'),
    ('security:vendor_access:manage', 'security:vendor_access', 'manage'),
    ('settings:module:view', 'settings:module', 'view'),
    ('settings:personal:manage', 'settings:personal', 'manage'),
    ('settings:tenant:manage', 'settings:tenant', 'manage'),
    ('team:absence:approve', 'team:absence', 'approve'),
    ('team:absence:read', 'team:absence', 'read'),
    ('team:absence_data:view', 'team:absence_data', 'view'),
    ('team:corrections:manage', 'team:corrections', 'manage'),
    ('team:data_job:edit', 'team:data_job', 'edit'),
    ('team:data_job:view', 'team:data_job', 'view'),
    ('team:data_personal:edit', 'team:data_personal', 'edit'),
    ('team:data_personal:view', 'team:data_personal', 'view'),
    ('team:directory:full', 'team:directory', 'full'),
    ('team:documents:edit', 'team:documents', 'edit'),
    ('team:documents:view', 'team:documents', 'view'),
    ('team:employee:create', 'team:employee', 'create'),
    ('team:employee:deactivate', 'team:employee', 'deactivate'),
    ('team:employee:edit', 'team:employee', 'edit'),
    ('team:employee:offboard', 'team:employee', 'offboard'),
    ('team:employee:read', 'team:employee', 'read'),
    ('team:module:view', 'team:module', 'view'),
    ('team:onboarding:manage', 'team:onboarding', 'manage'),
    ('team:payroll:run', 'team:payroll', 'run'),
    ('team:payroll:view', 'team:payroll', 'view'),
    ('team:role:assign', 'team:role', 'assign'),
    ('team:salary:edit', 'team:salary', 'edit'),
    ('team:salary:view', 'team:salary', 'view'),
    ('team:self:propose', 'team:self', 'propose'),
    ('team:training:manage', 'team:training', 'manage'),
    ('vermietung:export:run', 'vermietung:export', 'run'),
    ('vermietung:inspection:create', 'vermietung:inspection', 'create'),
    ('vermietung:module:view', 'vermietung:module', 'view'),
    ('vermietung:object:create', 'vermietung:object', 'create'),
    ('vermietung:object:delete', 'vermietung:object', 'delete'),
    ('vermietung:object:edit', 'vermietung:object', 'edit'),
    ('vermietung:object:read', 'vermietung:object', 'read'),
    ('vermietung:rental:cancel', 'vermietung:rental', 'cancel'),
    ('vermietung:rental:create', 'vermietung:rental', 'create'),
    ('vermietung:rental:edit', 'vermietung:rental', 'edit'),
    ('vermietung:rental:handover', 'vermietung:rental', 'handover'),
    ('vermietung:rental:read', 'vermietung:rental', 'read'),
    ('vertraege:contract:create', 'vertraege:contract', 'create'),
    ('vertraege:contract:delete', 'vertraege:contract', 'delete'),
    ('vertraege:contract:edit', 'vertraege:contract', 'edit'),
    ('vertraege:contract:read', 'vertraege:contract', 'read'),
    ('vertraege:contract:terminate', 'vertraege:contract', 'terminate'),
    ('vertraege:module:view', 'vertraege:module', 'view'),
    ('video:module:view', 'video:module', 'view'),
    ('wiki:article:create', 'wiki:article', 'create'),
    ('wiki:article:delete', 'wiki:article', 'delete'),
    ('wiki:article:edit', 'wiki:article', 'edit'),
    ('wiki:article:publish', 'wiki:article', 'publish'),
    ('wiki:article:read', 'wiki:article', 'read'),
    ('wiki:category:manage', 'wiki:category', 'manage'),
    ('wiki:module:view', 'wiki:module', 'view'),
    ('wiki:share_token:create', 'wiki:share_token', 'create'),
    ('wiki:template:manage', 'wiki:template', 'manage'),
    ('work:board:export', 'work:board', 'export'),
    ('work:module:view', 'work:module', 'view'),
    ('work:project:create', 'work:project', 'create'),
    ('work:project:delete', 'work:project', 'delete'),
    ('work:project:edit', 'work:project', 'edit'),
    ('work:project:manage_members', 'work:project', 'manage_members'),
    ('work:project:read', 'work:project', 'read'),
    ('work:task:be_assigned', 'work:task', 'be_assigned'),
    ('work:task:comment', 'work:task', 'comment'),
    ('work:task:create', 'work:task', 'create'),
    ('work:task:delete', 'work:task', 'delete'),
    ('work:task:edit', 'work:task', 'edit'),
    ('work:task:read', 'work:task', 'read'),
    ('work:time:log', 'work:time', 'log'),
    ('zeiterfassung:corrections:approve', 'zeiterfassung:corrections', 'approve'),
    ('zeiterfassung:export:run', 'zeiterfassung:export', 'run'),
    ('zeiterfassung:module:view', 'zeiterfassung:module', 'view'),
    ('zeiterfassung:team:view', 'zeiterfassung:team', 'view'),
    ('zeiterfassung:week:approve', 'zeiterfassung:week', 'approve')
ON CONFLICT (name) DO NOTHING;

-- (b) the 4 missing preset roles + color backfill on the 3 existing ones
-- Preset roles migration 000002 never seeded. tenant_id stays NULL — system
-- preset, visible to every tenant via the roles RLS policy.
INSERT INTO roles (name, description, color) VALUES
    ('it_admin', 'Technical administration without HR/salary data', 'hsl(25 95% 53%)'),
    ('hr_admin', 'People management incl. protected HR data; assigns roles', 'hsl(270 76% 55%)'),
    ('readonly', 'Sees everything relevant, changes nothing', 'hsl(215 16% 47%)'),
    ('extern', 'Assigned tasks and read-only documents, nothing else', 'hsl(180 45% 42%)')
ON CONFLICT (COALESCE(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), name) DO NOTHING;

-- Backfill color on the 3 presets migration 000002 already created.
UPDATE roles SET color = 'hsl(0 72% 51%)' WHERE name = 'admin' AND tenant_id IS NULL;
UPDATE roles SET color = 'hsl(217 91% 60%)' WHERE name = 'manager' AND tenant_id IS NULL;
UPDATE roles SET color = 'hsl(142 71% 45%)' WHERE name = 'member' AND tenant_id IS NULL;

-- (c) role_permissions with scope, all 7 presets
-- admin: 282 grant(s) at scope 'all'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'all'
FROM roles r, permissions p
WHERE r.name = 'admin' AND r.tenant_id IS NULL AND p.name IN ('admin:ai:manage', 'admin:branding:manage', 'admin:company:manage', 'admin:customization:manage', 'admin:impersonate:run', 'admin:integrations:manage', 'admin:it:manage', 'admin:license:manage', 'admin:module:view', 'admin:modules:manage', 'admin:role:assign', 'admin:role:create', 'admin:role:delete', 'admin:role:edit', 'admin:role:read', 'admin:user:deactivate', 'admin:user:invite', 'admin:user:read', 'admin:user_override:manage', 'automatisierung:automations:create', 'automatisierung:automations:delete', 'automatisierung:automations:edit', 'automatisierung:automations:read', 'automatisierung:automations:toggle', 'automatisierung:executions:read', 'automatisierung:module:view', 'berichte:datev:read', 'berichte:export:run', 'berichte:module:view', 'berichte:reports:create', 'berichte:reports:delete', 'berichte:reports:edit', 'berichte:reports:publish', 'berichte:reports:read', 'berichte:schedule:manage', 'berichte:share:manage', 'crm:advisory:read', 'crm:advisory:write', 'crm:contact:create', 'crm:contact:delete', 'crm:contact:edit', 'crm:contact:export', 'crm:contact:read', 'crm:deal:create', 'crm:deal:delete', 'crm:deal:edit', 'crm:deal:read', 'crm:import:run', 'crm:module:view', 'crm:pipeline:manage', 'crm:segment:override', 'dashboard:module:view', 'dialer:agent:manage', 'dialer:calls:read', 'dialer:calls:write', 'dialer:campaigns:manage', 'dialer:campaigns:read', 'dialer:module:view', 'dialer:outcomes:manage', 'documents:file:delete', 'documents:file:download', 'documents:file:edit', 'documents:file:read', 'documents:file:upload', 'documents:module:view', 'documents:share:manage', 'documents:share_link:create', 'documents:template:manage', 'documents:version:restore', 'einkauf:catalog:read', 'einkauf:contract:call', 'einkauf:contract:read', 'einkauf:export:run', 'einkauf:module:view', 'einkauf:po:approve', 'einkauf:po:cancel', 'einkauf:po:create', 'einkauf:po:delete', 'einkauf:po:edit', 'einkauf:po:read', 'einkauf:po:receive', 'einkauf:po:send', 'einkauf:rating:create', 'einkauf:supplier:create', 'einkauf:supplier:deactivate', 'einkauf:supplier:edit', 'einkauf:supplier:read', 'finance:amounts:view', 'finance:dunning:run', 'finance:export:run', 'finance:incoming:book', 'finance:incoming:review', 'finance:invoice:create', 'finance:invoice:delete', 'finance:invoice:edit', 'finance:invoice:read', 'finance:invoice:send', 'finance:module:view', 'finance:quote:create', 'finance:quote:read', 'finance:quote:send', 'finance:settings:manage', 'formulare:export:run', 'formulare:module:view', 'formulare:schemas:create', 'formulare:schemas:delete', 'formulare:schemas:edit', 'formulare:schemas:publish', 'formulare:schemas:read', 'formulare:share:manage', 'formulare:submissions:read', 'formulare:submissions:write', 'fuhrpark:damage:create', 'fuhrpark:export:run', 'fuhrpark:fuel:create', 'fuhrpark:fuel:read', 'fuhrpark:gps:read', 'fuhrpark:module:view', 'fuhrpark:service:create', 'fuhrpark:service:read', 'fuhrpark:trip:create', 'fuhrpark:trip:read', 'fuhrpark:vehicle:manage', 'fuhrpark:vehicle:read', 'helpdesk:canned:manage', 'helpdesk:kb:manage', 'helpdesk:module:view', 'helpdesk:stats:view', 'helpdesk:ticket:create', 'helpdesk:ticket:edit', 'helpdesk:ticket:read', 'helpdesk:ticket:reply', 'infrastructure:backup:manage', 'infrastructure:logs:export', 'infrastructure:module:view', 'infrastructure:security:manage', 'infrastructure:service:manage', 'infrastructure:updates:manage', 'inventar:attachment:manage', 'inventar:export:run', 'inventar:inventur:book', 'inventar:inventur:count', 'inventar:inventur:create', 'inventar:inventur:read', 'inventar:item:create', 'inventar:item:delete', 'inventar:item:edit', 'inventar:item:read', 'inventar:location:read', 'inventar:module:view', 'inventar:movement:adjust', 'inventar:movement:create', 'inventar:movement:read', 'kalender:booking_page:manage', 'kalender:category:manage', 'kalender:module:view', 'kommunikation:canned:manage', 'kommunikation:channel:manage', 'kommunikation:module:view', 'kommunikation:routing:manage', 'kommunikation:team_inbox:manage', 'kommunikation:webhook:manage', 'mail:module:view', 'mail:settings:manage', 'notifications:module:view', 'produktion:bom:create', 'produktion:bom:edit', 'produktion:bom:read', 'produktion:export:run', 'produktion:machine:manage', 'produktion:machine:read', 'produktion:module:view', 'produktion:order:cancel', 'produktion:order:complete', 'produktion:order:create', 'produktion:order:delete', 'produktion:order:edit', 'produktion:order:read', 'produktion:order:start', 'produktion:quality:create', 'produktion:quality:read', 'produktion:workstep:edit', 'rapporte:export:run', 'rapporte:measurement:manage', 'rapporte:measurement:read', 'rapporte:module:view', 'rapporte:report:approve', 'rapporte:report:create', 'rapporte:report:delete', 'rapporte:report:edit', 'rapporte:report:read', 'rapporte:template:read', 'schichten:assignment:manage', 'schichten:export:run', 'schichten:module:view', 'schichten:shift:publish', 'schichten:shift:read', 'schichten:swap:approve', 'schichten:swap:create', 'schichten:swap:read', 'schichten:template:manage', 'schichten:template:read', 'security:audit:read', 'security:gdpr:execute', 'security:module:view', 'security:policy:manage', 'security:vendor_access:manage', 'settings:module:view', 'settings:personal:manage', 'settings:tenant:manage', 'team:absence:approve', 'team:absence:read', 'team:absence_data:view', 'team:corrections:manage', 'team:data_job:edit', 'team:data_job:view', 'team:data_personal:edit', 'team:data_personal:view', 'team:directory:full', 'team:documents:edit', 'team:documents:view', 'team:employee:create', 'team:employee:deactivate', 'team:employee:edit', 'team:employee:offboard', 'team:employee:read', 'team:module:view', 'team:onboarding:manage', 'team:payroll:run', 'team:payroll:view', 'team:role:assign', 'team:salary:edit', 'team:salary:view', 'team:self:propose', 'team:training:manage', 'vermietung:export:run', 'vermietung:inspection:create', 'vermietung:module:view', 'vermietung:object:create', 'vermietung:object:delete', 'vermietung:object:edit', 'vermietung:object:read', 'vermietung:rental:cancel', 'vermietung:rental:create', 'vermietung:rental:edit', 'vermietung:rental:handover', 'vermietung:rental:read', 'vertraege:contract:create', 'vertraege:contract:delete', 'vertraege:contract:edit', 'vertraege:contract:read', 'vertraege:contract:terminate', 'vertraege:module:view', 'video:module:view', 'wiki:article:create', 'wiki:article:delete', 'wiki:article:edit', 'wiki:article:publish', 'wiki:article:read', 'wiki:category:manage', 'wiki:module:view', 'wiki:share_token:create', 'wiki:template:manage', 'work:board:export', 'work:module:view', 'work:project:create', 'work:project:delete', 'work:project:edit', 'work:project:manage_members', 'work:project:read', 'work:task:be_assigned', 'work:task:comment', 'work:task:create', 'work:task:delete', 'work:task:edit', 'work:task:read', 'work:time:log', 'zeiterfassung:corrections:approve', 'zeiterfassung:export:run', 'zeiterfassung:module:view', 'zeiterfassung:team:view', 'zeiterfassung:week:approve')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- it_admin: 104 grant(s) at scope 'all'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'all'
FROM roles r, permissions p
WHERE r.name = 'it_admin' AND r.tenant_id IS NULL AND p.name IN ('admin:ai:manage', 'admin:customization:manage', 'admin:integrations:manage', 'admin:it:manage', 'admin:module:view', 'admin:modules:manage', 'admin:role:assign', 'admin:role:create', 'admin:role:delete', 'admin:role:edit', 'admin:role:read', 'admin:user:deactivate', 'admin:user:invite', 'admin:user:read', 'automatisierung:automations:create', 'automatisierung:automations:delete', 'automatisierung:automations:edit', 'automatisierung:automations:read', 'automatisierung:automations:toggle', 'automatisierung:executions:read', 'automatisierung:module:view', 'berichte:module:view', 'berichte:reports:read', 'crm:contact:read', 'crm:deal:read', 'crm:module:view', 'dashboard:module:view', 'dialer:calls:read', 'dialer:campaigns:read', 'dialer:module:view', 'documents:file:read', 'documents:module:view', 'einkauf:catalog:read', 'einkauf:contract:read', 'einkauf:module:view', 'einkauf:po:read', 'einkauf:supplier:read', 'formulare:module:view', 'formulare:schemas:read', 'formulare:submissions:read', 'fuhrpark:fuel:read', 'fuhrpark:module:view', 'fuhrpark:service:read', 'fuhrpark:trip:read', 'fuhrpark:vehicle:read', 'helpdesk:canned:manage', 'helpdesk:kb:manage', 'helpdesk:module:view', 'helpdesk:stats:view', 'helpdesk:ticket:create', 'helpdesk:ticket:edit', 'helpdesk:ticket:read', 'helpdesk:ticket:reply', 'infrastructure:backup:manage', 'infrastructure:logs:export', 'infrastructure:module:view', 'infrastructure:security:manage', 'infrastructure:service:manage', 'infrastructure:updates:manage', 'inventar:inventur:read', 'inventar:item:read', 'inventar:location:read', 'inventar:module:view', 'inventar:movement:read', 'kalender:module:view', 'kommunikation:module:view', 'kommunikation:webhook:manage', 'mail:module:view', 'mail:settings:manage', 'notifications:module:view', 'produktion:bom:read', 'produktion:machine:read', 'produktion:module:view', 'produktion:order:read', 'produktion:quality:read', 'rapporte:measurement:read', 'rapporte:module:view', 'rapporte:report:read', 'rapporte:template:read', 'schichten:module:view', 'schichten:shift:read', 'schichten:swap:read', 'schichten:template:read', 'security:audit:read', 'security:module:view', 'security:policy:manage', 'settings:module:view', 'settings:personal:manage', 'settings:tenant:manage', 'team:directory:full', 'team:employee:read', 'team:module:view', 'vermietung:module:view', 'vermietung:object:read', 'vermietung:rental:read', 'vertraege:contract:read', 'vertraege:module:view', 'video:module:view', 'wiki:article:read', 'wiki:module:view', 'work:module:view', 'work:project:read', 'work:task:read', 'zeiterfassung:module:view')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- hr_admin: 66 grant(s) at scope 'all'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'all'
FROM roles r, permissions p
WHERE r.name = 'hr_admin' AND r.tenant_id IS NULL AND p.name IN ('admin:module:view', 'admin:role:assign', 'admin:role:read', 'admin:user:deactivate', 'admin:user:invite', 'admin:user:read', 'crm:contact:read', 'crm:module:view', 'dashboard:module:view', 'documents:file:download', 'documents:file:read', 'documents:file:upload', 'documents:module:view', 'kalender:module:view', 'kommunikation:module:view', 'mail:module:view', 'notifications:module:view', 'schichten:assignment:manage', 'schichten:export:run', 'schichten:module:view', 'schichten:shift:publish', 'schichten:shift:read', 'schichten:swap:approve', 'schichten:swap:create', 'schichten:swap:read', 'schichten:template:manage', 'schichten:template:read', 'settings:module:view', 'settings:personal:manage', 'team:absence:approve', 'team:absence:read', 'team:absence_data:view', 'team:corrections:manage', 'team:data_job:edit', 'team:data_job:view', 'team:data_personal:edit', 'team:data_personal:view', 'team:directory:full', 'team:documents:edit', 'team:documents:view', 'team:employee:create', 'team:employee:deactivate', 'team:employee:edit', 'team:employee:offboard', 'team:employee:read', 'team:module:view', 'team:onboarding:manage', 'team:payroll:run', 'team:payroll:view', 'team:role:assign', 'team:salary:edit', 'team:salary:view', 'team:self:propose', 'team:training:manage', 'video:module:view', 'wiki:article:create', 'wiki:article:read', 'wiki:module:view', 'work:module:view', 'work:project:read', 'work:task:read', 'zeiterfassung:corrections:approve', 'zeiterfassung:export:run', 'zeiterfassung:module:view', 'zeiterfassung:team:view', 'zeiterfassung:week:approve')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- hr_admin: 5 grant(s) at scope 'own'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'own'
FROM roles r, permissions p
WHERE r.name = 'hr_admin' AND r.tenant_id IS NULL AND p.name IN ('work:task:be_assigned', 'work:task:comment', 'work:task:create', 'work:task:edit', 'work:time:log')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- manager: 192 grant(s) at scope 'all'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'all'
FROM roles r, permissions p
WHERE r.name = 'manager' AND r.tenant_id IS NULL AND p.name IN ('automatisierung:automations:create', 'automatisierung:automations:delete', 'automatisierung:automations:edit', 'automatisierung:automations:read', 'automatisierung:automations:toggle', 'automatisierung:executions:read', 'automatisierung:module:view', 'berichte:export:run', 'berichte:module:view', 'berichte:reports:create', 'berichte:reports:delete', 'berichte:reports:edit', 'berichte:reports:publish', 'berichte:reports:read', 'berichte:schedule:manage', 'berichte:share:manage', 'crm:contact:read', 'crm:deal:create', 'crm:deal:read', 'crm:module:view', 'dashboard:module:view', 'dialer:agent:manage', 'dialer:calls:read', 'dialer:calls:write', 'dialer:campaigns:manage', 'dialer:campaigns:read', 'dialer:module:view', 'dialer:outcomes:manage', 'documents:file:download', 'documents:file:read', 'documents:file:upload', 'documents:module:view', 'documents:share:manage', 'einkauf:catalog:read', 'einkauf:contract:call', 'einkauf:contract:read', 'einkauf:export:run', 'einkauf:module:view', 'einkauf:po:approve', 'einkauf:po:cancel', 'einkauf:po:create', 'einkauf:po:delete', 'einkauf:po:edit', 'einkauf:po:read', 'einkauf:po:receive', 'einkauf:po:send', 'einkauf:rating:create', 'einkauf:supplier:create', 'einkauf:supplier:deactivate', 'einkauf:supplier:edit', 'einkauf:supplier:read', 'formulare:export:run', 'formulare:module:view', 'formulare:schemas:create', 'formulare:schemas:delete', 'formulare:schemas:edit', 'formulare:schemas:publish', 'formulare:schemas:read', 'formulare:share:manage', 'formulare:submissions:read', 'formulare:submissions:write', 'fuhrpark:damage:create', 'fuhrpark:export:run', 'fuhrpark:fuel:create', 'fuhrpark:fuel:read', 'fuhrpark:gps:read', 'fuhrpark:module:view', 'fuhrpark:service:create', 'fuhrpark:service:read', 'fuhrpark:trip:create', 'fuhrpark:trip:read', 'fuhrpark:vehicle:manage', 'fuhrpark:vehicle:read', 'helpdesk:canned:manage', 'helpdesk:kb:manage', 'helpdesk:module:view', 'helpdesk:stats:view', 'helpdesk:ticket:create', 'helpdesk:ticket:edit', 'helpdesk:ticket:read', 'helpdesk:ticket:reply', 'inventar:attachment:manage', 'inventar:export:run', 'inventar:inventur:book', 'inventar:inventur:count', 'inventar:inventur:create', 'inventar:inventur:read', 'inventar:item:create', 'inventar:item:delete', 'inventar:item:edit', 'inventar:item:read', 'inventar:location:read', 'inventar:module:view', 'inventar:movement:adjust', 'inventar:movement:create', 'inventar:movement:read', 'kalender:booking_page:manage', 'kalender:category:manage', 'kalender:module:view', 'kommunikation:canned:manage', 'kommunikation:channel:manage', 'kommunikation:module:view', 'kommunikation:routing:manage', 'kommunikation:team_inbox:manage', 'mail:module:view', 'notifications:module:view', 'produktion:bom:create', 'produktion:bom:edit', 'produktion:bom:read', 'produktion:export:run', 'produktion:machine:manage', 'produktion:machine:read', 'produktion:module:view', 'produktion:order:cancel', 'produktion:order:complete', 'produktion:order:create', 'produktion:order:delete', 'produktion:order:edit', 'produktion:order:read', 'produktion:order:start', 'produktion:quality:create', 'produktion:quality:read', 'produktion:workstep:edit', 'rapporte:export:run', 'rapporte:measurement:manage', 'rapporte:measurement:read', 'rapporte:module:view', 'rapporte:report:approve', 'rapporte:report:create', 'rapporte:report:delete', 'rapporte:report:edit', 'rapporte:report:read', 'rapporte:template:read', 'schichten:assignment:manage', 'schichten:export:run', 'schichten:module:view', 'schichten:shift:publish', 'schichten:shift:read', 'schichten:swap:approve', 'schichten:swap:create', 'schichten:swap:read', 'schichten:template:manage', 'schichten:template:read', 'settings:module:view', 'settings:personal:manage', 'team:absence:approve', 'team:absence:read', 'team:corrections:manage', 'team:module:view', 'team:onboarding:manage', 'team:self:propose', 'team:training:manage', 'vermietung:export:run', 'vermietung:inspection:create', 'vermietung:module:view', 'vermietung:object:create', 'vermietung:object:delete', 'vermietung:object:edit', 'vermietung:object:read', 'vermietung:rental:cancel', 'vermietung:rental:create', 'vermietung:rental:edit', 'vermietung:rental:handover', 'vermietung:rental:read', 'vertraege:contract:create', 'vertraege:contract:delete', 'vertraege:contract:edit', 'vertraege:contract:read', 'vertraege:contract:terminate', 'vertraege:module:view', 'video:module:view', 'wiki:article:create', 'wiki:article:publish', 'wiki:article:read', 'wiki:category:manage', 'wiki:module:view', 'work:board:export', 'work:module:view', 'work:project:create', 'work:project:edit', 'work:project:manage_members', 'work:project:read', 'work:task:be_assigned', 'work:task:comment', 'work:task:create', 'work:task:read', 'work:time:log', 'zeiterfassung:corrections:approve', 'zeiterfassung:export:run', 'zeiterfassung:module:view', 'zeiterfassung:team:view', 'zeiterfassung:week:approve')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- manager: 12 grant(s) at scope 'team'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'team'
FROM roles r, permissions p
WHERE r.name = 'manager' AND r.tenant_id IS NULL AND p.name IN ('crm:contact:create', 'crm:contact:edit', 'crm:deal:delete', 'crm:deal:edit', 'documents:file:edit', 'team:absence_data:view', 'team:data_job:view', 'team:data_personal:view', 'team:documents:view', 'team:employee:read', 'work:task:delete', 'work:task:edit')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- manager: 1 grant(s) at scope 'own'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'own'
FROM roles r, permissions p
WHERE r.name = 'manager' AND r.tenant_id IS NULL AND p.name IN ('wiki:article:edit')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- member: 93 grant(s) at scope 'all'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'all'
FROM roles r, permissions p
WHERE r.name = 'member' AND r.tenant_id IS NULL AND p.name IN ('berichte:module:view', 'berichte:reports:create', 'berichte:reports:read', 'crm:contact:read', 'crm:deal:read', 'crm:module:view', 'dashboard:module:view', 'dialer:calls:read', 'dialer:calls:write', 'dialer:campaigns:read', 'dialer:module:view', 'documents:file:download', 'documents:file:read', 'documents:file:upload', 'documents:module:view', 'einkauf:catalog:read', 'einkauf:contract:read', 'einkauf:module:view', 'einkauf:po:create', 'einkauf:po:read', 'einkauf:po:receive', 'einkauf:supplier:read', 'formulare:module:view', 'formulare:schemas:read', 'formulare:submissions:read', 'formulare:submissions:write', 'fuhrpark:damage:create', 'fuhrpark:fuel:create', 'fuhrpark:fuel:read', 'fuhrpark:module:view', 'fuhrpark:service:read', 'fuhrpark:trip:create', 'fuhrpark:trip:read', 'fuhrpark:vehicle:read', 'helpdesk:module:view', 'helpdesk:ticket:create', 'helpdesk:ticket:reply', 'inventar:inventur:count', 'inventar:inventur:read', 'inventar:item:read', 'inventar:location:read', 'inventar:module:view', 'inventar:movement:create', 'inventar:movement:read', 'kalender:module:view', 'kommunikation:channel:manage', 'kommunikation:module:view', 'mail:module:view', 'notifications:module:view', 'produktion:bom:read', 'produktion:export:run', 'produktion:machine:read', 'produktion:module:view', 'produktion:order:complete', 'produktion:order:read', 'produktion:order:start', 'produktion:quality:create', 'produktion:quality:read', 'produktion:workstep:edit', 'rapporte:export:run', 'rapporte:measurement:manage', 'rapporte:measurement:read', 'rapporte:module:view', 'rapporte:report:create', 'rapporte:template:read', 'schichten:module:view', 'schichten:shift:read', 'settings:module:view', 'settings:personal:manage', 'team:absence:read', 'team:employee:read', 'team:module:view', 'team:self:propose', 'vermietung:inspection:create', 'vermietung:module:view', 'vermietung:object:read', 'vermietung:rental:create', 'vermietung:rental:edit', 'vermietung:rental:handover', 'vermietung:rental:read', 'vertraege:contract:read', 'vertraege:module:view', 'video:module:view', 'wiki:article:create', 'wiki:article:read', 'wiki:module:view', 'work:module:view', 'work:project:read', 'work:task:be_assigned', 'work:task:comment', 'work:task:create', 'work:task:read', 'zeiterfassung:module:view')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- member: 2 grant(s) at scope 'team'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'team'
FROM roles r, permissions p
WHERE r.name = 'member' AND r.tenant_id IS NULL AND p.name IN ('crm:contact:create', 'crm:contact:edit')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- member: 15 grant(s) at scope 'own'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'own'
FROM roles r, permissions p
WHERE r.name = 'member' AND r.tenant_id IS NULL AND p.name IN ('berichte:reports:edit', 'documents:file:edit', 'helpdesk:ticket:read', 'rapporte:report:edit', 'rapporte:report:read', 'schichten:swap:create', 'schichten:swap:read', 'team:absence_data:view', 'team:data_job:view', 'team:data_personal:view', 'team:documents:view', 'team:salary:view', 'wiki:article:edit', 'work:task:edit', 'work:time:log')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- readonly: 74 grant(s) at scope 'all'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'all'
FROM roles r, permissions p
WHERE r.name = 'readonly' AND r.tenant_id IS NULL AND p.name IN ('automatisierung:automations:read', 'automatisierung:executions:read', 'automatisierung:module:view', 'berichte:datev:read', 'berichte:module:view', 'berichte:reports:read', 'crm:contact:read', 'crm:deal:read', 'crm:module:view', 'dashboard:module:view', 'dialer:calls:read', 'dialer:campaigns:read', 'dialer:module:view', 'documents:file:read', 'documents:module:view', 'einkauf:catalog:read', 'einkauf:contract:read', 'einkauf:module:view', 'einkauf:po:read', 'einkauf:supplier:read', 'finance:amounts:view', 'finance:invoice:read', 'finance:module:view', 'finance:quote:read', 'formulare:module:view', 'formulare:schemas:read', 'formulare:submissions:read', 'fuhrpark:fuel:read', 'fuhrpark:module:view', 'fuhrpark:service:read', 'fuhrpark:trip:read', 'fuhrpark:vehicle:read', 'helpdesk:module:view', 'helpdesk:stats:view', 'helpdesk:ticket:read', 'inventar:inventur:read', 'inventar:item:read', 'inventar:location:read', 'inventar:module:view', 'inventar:movement:read', 'kalender:module:view', 'kommunikation:module:view', 'mail:module:view', 'notifications:module:view', 'produktion:bom:read', 'produktion:machine:read', 'produktion:module:view', 'produktion:order:read', 'produktion:quality:read', 'rapporte:measurement:read', 'rapporte:module:view', 'rapporte:report:read', 'rapporte:template:read', 'schichten:module:view', 'schichten:shift:read', 'schichten:swap:read', 'schichten:template:read', 'settings:module:view', 'settings:personal:manage', 'team:absence:read', 'team:employee:read', 'team:module:view', 'vermietung:module:view', 'vermietung:object:read', 'vermietung:rental:read', 'vertraege:contract:read', 'vertraege:module:view', 'video:module:view', 'wiki:article:read', 'wiki:module:view', 'work:module:view', 'work:project:read', 'work:task:read', 'zeiterfassung:module:view')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- extern: 6 grant(s) at scope 'all'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'all'
FROM roles r, permissions p
WHERE r.name = 'extern' AND r.tenant_id IS NULL AND p.name IN ('dashboard:module:view', 'documents:module:view', 'notifications:module:view', 'settings:module:view', 'settings:personal:manage', 'work:module:view')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- extern: 3 grant(s) at scope 'team'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'team'
FROM roles r, permissions p
WHERE r.name = 'extern' AND r.tenant_id IS NULL AND p.name IN ('documents:file:read', 'work:project:read', 'work:task:read')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

-- extern: 2 grant(s) at scope 'own'
INSERT INTO role_permissions (role_id, permission_id, scope)
SELECT r.id, p.id, 'own'
FROM roles r, permissions p
WHERE r.name = 'extern' AND r.tenant_id IS NULL AND p.name IN ('work:task:be_assigned', 'work:task:comment')
ON CONFLICT (role_id, permission_id) DO UPDATE SET scope = EXCLUDED.scope;

COMMIT;
