// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/berichte/v1/berichte.proto

package berichtev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BerichteService_CreateDefinition_FullMethodName  = "/berichte.v1.BerichteService/CreateDefinition"
	BerichteService_GetDefinition_FullMethodName     = "/berichte.v1.BerichteService/GetDefinition"
	BerichteService_UpdateDefinition_FullMethodName  = "/berichte.v1.BerichteService/UpdateDefinition"
	BerichteService_DeleteDefinition_FullMethodName  = "/berichte.v1.BerichteService/DeleteDefinition"
	BerichteService_ListDefinitions_FullMethodName   = "/berichte.v1.BerichteService/ListDefinitions"
	BerichteService_RunReport_FullMethodName         = "/berichte.v1.BerichteService/RunReport"
	BerichteService_GetCachedResult_FullMethodName   = "/berichte.v1.BerichteService/GetCachedResult"
	BerichteService_InvalidateCache_FullMethodName   = "/berichte.v1.BerichteService/InvalidateCache"
	BerichteService_ExportReport_FullMethodName      = "/berichte.v1.BerichteService/ExportReport"
	BerichteService_CreateSchedule_FullMethodName    = "/berichte.v1.BerichteService/CreateSchedule"
	BerichteService_UpdateSchedule_FullMethodName    = "/berichte.v1.BerichteService/UpdateSchedule"
	BerichteService_DeleteSchedule_FullMethodName    = "/berichte.v1.BerichteService/DeleteSchedule"
	BerichteService_ListSchedules_FullMethodName     = "/berichte.v1.BerichteService/ListSchedules"
	BerichteService_ToggleSchedule_FullMethodName    = "/berichte.v1.BerichteService/ToggleSchedule"
	BerichteService_GetDashboardKPIs_FullMethodName  = "/berichte.v1.BerichteService/GetDashboardKPIs"
	BerichteService_CreateDocument_FullMethodName    = "/berichte.v1.BerichteService/CreateDocument"
	BerichteService_GetDocument_FullMethodName       = "/berichte.v1.BerichteService/GetDocument"
	BerichteService_UpdateDocument_FullMethodName    = "/berichte.v1.BerichteService/UpdateDocument"
	BerichteService_DeleteDocument_FullMethodName    = "/berichte.v1.BerichteService/DeleteDocument"
	BerichteService_ListDocuments_FullMethodName     = "/berichte.v1.BerichteService/ListDocuments"
	BerichteService_ExportDocumentPDF_FullMethodName = "/berichte.v1.BerichteService/ExportDocumentPDF"
	BerichteService_ListTemplates_FullMethodName     = "/berichte.v1.BerichteService/ListTemplates"
	BerichteService_CreateShareToken_FullMethodName  = "/berichte.v1.BerichteService/CreateShareToken"
	BerichteService_ListShareTokens_FullMethodName   = "/berichte.v1.BerichteService/ListShareTokens"
	BerichteService_RevokeShareToken_FullMethodName  = "/berichte.v1.BerichteService/RevokeShareToken"
	BerichteService_GetSharedDocument_FullMethodName = "/berichte.v1.BerichteService/GetSharedDocument"
)

// BerichteServiceClient is the client API for BerichteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BerichteServiceClient interface {
	// Definitions (CRUD)
	CreateDefinition(ctx context.Context, in *CreateDefinitionRequest, opts ...grpc.CallOption) (*DefinitionResponse, error)
	GetDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*DefinitionResponse, error)
	UpdateDefinition(ctx context.Context, in *UpdateDefinitionRequest, opts ...grpc.CallOption) (*DefinitionResponse, error)
	DeleteDefinition(ctx context.Context, in *DeleteDefinitionRequest, opts ...grpc.CallOption) (*DeleteDefinitionResponse, error)
	ListDefinitions(ctx context.Context, in *ListDefinitionsRequest, opts ...grpc.CallOption) (*ListDefinitionsResponse, error)
	// Run & Cache
	RunReport(ctx context.Context, in *RunReportRequest, opts ...grpc.CallOption) (*RunReportResponse, error)
	GetCachedResult(ctx context.Context, in *GetCachedResultRequest, opts ...grpc.CallOption) (*RunReportResponse, error)
	InvalidateCache(ctx context.Context, in *InvalidateCacheRequest, opts ...grpc.CallOption) (*InvalidateCacheResponse, error)
	// Export
	ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
	// Schedules
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error)
	ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error)
	ToggleSchedule(ctx context.Context, in *ToggleScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// KPIs (Dashboard convenience)
	GetDashboardKPIs(ctx context.Context, in *DashboardKPIsRequest, opts ...grpc.CallOption) (*DashboardKPIsResponse, error)
	// Documents (multi-page authoring)
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	// ExportDocumentPDF renders the document's block tree (rows -> columns ->
	// blocks) to a PDF via the maroto renderer in berichte/export. See
	// export.DocumentPDFExporter for the block-type mapping.
	ExportDocumentPDF(ctx context.Context, in *ExportDocumentPDFRequest, opts ...grpc.CallOption) (*ExportDocumentPDFResponse, error)
	// Templates (static starter structures for "Neuer Bericht aus Vorlage")
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	// External share links for a report document.
	CreateShareToken(ctx context.Context, in *CreateShareTokenRequest, opts ...grpc.CallOption) (*ShareTokenResponse, error)
	ListShareTokens(ctx context.Context, in *ListShareTokensRequest, opts ...grpc.CallOption) (*ListShareTokensResponse, error)
	RevokeShareToken(ctx context.Context, in *RevokeShareTokenRequest, opts ...grpc.CallOption) (*RevokeShareTokenResponse, error)
	// GetSharedDocument serves the unauthenticated public read. It takes no
	// tenant_id: the caller has none, and the tenant is resolved from the token
	// itself. See berichte.Service.GetSharedDocument.
	GetSharedDocument(ctx context.Context, in *GetSharedDocumentRequest, opts ...grpc.CallOption) (*GetSharedDocumentResponse, error)
}

type berichteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBerichteServiceClient(cc grpc.ClientConnInterface) BerichteServiceClient {
	return &berichteServiceClient{cc}
}

func (c *berichteServiceClient) CreateDefinition(ctx context.Context, in *CreateDefinitionRequest, opts ...grpc.CallOption) (*DefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefinitionResponse)
	err := c.cc.Invoke(ctx, BerichteService_CreateDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) GetDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*DefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefinitionResponse)
	err := c.cc.Invoke(ctx, BerichteService_GetDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) UpdateDefinition(ctx context.Context, in *UpdateDefinitionRequest, opts ...grpc.CallOption) (*DefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefinitionResponse)
	err := c.cc.Invoke(ctx, BerichteService_UpdateDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) DeleteDefinition(ctx context.Context, in *DeleteDefinitionRequest, opts ...grpc.CallOption) (*DeleteDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDefinitionResponse)
	err := c.cc.Invoke(ctx, BerichteService_DeleteDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) ListDefinitions(ctx context.Context, in *ListDefinitionsRequest, opts ...grpc.CallOption) (*ListDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDefinitionsResponse)
	err := c.cc.Invoke(ctx, BerichteService_ListDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) RunReport(ctx context.Context, in *RunReportRequest, opts ...grpc.CallOption) (*RunReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunReportResponse)
	err := c.cc.Invoke(ctx, BerichteService_RunReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) GetCachedResult(ctx context.Context, in *GetCachedResultRequest, opts ...grpc.CallOption) (*RunReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunReportResponse)
	err := c.cc.Invoke(ctx, BerichteService_GetCachedResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) InvalidateCache(ctx context.Context, in *InvalidateCacheRequest, opts ...grpc.CallOption) (*InvalidateCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateCacheResponse)
	err := c.cc.Invoke(ctx, BerichteService_InvalidateCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, BerichteService_ExportReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, BerichteService_CreateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, BerichteService_UpdateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScheduleResponse)
	err := c.cc.Invoke(ctx, BerichteService_DeleteSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchedulesResponse)
	err := c.cc.Invoke(ctx, BerichteService_ListSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) ToggleSchedule(ctx context.Context, in *ToggleScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, BerichteService_ToggleSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) GetDashboardKPIs(ctx context.Context, in *DashboardKPIsRequest, opts ...grpc.CallOption) (*DashboardKPIsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardKPIsResponse)
	err := c.cc.Invoke(ctx, BerichteService_GetDashboardKPIs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, BerichteService_CreateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, BerichteService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, BerichteService_UpdateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, BerichteService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, BerichteService_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) ExportDocumentPDF(ctx context.Context, in *ExportDocumentPDFRequest, opts ...grpc.CallOption) (*ExportDocumentPDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportDocumentPDFResponse)
	err := c.cc.Invoke(ctx, BerichteService_ExportDocumentPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, BerichteService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) CreateShareToken(ctx context.Context, in *CreateShareTokenRequest, opts ...grpc.CallOption) (*ShareTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareTokenResponse)
	err := c.cc.Invoke(ctx, BerichteService_CreateShareToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) ListShareTokens(ctx context.Context, in *ListShareTokensRequest, opts ...grpc.CallOption) (*ListShareTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShareTokensResponse)
	err := c.cc.Invoke(ctx, BerichteService_ListShareTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) RevokeShareToken(ctx context.Context, in *RevokeShareTokenRequest, opts ...grpc.CallOption) (*RevokeShareTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeShareTokenResponse)
	err := c.cc.Invoke(ctx, BerichteService_RevokeShareToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *berichteServiceClient) GetSharedDocument(ctx context.Context, in *GetSharedDocumentRequest, opts ...grpc.CallOption) (*GetSharedDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSharedDocumentResponse)
	err := c.cc.Invoke(ctx, BerichteService_GetSharedDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BerichteServiceServer is the server API for BerichteService service.
// All implementations must embed UnimplementedBerichteServiceServer
// for forward compatibility.
type BerichteServiceServer interface {
	// Definitions (CRUD)
	CreateDefinition(context.Context, *CreateDefinitionRequest) (*DefinitionResponse, error)
	GetDefinition(context.Context, *GetDefinitionRequest) (*DefinitionResponse, error)
	UpdateDefinition(context.Context, *UpdateDefinitionRequest) (*DefinitionResponse, error)
	DeleteDefinition(context.Context, *DeleteDefinitionRequest) (*DeleteDefinitionResponse, error)
	ListDefinitions(context.Context, *ListDefinitionsRequest) (*ListDefinitionsResponse, error)
	// Run & Cache
	RunReport(context.Context, *RunReportRequest) (*RunReportResponse, error)
	GetCachedResult(context.Context, *GetCachedResultRequest) (*RunReportResponse, error)
	InvalidateCache(context.Context, *InvalidateCacheRequest) (*InvalidateCacheResponse, error)
	// Export
	ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error)
	// Schedules
	CreateSchedule(context.Context, *CreateScheduleRequest) (*ScheduleResponse, error)
	UpdateSchedule(context.Context, *UpdateScheduleRequest) (*ScheduleResponse, error)
	DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error)
	ToggleSchedule(context.Context, *ToggleScheduleRequest) (*ScheduleResponse, error)
	// KPIs (Dashboard convenience)
	GetDashboardKPIs(context.Context, *DashboardKPIsRequest) (*DashboardKPIsResponse, error)
	// Documents (multi-page authoring)
	CreateDocument(context.Context, *CreateDocumentRequest) (*DocumentResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*DocumentResponse, error)
	UpdateDocument(context.Context, *UpdateDocumentRequest) (*DocumentResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	// ExportDocumentPDF renders the document's block tree (rows -> columns ->
	// blocks) to a PDF via the maroto renderer in berichte/export. See
	// export.DocumentPDFExporter for the block-type mapping.
	ExportDocumentPDF(context.Context, *ExportDocumentPDFRequest) (*ExportDocumentPDFResponse, error)
	// Templates (static starter structures for "Neuer Bericht aus Vorlage")
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	// External share links for a report document.
	CreateShareToken(context.Context, *CreateShareTokenRequest) (*ShareTokenResponse, error)
	ListShareTokens(context.Context, *ListShareTokensRequest) (*ListShareTokensResponse, error)
	RevokeShareToken(context.Context, *RevokeShareTokenRequest) (*RevokeShareTokenResponse, error)
	// GetSharedDocument serves the unauthenticated public read. It takes no
	// tenant_id: the caller has none, and the tenant is resolved from the token
	// itself. See berichte.Service.GetSharedDocument.
	GetSharedDocument(context.Context, *GetSharedDocumentRequest) (*GetSharedDocumentResponse, error)
	mustEmbedUnimplementedBerichteServiceServer()
}

// UnimplementedBerichteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBerichteServiceServer struct{}

func (UnimplementedBerichteServiceServer) CreateDefinition(context.Context, *CreateDefinitionRequest) (*DefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDefinition not implemented")
}
func (UnimplementedBerichteServiceServer) GetDefinition(context.Context, *GetDefinitionRequest) (*DefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefinition not implemented")
}
func (UnimplementedBerichteServiceServer) UpdateDefinition(context.Context, *UpdateDefinitionRequest) (*DefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDefinition not implemented")
}
func (UnimplementedBerichteServiceServer) DeleteDefinition(context.Context, *DeleteDefinitionRequest) (*DeleteDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDefinition not implemented")
}
func (UnimplementedBerichteServiceServer) ListDefinitions(context.Context, *ListDefinitionsRequest) (*ListDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDefinitions not implemented")
}
func (UnimplementedBerichteServiceServer) RunReport(context.Context, *RunReportRequest) (*RunReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunReport not implemented")
}
func (UnimplementedBerichteServiceServer) GetCachedResult(context.Context, *GetCachedResultRequest) (*RunReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCachedResult not implemented")
}
func (UnimplementedBerichteServiceServer) InvalidateCache(context.Context, *InvalidateCacheRequest) (*InvalidateCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvalidateCache not implemented")
}
func (UnimplementedBerichteServiceServer) ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportReport not implemented")
}
func (UnimplementedBerichteServiceServer) CreateSchedule(context.Context, *CreateScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedBerichteServiceServer) UpdateSchedule(context.Context, *UpdateScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSchedule not implemented")
}
func (UnimplementedBerichteServiceServer) DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (UnimplementedBerichteServiceServer) ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchedules not implemented")
}
func (UnimplementedBerichteServiceServer) ToggleSchedule(context.Context, *ToggleScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleSchedule not implemented")
}
func (UnimplementedBerichteServiceServer) GetDashboardKPIs(context.Context, *DashboardKPIsRequest) (*DashboardKPIsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboardKPIs not implemented")
}
func (UnimplementedBerichteServiceServer) CreateDocument(context.Context, *CreateDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDocument not implemented")
}
func (UnimplementedBerichteServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedBerichteServiceServer) UpdateDocument(context.Context, *UpdateDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDocument not implemented")
}
func (UnimplementedBerichteServiceServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedBerichteServiceServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedBerichteServiceServer) ExportDocumentPDF(context.Context, *ExportDocumentPDFRequest) (*ExportDocumentPDFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportDocumentPDF not implemented")
}
func (UnimplementedBerichteServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedBerichteServiceServer) CreateShareToken(context.Context, *CreateShareTokenRequest) (*ShareTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShareToken not implemented")
}
func (UnimplementedBerichteServiceServer) ListShareTokens(context.Context, *ListShareTokensRequest) (*ListShareTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShareTokens not implemented")
}
func (UnimplementedBerichteServiceServer) RevokeShareToken(context.Context, *RevokeShareTokenRequest) (*RevokeShareTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeShareToken not implemented")
}
func (UnimplementedBerichteServiceServer) GetSharedDocument(context.Context, *GetSharedDocumentRequest) (*GetSharedDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSharedDocument not implemented")
}
func (UnimplementedBerichteServiceServer) mustEmbedUnimplementedBerichteServiceServer() {}
func (UnimplementedBerichteServiceServer) testEmbeddedByValue()                         {}

// UnsafeBerichteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BerichteServiceServer will
// result in compilation errors.
type UnsafeBerichteServiceServer interface {
	mustEmbedUnimplementedBerichteServiceServer()
}

func RegisterBerichteServiceServer(s grpc.ServiceRegistrar, srv BerichteServiceServer) {
	// If the following call panics, it indicates UnimplementedBerichteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BerichteService_ServiceDesc, srv)
}

func _BerichteService_CreateDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).CreateDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_CreateDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).CreateDefinition(ctx, req.(*CreateDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_GetDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).GetDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_GetDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).GetDefinition(ctx, req.(*GetDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_UpdateDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).UpdateDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_UpdateDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).UpdateDefinition(ctx, req.(*UpdateDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_DeleteDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).DeleteDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_DeleteDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).DeleteDefinition(ctx, req.(*DeleteDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_ListDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).ListDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_ListDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).ListDefinitions(ctx, req.(*ListDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_RunReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).RunReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_RunReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).RunReport(ctx, req.(*RunReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_GetCachedResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCachedResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).GetCachedResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_GetCachedResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).GetCachedResult(ctx, req.(*GetCachedResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_InvalidateCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).InvalidateCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_InvalidateCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).InvalidateCache(ctx, req.(*InvalidateCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_ExportReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).ExportReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_ExportReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).ExportReport(ctx, req.(*ExportReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_CreateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_UpdateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).UpdateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_UpdateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).UpdateSchedule(ctx, req.(*UpdateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_DeleteSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).DeleteSchedule(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_ListSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).ListSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_ListSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).ListSchedules(ctx, req.(*ListSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_ToggleSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).ToggleSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_ToggleSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).ToggleSchedule(ctx, req.(*ToggleScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_GetDashboardKPIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardKPIsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).GetDashboardKPIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_GetDashboardKPIs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).GetDashboardKPIs(ctx, req.(*DashboardKPIsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_CreateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_UpdateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).UpdateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_UpdateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).UpdateDocument(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_ExportDocumentPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportDocumentPDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).ExportDocumentPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_ExportDocumentPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).ExportDocumentPDF(ctx, req.(*ExportDocumentPDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_CreateShareToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).CreateShareToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_CreateShareToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).CreateShareToken(ctx, req.(*CreateShareTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_ListShareTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShareTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).ListShareTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_ListShareTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).ListShareTokens(ctx, req.(*ListShareTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_RevokeShareToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeShareTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).RevokeShareToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_RevokeShareToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).RevokeShareToken(ctx, req.(*RevokeShareTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BerichteService_GetSharedDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSharedDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerichteServiceServer).GetSharedDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BerichteService_GetSharedDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerichteServiceServer).GetSharedDocument(ctx, req.(*GetSharedDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BerichteService_ServiceDesc is the grpc.ServiceDesc for BerichteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BerichteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "berichte.v1.BerichteService",
	HandlerType: (*BerichteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDefinition",
			Handler:    _BerichteService_CreateDefinition_Handler,
		},
		{
			MethodName: "GetDefinition",
			Handler:    _BerichteService_GetDefinition_Handler,
		},
		{
			MethodName: "UpdateDefinition",
			Handler:    _BerichteService_UpdateDefinition_Handler,
		},
		{
			MethodName: "DeleteDefinition",
			Handler:    _BerichteService_DeleteDefinition_Handler,
		},
		{
			MethodName: "ListDefinitions",
			Handler:    _BerichteService_ListDefinitions_Handler,
		},
		{
			MethodName: "RunReport",
			Handler:    _BerichteService_RunReport_Handler,
		},
		{
			MethodName: "GetCachedResult",
			Handler:    _BerichteService_GetCachedResult_Handler,
		},
		{
			MethodName: "InvalidateCache",
			Handler:    _BerichteService_InvalidateCache_Handler,
		},
		{
			MethodName: "ExportReport",
			Handler:    _BerichteService_ExportReport_Handler,
		},
		{
			MethodName: "CreateSchedule",
			Handler:    _BerichteService_CreateSchedule_Handler,
		},
		{
			MethodName: "UpdateSchedule",
			Handler:    _BerichteService_UpdateSchedule_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _BerichteService_DeleteSchedule_Handler,
		},
		{
			MethodName: "ListSchedules",
			Handler:    _BerichteService_ListSchedules_Handler,
		},
		{
			MethodName: "ToggleSchedule",
			Handler:    _BerichteService_ToggleSchedule_Handler,
		},
		{
			MethodName: "GetDashboardKPIs",
			Handler:    _BerichteService_GetDashboardKPIs_Handler,
		},
		{
			MethodName: "CreateDocument",
			Handler:    _BerichteService_CreateDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _BerichteService_GetDocument_Handler,
		},
		{
			MethodName: "UpdateDocument",
			Handler:    _BerichteService_UpdateDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _BerichteService_DeleteDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _BerichteService_ListDocuments_Handler,
		},
		{
			MethodName: "ExportDocumentPDF",
			Handler:    _BerichteService_ExportDocumentPDF_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _BerichteService_ListTemplates_Handler,
		},
		{
			MethodName: "CreateShareToken",
			Handler:    _BerichteService_CreateShareToken_Handler,
		},
		{
			MethodName: "ListShareTokens",
			Handler:    _BerichteService_ListShareTokens_Handler,
		},
		{
			MethodName: "RevokeShareToken",
			Handler:    _BerichteService_RevokeShareToken_Handler,
		},
		{
			MethodName: "GetSharedDocument",
			Handler:    _BerichteService_GetSharedDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/berichte/v1/berichte.proto",
}
