// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/inventar/v1/inventar.proto

package inventarv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventarService_CreateItem_FullMethodName         = "/inventar.v1.InventarService/CreateItem"
	InventarService_GetItem_FullMethodName            = "/inventar.v1.InventarService/GetItem"
	InventarService_UpdateItem_FullMethodName         = "/inventar.v1.InventarService/UpdateItem"
	InventarService_DeleteItem_FullMethodName         = "/inventar.v1.InventarService/DeleteItem"
	InventarService_ListItems_FullMethodName          = "/inventar.v1.InventarService/ListItems"
	InventarService_AdjustStock_FullMethodName        = "/inventar.v1.InventarService/AdjustStock"
	InventarService_TransferStock_FullMethodName      = "/inventar.v1.InventarService/TransferStock"
	InventarService_RecordMovement_FullMethodName     = "/inventar.v1.InventarService/RecordMovement"
	InventarService_ListMovements_FullMethodName      = "/inventar.v1.InventarService/ListMovements"
	InventarService_GetStockHistory_FullMethodName    = "/inventar.v1.InventarService/GetStockHistory"
	InventarService_CreateWarning_FullMethodName      = "/inventar.v1.InventarService/CreateWarning"
	InventarService_UpdateWarning_FullMethodName      = "/inventar.v1.InventarService/UpdateWarning"
	InventarService_AcknowledgeWarning_FullMethodName = "/inventar.v1.InventarService/AcknowledgeWarning"
	InventarService_ListWarnings_FullMethodName       = "/inventar.v1.InventarService/ListWarnings"
	InventarService_GetStockReport_FullMethodName     = "/inventar.v1.InventarService/GetStockReport"
	InventarService_ExportInventory_FullMethodName    = "/inventar.v1.InventarService/ExportInventory"
)

// InventarServiceClient is the client API for InventarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventarServiceClient interface {
	// Items
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error)
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	// Stock operations
	AdjustStock(ctx context.Context, in *AdjustStockRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	TransferStock(ctx context.Context, in *TransferStockRequest, opts ...grpc.CallOption) (*TransferStockResponse, error)
	RecordMovement(ctx context.Context, in *RecordMovementRequest, opts ...grpc.CallOption) (*MovementResponse, error)
	ListMovements(ctx context.Context, in *ListMovementsRequest, opts ...grpc.CallOption) (*ListMovementsResponse, error)
	GetStockHistory(ctx context.Context, in *GetStockHistoryRequest, opts ...grpc.CallOption) (*ListMovementsResponse, error)
	// Warnings
	CreateWarning(ctx context.Context, in *CreateWarningRequest, opts ...grpc.CallOption) (*WarningResponse, error)
	UpdateWarning(ctx context.Context, in *UpdateWarningRequest, opts ...grpc.CallOption) (*WarningResponse, error)
	AcknowledgeWarning(ctx context.Context, in *AcknowledgeWarningRequest, opts ...grpc.CallOption) (*WarningResponse, error)
	ListWarnings(ctx context.Context, in *ListWarningsRequest, opts ...grpc.CallOption) (*ListWarningsResponse, error)
	// Reports
	GetStockReport(ctx context.Context, in *GetStockReportRequest, opts ...grpc.CallOption) (*StockReportResponse, error)
	ExportInventory(ctx context.Context, in *ExportInventoryRequest, opts ...grpc.CallOption) (*ExportInventoryResponse, error)
}

type inventarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventarServiceClient(cc grpc.ClientConnInterface) InventarServiceClient {
	return &inventarServiceClient{cc}
}

func (c *inventarServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, InventarService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, InventarService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, InventarService_UpdateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteItemResponse)
	err := c.cc.Invoke(ctx, InventarService_DeleteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, InventarService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) AdjustStock(ctx context.Context, in *AdjustStockRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, InventarService_AdjustStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) TransferStock(ctx context.Context, in *TransferStockRequest, opts ...grpc.CallOption) (*TransferStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStockResponse)
	err := c.cc.Invoke(ctx, InventarService_TransferStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) RecordMovement(ctx context.Context, in *RecordMovementRequest, opts ...grpc.CallOption) (*MovementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MovementResponse)
	err := c.cc.Invoke(ctx, InventarService_RecordMovement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) ListMovements(ctx context.Context, in *ListMovementsRequest, opts ...grpc.CallOption) (*ListMovementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMovementsResponse)
	err := c.cc.Invoke(ctx, InventarService_ListMovements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) GetStockHistory(ctx context.Context, in *GetStockHistoryRequest, opts ...grpc.CallOption) (*ListMovementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMovementsResponse)
	err := c.cc.Invoke(ctx, InventarService_GetStockHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) CreateWarning(ctx context.Context, in *CreateWarningRequest, opts ...grpc.CallOption) (*WarningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarningResponse)
	err := c.cc.Invoke(ctx, InventarService_CreateWarning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) UpdateWarning(ctx context.Context, in *UpdateWarningRequest, opts ...grpc.CallOption) (*WarningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarningResponse)
	err := c.cc.Invoke(ctx, InventarService_UpdateWarning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) AcknowledgeWarning(ctx context.Context, in *AcknowledgeWarningRequest, opts ...grpc.CallOption) (*WarningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarningResponse)
	err := c.cc.Invoke(ctx, InventarService_AcknowledgeWarning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) ListWarnings(ctx context.Context, in *ListWarningsRequest, opts ...grpc.CallOption) (*ListWarningsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWarningsResponse)
	err := c.cc.Invoke(ctx, InventarService_ListWarnings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) GetStockReport(ctx context.Context, in *GetStockReportRequest, opts ...grpc.CallOption) (*StockReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockReportResponse)
	err := c.cc.Invoke(ctx, InventarService_GetStockReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventarServiceClient) ExportInventory(ctx context.Context, in *ExportInventoryRequest, opts ...grpc.CallOption) (*ExportInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportInventoryResponse)
	err := c.cc.Invoke(ctx, InventarService_ExportInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventarServiceServer is the server API for InventarService service.
// All implementations must embed UnimplementedInventarServiceServer
// for forward compatibility.
type InventarServiceServer interface {
	// Items
	CreateItem(context.Context, *CreateItemRequest) (*ItemResponse, error)
	GetItem(context.Context, *GetItemRequest) (*ItemResponse, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*ItemResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error)
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	// Stock operations
	AdjustStock(context.Context, *AdjustStockRequest) (*ItemResponse, error)
	TransferStock(context.Context, *TransferStockRequest) (*TransferStockResponse, error)
	RecordMovement(context.Context, *RecordMovementRequest) (*MovementResponse, error)
	ListMovements(context.Context, *ListMovementsRequest) (*ListMovementsResponse, error)
	GetStockHistory(context.Context, *GetStockHistoryRequest) (*ListMovementsResponse, error)
	// Warnings
	CreateWarning(context.Context, *CreateWarningRequest) (*WarningResponse, error)
	UpdateWarning(context.Context, *UpdateWarningRequest) (*WarningResponse, error)
	AcknowledgeWarning(context.Context, *AcknowledgeWarningRequest) (*WarningResponse, error)
	ListWarnings(context.Context, *ListWarningsRequest) (*ListWarningsResponse, error)
	// Reports
	GetStockReport(context.Context, *GetStockReportRequest) (*StockReportResponse, error)
	ExportInventory(context.Context, *ExportInventoryRequest) (*ExportInventoryResponse, error)
	mustEmbedUnimplementedInventarServiceServer()
}

// UnimplementedInventarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventarServiceServer struct{}

func (UnimplementedInventarServiceServer) CreateItem(context.Context, *CreateItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedInventarServiceServer) GetItem(context.Context, *GetItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedInventarServiceServer) UpdateItem(context.Context, *UpdateItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedInventarServiceServer) DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedInventarServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedInventarServiceServer) AdjustStock(context.Context, *AdjustStockRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustStock not implemented")
}
func (UnimplementedInventarServiceServer) TransferStock(context.Context, *TransferStockRequest) (*TransferStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferStock not implemented")
}
func (UnimplementedInventarServiceServer) RecordMovement(context.Context, *RecordMovementRequest) (*MovementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordMovement not implemented")
}
func (UnimplementedInventarServiceServer) ListMovements(context.Context, *ListMovementsRequest) (*ListMovementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMovements not implemented")
}
func (UnimplementedInventarServiceServer) GetStockHistory(context.Context, *GetStockHistoryRequest) (*ListMovementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockHistory not implemented")
}
func (UnimplementedInventarServiceServer) CreateWarning(context.Context, *CreateWarningRequest) (*WarningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWarning not implemented")
}
func (UnimplementedInventarServiceServer) UpdateWarning(context.Context, *UpdateWarningRequest) (*WarningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWarning not implemented")
}
func (UnimplementedInventarServiceServer) AcknowledgeWarning(context.Context, *AcknowledgeWarningRequest) (*WarningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeWarning not implemented")
}
func (UnimplementedInventarServiceServer) ListWarnings(context.Context, *ListWarningsRequest) (*ListWarningsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWarnings not implemented")
}
func (UnimplementedInventarServiceServer) GetStockReport(context.Context, *GetStockReportRequest) (*StockReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockReport not implemented")
}
func (UnimplementedInventarServiceServer) ExportInventory(context.Context, *ExportInventoryRequest) (*ExportInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportInventory not implemented")
}
func (UnimplementedInventarServiceServer) mustEmbedUnimplementedInventarServiceServer() {}
func (UnimplementedInventarServiceServer) testEmbeddedByValue()                         {}

// UnsafeInventarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventarServiceServer will
// result in compilation errors.
type UnsafeInventarServiceServer interface {
	mustEmbedUnimplementedInventarServiceServer()
}

func RegisterInventarServiceServer(s grpc.ServiceRegistrar, srv InventarServiceServer) {
	// If the following call panics, it indicates UnimplementedInventarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventarService_ServiceDesc, srv)
}

func _InventarService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_UpdateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_DeleteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_AdjustStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).AdjustStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_AdjustStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).AdjustStock(ctx, req.(*AdjustStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_TransferStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).TransferStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_TransferStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).TransferStock(ctx, req.(*TransferStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_RecordMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordMovementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).RecordMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_RecordMovement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).RecordMovement(ctx, req.(*RecordMovementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_ListMovements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMovementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).ListMovements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_ListMovements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).ListMovements(ctx, req.(*ListMovementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_GetStockHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).GetStockHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_GetStockHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).GetStockHistory(ctx, req.(*GetStockHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_CreateWarning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWarningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).CreateWarning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_CreateWarning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).CreateWarning(ctx, req.(*CreateWarningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_UpdateWarning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWarningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).UpdateWarning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_UpdateWarning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).UpdateWarning(ctx, req.(*UpdateWarningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_AcknowledgeWarning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeWarningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).AcknowledgeWarning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_AcknowledgeWarning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).AcknowledgeWarning(ctx, req.(*AcknowledgeWarningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_ListWarnings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWarningsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).ListWarnings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_ListWarnings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).ListWarnings(ctx, req.(*ListWarningsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_GetStockReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).GetStockReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_GetStockReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).GetStockReport(ctx, req.(*GetStockReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventarService_ExportInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventarServiceServer).ExportInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventarService_ExportInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventarServiceServer).ExportInventory(ctx, req.(*ExportInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventarService_ServiceDesc is the grpc.ServiceDesc for InventarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventar.v1.InventarService",
	HandlerType: (*InventarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _InventarService_CreateItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _InventarService_GetItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _InventarService_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _InventarService_DeleteItem_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _InventarService_ListItems_Handler,
		},
		{
			MethodName: "AdjustStock",
			Handler:    _InventarService_AdjustStock_Handler,
		},
		{
			MethodName: "TransferStock",
			Handler:    _InventarService_TransferStock_Handler,
		},
		{
			MethodName: "RecordMovement",
			Handler:    _InventarService_RecordMovement_Handler,
		},
		{
			MethodName: "ListMovements",
			Handler:    _InventarService_ListMovements_Handler,
		},
		{
			MethodName: "GetStockHistory",
			Handler:    _InventarService_GetStockHistory_Handler,
		},
		{
			MethodName: "CreateWarning",
			Handler:    _InventarService_CreateWarning_Handler,
		},
		{
			MethodName: "UpdateWarning",
			Handler:    _InventarService_UpdateWarning_Handler,
		},
		{
			MethodName: "AcknowledgeWarning",
			Handler:    _InventarService_AcknowledgeWarning_Handler,
		},
		{
			MethodName: "ListWarnings",
			Handler:    _InventarService_ListWarnings_Handler,
		},
		{
			MethodName: "GetStockReport",
			Handler:    _InventarService_GetStockReport_Handler,
		},
		{
			MethodName: "ExportInventory",
			Handler:    _InventarService_ExportInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventar/v1/inventar.proto",
}
