// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/schichten/v1/schichten.proto

package schichtenv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchichtenService_CreateShift_FullMethodName          = "/schichten.v1.SchichtenService/CreateShift"
	SchichtenService_GetShift_FullMethodName             = "/schichten.v1.SchichtenService/GetShift"
	SchichtenService_UpdateShift_FullMethodName          = "/schichten.v1.SchichtenService/UpdateShift"
	SchichtenService_DeleteShift_FullMethodName          = "/schichten.v1.SchichtenService/DeleteShift"
	SchichtenService_ListShifts_FullMethodName           = "/schichten.v1.SchichtenService/ListShifts"
	SchichtenService_PublishShifts_FullMethodName        = "/schichten.v1.SchichtenService/PublishShifts"
	SchichtenService_AssignEmployee_FullMethodName       = "/schichten.v1.SchichtenService/AssignEmployee"
	SchichtenService_UnassignEmployee_FullMethodName     = "/schichten.v1.SchichtenService/UnassignEmployee"
	SchichtenService_ListAssignments_FullMethodName      = "/schichten.v1.SchichtenService/ListAssignments"
	SchichtenService_CreateTemplate_FullMethodName       = "/schichten.v1.SchichtenService/CreateTemplate"
	SchichtenService_UpdateTemplate_FullMethodName       = "/schichten.v1.SchichtenService/UpdateTemplate"
	SchichtenService_DeleteTemplate_FullMethodName       = "/schichten.v1.SchichtenService/DeleteTemplate"
	SchichtenService_ListTemplates_FullMethodName        = "/schichten.v1.SchichtenService/ListTemplates"
	SchichtenService_ApplyTemplate_FullMethodName        = "/schichten.v1.SchichtenService/ApplyTemplate"
	SchichtenService_CheckArbzgCompliance_FullMethodName = "/schichten.v1.SchichtenService/CheckArbzgCompliance"
	SchichtenService_GetShiftStats_FullMethodName        = "/schichten.v1.SchichtenService/GetShiftStats"
	SchichtenService_CreateSwapRequest_FullMethodName    = "/schichten.v1.SchichtenService/CreateSwapRequest"
	SchichtenService_ListSwapRequests_FullMethodName     = "/schichten.v1.SchichtenService/ListSwapRequests"
	SchichtenService_ApproveSwapRequest_FullMethodName   = "/schichten.v1.SchichtenService/ApproveSwapRequest"
	SchichtenService_RejectSwapRequest_FullMethodName    = "/schichten.v1.SchichtenService/RejectSwapRequest"
)

// SchichtenServiceClient is the client API for SchichtenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchichtenServiceClient interface {
	// Shifts
	CreateShift(ctx context.Context, in *CreateShiftRequest, opts ...grpc.CallOption) (*ShiftResponse, error)
	GetShift(ctx context.Context, in *GetShiftRequest, opts ...grpc.CallOption) (*ShiftResponse, error)
	UpdateShift(ctx context.Context, in *UpdateShiftRequest, opts ...grpc.CallOption) (*ShiftResponse, error)
	DeleteShift(ctx context.Context, in *DeleteShiftRequest, opts ...grpc.CallOption) (*DeleteShiftResponse, error)
	ListShifts(ctx context.Context, in *ListShiftsRequest, opts ...grpc.CallOption) (*ListShiftsResponse, error)
	PublishShifts(ctx context.Context, in *PublishShiftsRequest, opts ...grpc.CallOption) (*PublishShiftsResponse, error)
	// Assignments
	AssignEmployee(ctx context.Context, in *AssignEmployeeRequest, opts ...grpc.CallOption) (*AssignmentResponse, error)
	UnassignEmployee(ctx context.Context, in *UnassignEmployeeRequest, opts ...grpc.CallOption) (*UnassignEmployeeResponse, error)
	ListAssignments(ctx context.Context, in *ListAssignmentsRequest, opts ...grpc.CallOption) (*ListAssignmentsResponse, error)
	// Templates
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error)
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	ApplyTemplate(ctx context.Context, in *ApplyTemplateRequest, opts ...grpc.CallOption) (*ApplyTemplateResponse, error)
	// Compliance & Stats
	CheckArbzgCompliance(ctx context.Context, in *CheckArbzgComplianceRequest, opts ...grpc.CallOption) (*CheckArbzgComplianceResponse, error)
	GetShiftStats(ctx context.Context, in *GetShiftStatsRequest, opts ...grpc.CallOption) (*ShiftStatsResponse, error)
	// Swap Requests
	CreateSwapRequest(ctx context.Context, in *CreateSwapRequestRequest, opts ...grpc.CallOption) (*SwapRequestResponse, error)
	ListSwapRequests(ctx context.Context, in *ListSwapRequestsRequest, opts ...grpc.CallOption) (*ListSwapRequestsResponse, error)
	ApproveSwapRequest(ctx context.Context, in *ApproveSwapRequestRequest, opts ...grpc.CallOption) (*SwapRequestResponse, error)
	RejectSwapRequest(ctx context.Context, in *RejectSwapRequestRequest, opts ...grpc.CallOption) (*SwapRequestResponse, error)
}

type schichtenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchichtenServiceClient(cc grpc.ClientConnInterface) SchichtenServiceClient {
	return &schichtenServiceClient{cc}
}

func (c *schichtenServiceClient) CreateShift(ctx context.Context, in *CreateShiftRequest, opts ...grpc.CallOption) (*ShiftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShiftResponse)
	err := c.cc.Invoke(ctx, SchichtenService_CreateShift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) GetShift(ctx context.Context, in *GetShiftRequest, opts ...grpc.CallOption) (*ShiftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShiftResponse)
	err := c.cc.Invoke(ctx, SchichtenService_GetShift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) UpdateShift(ctx context.Context, in *UpdateShiftRequest, opts ...grpc.CallOption) (*ShiftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShiftResponse)
	err := c.cc.Invoke(ctx, SchichtenService_UpdateShift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) DeleteShift(ctx context.Context, in *DeleteShiftRequest, opts ...grpc.CallOption) (*DeleteShiftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShiftResponse)
	err := c.cc.Invoke(ctx, SchichtenService_DeleteShift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) ListShifts(ctx context.Context, in *ListShiftsRequest, opts ...grpc.CallOption) (*ListShiftsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShiftsResponse)
	err := c.cc.Invoke(ctx, SchichtenService_ListShifts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) PublishShifts(ctx context.Context, in *PublishShiftsRequest, opts ...grpc.CallOption) (*PublishShiftsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishShiftsResponse)
	err := c.cc.Invoke(ctx, SchichtenService_PublishShifts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) AssignEmployee(ctx context.Context, in *AssignEmployeeRequest, opts ...grpc.CallOption) (*AssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignmentResponse)
	err := c.cc.Invoke(ctx, SchichtenService_AssignEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) UnassignEmployee(ctx context.Context, in *UnassignEmployeeRequest, opts ...grpc.CallOption) (*UnassignEmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignEmployeeResponse)
	err := c.cc.Invoke(ctx, SchichtenService_UnassignEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) ListAssignments(ctx context.Context, in *ListAssignmentsRequest, opts ...grpc.CallOption) (*ListAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssignmentsResponse)
	err := c.cc.Invoke(ctx, SchichtenService_ListAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, SchichtenService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, SchichtenService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateResponse)
	err := c.cc.Invoke(ctx, SchichtenService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, SchichtenService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) ApplyTemplate(ctx context.Context, in *ApplyTemplateRequest, opts ...grpc.CallOption) (*ApplyTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyTemplateResponse)
	err := c.cc.Invoke(ctx, SchichtenService_ApplyTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) CheckArbzgCompliance(ctx context.Context, in *CheckArbzgComplianceRequest, opts ...grpc.CallOption) (*CheckArbzgComplianceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckArbzgComplianceResponse)
	err := c.cc.Invoke(ctx, SchichtenService_CheckArbzgCompliance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) GetShiftStats(ctx context.Context, in *GetShiftStatsRequest, opts ...grpc.CallOption) (*ShiftStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShiftStatsResponse)
	err := c.cc.Invoke(ctx, SchichtenService_GetShiftStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) CreateSwapRequest(ctx context.Context, in *CreateSwapRequestRequest, opts ...grpc.CallOption) (*SwapRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapRequestResponse)
	err := c.cc.Invoke(ctx, SchichtenService_CreateSwapRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) ListSwapRequests(ctx context.Context, in *ListSwapRequestsRequest, opts ...grpc.CallOption) (*ListSwapRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSwapRequestsResponse)
	err := c.cc.Invoke(ctx, SchichtenService_ListSwapRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) ApproveSwapRequest(ctx context.Context, in *ApproveSwapRequestRequest, opts ...grpc.CallOption) (*SwapRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapRequestResponse)
	err := c.cc.Invoke(ctx, SchichtenService_ApproveSwapRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schichtenServiceClient) RejectSwapRequest(ctx context.Context, in *RejectSwapRequestRequest, opts ...grpc.CallOption) (*SwapRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapRequestResponse)
	err := c.cc.Invoke(ctx, SchichtenService_RejectSwapRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchichtenServiceServer is the server API for SchichtenService service.
// All implementations must embed UnimplementedSchichtenServiceServer
// for forward compatibility.
type SchichtenServiceServer interface {
	// Shifts
	CreateShift(context.Context, *CreateShiftRequest) (*ShiftResponse, error)
	GetShift(context.Context, *GetShiftRequest) (*ShiftResponse, error)
	UpdateShift(context.Context, *UpdateShiftRequest) (*ShiftResponse, error)
	DeleteShift(context.Context, *DeleteShiftRequest) (*DeleteShiftResponse, error)
	ListShifts(context.Context, *ListShiftsRequest) (*ListShiftsResponse, error)
	PublishShifts(context.Context, *PublishShiftsRequest) (*PublishShiftsResponse, error)
	// Assignments
	AssignEmployee(context.Context, *AssignEmployeeRequest) (*AssignmentResponse, error)
	UnassignEmployee(context.Context, *UnassignEmployeeRequest) (*UnassignEmployeeResponse, error)
	ListAssignments(context.Context, *ListAssignmentsRequest) (*ListAssignmentsResponse, error)
	// Templates
	CreateTemplate(context.Context, *CreateTemplateRequest) (*TemplateResponse, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*TemplateResponse, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	ApplyTemplate(context.Context, *ApplyTemplateRequest) (*ApplyTemplateResponse, error)
	// Compliance & Stats
	CheckArbzgCompliance(context.Context, *CheckArbzgComplianceRequest) (*CheckArbzgComplianceResponse, error)
	GetShiftStats(context.Context, *GetShiftStatsRequest) (*ShiftStatsResponse, error)
	// Swap Requests
	CreateSwapRequest(context.Context, *CreateSwapRequestRequest) (*SwapRequestResponse, error)
	ListSwapRequests(context.Context, *ListSwapRequestsRequest) (*ListSwapRequestsResponse, error)
	ApproveSwapRequest(context.Context, *ApproveSwapRequestRequest) (*SwapRequestResponse, error)
	RejectSwapRequest(context.Context, *RejectSwapRequestRequest) (*SwapRequestResponse, error)
	mustEmbedUnimplementedSchichtenServiceServer()
}

// UnimplementedSchichtenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchichtenServiceServer struct{}

func (UnimplementedSchichtenServiceServer) CreateShift(context.Context, *CreateShiftRequest) (*ShiftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShift not implemented")
}
func (UnimplementedSchichtenServiceServer) GetShift(context.Context, *GetShiftRequest) (*ShiftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShift not implemented")
}
func (UnimplementedSchichtenServiceServer) UpdateShift(context.Context, *UpdateShiftRequest) (*ShiftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShift not implemented")
}
func (UnimplementedSchichtenServiceServer) DeleteShift(context.Context, *DeleteShiftRequest) (*DeleteShiftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShift not implemented")
}
func (UnimplementedSchichtenServiceServer) ListShifts(context.Context, *ListShiftsRequest) (*ListShiftsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShifts not implemented")
}
func (UnimplementedSchichtenServiceServer) PublishShifts(context.Context, *PublishShiftsRequest) (*PublishShiftsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishShifts not implemented")
}
func (UnimplementedSchichtenServiceServer) AssignEmployee(context.Context, *AssignEmployeeRequest) (*AssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignEmployee not implemented")
}
func (UnimplementedSchichtenServiceServer) UnassignEmployee(context.Context, *UnassignEmployeeRequest) (*UnassignEmployeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnassignEmployee not implemented")
}
func (UnimplementedSchichtenServiceServer) ListAssignments(context.Context, *ListAssignmentsRequest) (*ListAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssignments not implemented")
}
func (UnimplementedSchichtenServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedSchichtenServiceServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedSchichtenServiceServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedSchichtenServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedSchichtenServiceServer) ApplyTemplate(context.Context, *ApplyTemplateRequest) (*ApplyTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyTemplate not implemented")
}
func (UnimplementedSchichtenServiceServer) CheckArbzgCompliance(context.Context, *CheckArbzgComplianceRequest) (*CheckArbzgComplianceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckArbzgCompliance not implemented")
}
func (UnimplementedSchichtenServiceServer) GetShiftStats(context.Context, *GetShiftStatsRequest) (*ShiftStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShiftStats not implemented")
}
func (UnimplementedSchichtenServiceServer) CreateSwapRequest(context.Context, *CreateSwapRequestRequest) (*SwapRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSwapRequest not implemented")
}
func (UnimplementedSchichtenServiceServer) ListSwapRequests(context.Context, *ListSwapRequestsRequest) (*ListSwapRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSwapRequests not implemented")
}
func (UnimplementedSchichtenServiceServer) ApproveSwapRequest(context.Context, *ApproveSwapRequestRequest) (*SwapRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveSwapRequest not implemented")
}
func (UnimplementedSchichtenServiceServer) RejectSwapRequest(context.Context, *RejectSwapRequestRequest) (*SwapRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectSwapRequest not implemented")
}
func (UnimplementedSchichtenServiceServer) mustEmbedUnimplementedSchichtenServiceServer() {}
func (UnimplementedSchichtenServiceServer) testEmbeddedByValue()                          {}

// UnsafeSchichtenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchichtenServiceServer will
// result in compilation errors.
type UnsafeSchichtenServiceServer interface {
	mustEmbedUnimplementedSchichtenServiceServer()
}

func RegisterSchichtenServiceServer(s grpc.ServiceRegistrar, srv SchichtenServiceServer) {
	// If the following call panics, it indicates UnimplementedSchichtenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchichtenService_ServiceDesc, srv)
}

func _SchichtenService_CreateShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).CreateShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_CreateShift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).CreateShift(ctx, req.(*CreateShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_GetShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).GetShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_GetShift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).GetShift(ctx, req.(*GetShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_UpdateShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).UpdateShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_UpdateShift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).UpdateShift(ctx, req.(*UpdateShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_DeleteShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).DeleteShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_DeleteShift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).DeleteShift(ctx, req.(*DeleteShiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_ListShifts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShiftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).ListShifts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_ListShifts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).ListShifts(ctx, req.(*ListShiftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_PublishShifts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishShiftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).PublishShifts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_PublishShifts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).PublishShifts(ctx, req.(*PublishShiftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_AssignEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).AssignEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_AssignEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).AssignEmployee(ctx, req.(*AssignEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_UnassignEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).UnassignEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_UnassignEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).UnassignEmployee(ctx, req.(*UnassignEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_ListAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).ListAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_ListAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).ListAssignments(ctx, req.(*ListAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_ApplyTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).ApplyTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_ApplyTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).ApplyTemplate(ctx, req.(*ApplyTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_CheckArbzgCompliance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckArbzgComplianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).CheckArbzgCompliance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_CheckArbzgCompliance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).CheckArbzgCompliance(ctx, req.(*CheckArbzgComplianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_GetShiftStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShiftStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).GetShiftStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_GetShiftStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).GetShiftStats(ctx, req.(*GetShiftStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_CreateSwapRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSwapRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).CreateSwapRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_CreateSwapRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).CreateSwapRequest(ctx, req.(*CreateSwapRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_ListSwapRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSwapRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).ListSwapRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_ListSwapRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).ListSwapRequests(ctx, req.(*ListSwapRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_ApproveSwapRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveSwapRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).ApproveSwapRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_ApproveSwapRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).ApproveSwapRequest(ctx, req.(*ApproveSwapRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchichtenService_RejectSwapRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectSwapRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchichtenServiceServer).RejectSwapRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchichtenService_RejectSwapRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchichtenServiceServer).RejectSwapRequest(ctx, req.(*RejectSwapRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchichtenService_ServiceDesc is the grpc.ServiceDesc for SchichtenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchichtenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schichten.v1.SchichtenService",
	HandlerType: (*SchichtenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShift",
			Handler:    _SchichtenService_CreateShift_Handler,
		},
		{
			MethodName: "GetShift",
			Handler:    _SchichtenService_GetShift_Handler,
		},
		{
			MethodName: "UpdateShift",
			Handler:    _SchichtenService_UpdateShift_Handler,
		},
		{
			MethodName: "DeleteShift",
			Handler:    _SchichtenService_DeleteShift_Handler,
		},
		{
			MethodName: "ListShifts",
			Handler:    _SchichtenService_ListShifts_Handler,
		},
		{
			MethodName: "PublishShifts",
			Handler:    _SchichtenService_PublishShifts_Handler,
		},
		{
			MethodName: "AssignEmployee",
			Handler:    _SchichtenService_AssignEmployee_Handler,
		},
		{
			MethodName: "UnassignEmployee",
			Handler:    _SchichtenService_UnassignEmployee_Handler,
		},
		{
			MethodName: "ListAssignments",
			Handler:    _SchichtenService_ListAssignments_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _SchichtenService_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _SchichtenService_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _SchichtenService_DeleteTemplate_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _SchichtenService_ListTemplates_Handler,
		},
		{
			MethodName: "ApplyTemplate",
			Handler:    _SchichtenService_ApplyTemplate_Handler,
		},
		{
			MethodName: "CheckArbzgCompliance",
			Handler:    _SchichtenService_CheckArbzgCompliance_Handler,
		},
		{
			MethodName: "GetShiftStats",
			Handler:    _SchichtenService_GetShiftStats_Handler,
		},
		{
			MethodName: "CreateSwapRequest",
			Handler:    _SchichtenService_CreateSwapRequest_Handler,
		},
		{
			MethodName: "ListSwapRequests",
			Handler:    _SchichtenService_ListSwapRequests_Handler,
		},
		{
			MethodName: "ApproveSwapRequest",
			Handler:    _SchichtenService_ApproveSwapRequest_Handler,
		},
		{
			MethodName: "RejectSwapRequest",
			Handler:    _SchichtenService_RejectSwapRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/schichten/v1/schichten.proto",
}
